### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Danteoriginal** [pvpgn/pvpgn-server#102]
when he was playing after completing the game, the server goes down and I appeared in this log

ep 02 07:39:24 [info ] pvpgn::bnetd::conn_destroy: [448] "Dante" logged out
Sep 02 07:39:24 [info ] pvpgn::bnetd::conn_destroy: [448] closed bnet connection
Sep 08 18:06:06 [info ] eventlog_startup: logging event levels: fatal,error,warn,info

is normal or is it a bug?

Greetings

**Comment by Danteoriginal** [comment]
hello harpywar

Works well in compiling build the server, but when compiled in release of the server goes down

regards

**Comment by HarpyWar** [comment]
@Danteoriginal please, try reproduce the crash on the test server https://github.com/HarpyWar/pvpgn/issues/130
