### ISSUE TITLE
Can't login after a restart

### ISSUE THREAD

**Issue by lord-bagheera** [pvpgn/pvpgn-server#104]
i've just compile  a brand new pvpgn on my Linux 3.2.0-4-sparc64 #1 Debian 3.2.60-1+deb7u3 sparc64 GNU/Linux just like we do before some years ago. I compile following instructions on the video.
all seems to work.
After configure sql repo and start the server i go to create a account, logout and login again, w/no problem
go to phpmyadmin and modified auth_command_groups to 255 and auth_admin to true, commit the change, try login, ok, but no admin or cg's o none rights in the server. they say "this command is reserved for admins" but i send /help !!!!!

I stop the server and after few hours restart, but now i can't login: log says
Sep 24 12:48:49 [trace] sql_read_account: SELECT uid FROM BNET WHERE username='masshiroi'
Sep 24 12:48:49 [info ] _client_loginreq2: [19] login for "masshiroi" refused (no such account)

y create other account and do the same steps (including the restart) and i get exact same results.

**Comment by Danteoriginal** [comment]
I think the problem started from these two modifications

https://github.com/HarpyWar/pvpgn/commit/c2cd07b1dd176b49e9092bde15a57292f653bb6b
https://github.com/HarpyWar/pvpgn/commit/3613ad99f012d76a4189cf691c2996383857748f

I have been adding modifications without these two and so far I'm going to the server worked well

regards

**Comment by lord-bagheera** [comment]
I've update and rebuild, we still have the same problem, i've have some delay because my old netra's powersource was blown, actually we try to get another one to use. so close this issue untill we get one

meawhile i try with an intel machine
