### ISSUE TITLE
Lockdown implementation

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#112]
We should unify the VersionCheck system by updating to lockdown and only use 1 file for all games.
All documentation/information for CheckRevision function should be posted here.

**Comment by xboi209** [comment]
http://www.stealthbot.net/board/index.php?showtopic=21774

**Comment by xboi209** [comment]
https://github.com/xboi209/CheckRevision
Hashing function is broken in my CheckRevision code but PvPGN can still guess the client based on other data automatically. I don't think I'm going to be doing research or implementing Lockdown.
