### ISSUE TITLE
Serverside spoofcheck

### ISSUE THREAD

**Issue by DingGGu** [pvpgn/pvpgn-server#127]
is it possible?

use game packet

**Comment by cen1** [comment]
Most hostbots do a hard spoof check by requesting player to send a whisper: ```/w botname sc```
On our server I made an automatic response with custom gproxy implementation.
In this case, bot would have to request spoof from pvpgn and pvpgn would then request ExtraWork to issue a whisper to the bot.
@xboi209 do we have any examples of ExtraWork usage so far? Maybe even a simple pingback packet? Can you provide one?

**Comment by xboi209** [comment]
@cen1 I think it would take some work to send a packet to PvPGN and then link that packet to a current connection/user. I'm not aware of anyone using ExtraWork right now.
