### ISSUE TITLE
Gamespy Support

### ISSUE THREAD

**Issue by TheSkeletonSK** [pvpgn/pvpgn-server#128]
Gamespy Emulation. Wouldn't that be rad? Im tired of seeing all these classic gamespy games die out to the lack of an alternative or the new complications of using an alternative.

Also, some sort of helper client would be cool. Like, im no programmer,but maybe it could redirect a game's connections to a pvpgn server before it leaves the pc. Like editing a hosts file without, you know, editing the hosts file. Would make things nice for more simpleminded gamers.

**Comment by xboi209** [comment]
While having GameSpy support is certainly possible, development here has been primarily focused on Battle.net clients. You probably won't find luck here unless there's a sudden surge of interested programmers.

**Comment by LipkeGu** [comment]
Gamespy is an encrypted IRC protocol i had tried it along time to implement in an older pvpgn release

yes there are server emulators for BF2 and so on which can emulate an GS server maybe a good start? :)

**Comment by TheSkeletonSK** [comment]
http://zenhax.com/viewtopic.php?t=6
There seems to be quite a bit of information here on the matter. I hope it can be of use if Gamespy support continues to be considered.

**Comment by stas730** [comment]
We can use OpenSpy server (not available in source code or binaries). / Мы можем использовать сервер OpenSpy (исходный код или исполняемые файлы недоступны).

**Comment by stas730** [comment]
OpenSpy for sniffing. / OpenSpy для "сниффинга" пакетов.

**Comment by stas730** [comment]
Stop. Code is available! / Стойте. Код доступен!
http://zenhax.com/viewtopic.php?t=6
