### ISSUE TITLE
TEST SERVER

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#130]
Hello, my friend, stay awhile and listen!

There is Battle.net test server is running with the latest `PvPGN-PRO` build. 
Address: `server.pvpgn.pro`

Last months development was freezed, because current version is not stable. Many people said that it crashes often and randomly. 
We need testers who may exhibit normal activity (play and use any commands there). Then crash dumps  will be explored to fix any problems that causes a crash.
And don't forget report any bugs that you found!

You can connect there with any supported client, including Diablo 2, IRC or bot(telnet) login.
Let's make PvPGN software better together!

**Comment by Artyom91** [comment]
@HarpyWar Запустить бота?

**Comment by HarpyWar** [comment]
@Artyom91 если есть такая возможность, то бот будет не лишним!

**Comment by Artyom91** [comment]
@HarpyWar Отключили только что?

**Comment by HarpyWar** [comment]
Первое время сервер может работать нестабильно. Впрочем, это и требуется. 
Чем больше раз он упадет, тем больше можно ошибок исправить!

**Comment by Artyom91** [comment]
@HarpyWar Ну тогда вот косяк, при регистрации (вводи логина и пароля) нажимаешь зарегистрироваться, виснет, нажимаешь отмена - он заходит в главное меню, вводишь данные - не подключается, пишет нет соединения с BNET, заходишь через через несколько минут, вводишь данные и входишь, без регистрации, значит первый раз данные отправляются.

**Comment by HarpyWar** [comment]
Когда вылезает debug assertion на Windows, то сервер продолжать работать, но не позволяет авторизоваться. На тот момент как раз могла быть такая ситуация. С тех пор сервер работал стабильно, но вместе с этим замечены большие утечки памяти http://forums.harpywar.com/viewtopic.php?id=1293

**Comment by Artyom91** [comment]
Забыл совсем про вас, запущу сегодня одного бота.

**Comment by anonprophet** [comment]
harpywar, can i use this version of pvpgn on production server?
its ready now ?

**Comment by HarpyWar** [comment]
@anonprophet the project will be ready when v2.0 is released. But you can try use it now.

I didn't get any crashes last time on the test server, because there is extremely small online, but other server admins said that it crashes very often. And as I said above there are memory leaks in current codebase.
Do you have several players who can play several games on the test server?

**Comment by Danteoriginal** [comment]
hello harpywar
bug no rating in games

regards

**Comment by HarpyWar** [comment]
@Danteoriginal Please, create a new bug report issue with the details. Now I do not know what you're talking about .

**Comment by anonprophet** [comment]
@HarpyWar sure, but my users only play WC3 Client especially DotA, LoD, etc

**Comment by anonprophet** [comment]
my server already up 2 days, without crash
already try all commands
i think this pvpgn already stable?

im only try using WC3

**Comment by Kelwing** [comment]
If its running great for you, then feel free to keep using it.  There have been other reports, so I'm sure that's why HarpyWar isn't comfortable with calling it stable.

**Comment by Danteoriginal** [comment]
hello harpywar

no pts in game ladder, check game report

regards
