### ISSUE TITLE
StarCraft: Brood War hack detection

### ISSUE THREAD

**Issue by xboi209** [pvpgn/pvpgn-server#137]
I'm publishing my research on offsets that hacks for StarCraft: Brood War change.
http://pastebin.com/4vs7FNMn

**Comment by HarpyWar** [comment]
Great! 
Will you do something open source/public based on it or it's just an info for antihack developers?

Reference https://github.com/HarpyWar/pvpgn/pull/26 https://github.com/HarpyWar/pvpgn/issues/72

**Comment by xboi209** [comment]
This is just info, it could be used for the SID_READMEMORY packet.
