### ISSUE TITLE
if Windows and storage_path = file:mode=plain,client use accname="CON" login,server down

### ISSUE THREAD

**Issue by yjfyy** [pvpgn/pvpgn-server#140]
use pvpgn-magic-builder ver 2.07
download the latest PvPGN source from GIT
1) Console (defaut)
1) Plain / CDB (default)
Enable Lua scripting support?
[Y,N]?N

build

run pvpgn

battnet ip = 127.0.0.1
run diablo II
acc name= con
password=x
enter
server down
# 

if  acc name=com1 and computer have com1
server down
# 

if acc name=com2 and computer not have com2
server is ok

**Comment by Kelwing** [comment]
Ok, so it looks like if you use a flat file database (which you shouldn't do, and a feature that should honestly be removed) and use an account name which matches an available COM port on windows, the server crashes.

**Comment by cen1** [comment]
Unable to replicate this using W3 as the client.
```Mar 02 17:13:18 [info ] pvpgn::bnetd::_client_loginreqw3: [468] (W3) login for "CON" refused (no such account)```

SOmeone with D2 please try to replicate it. Also, @yjfyy provide var/bnetd.log

**Comment by yjfyy** [comment]
Mar 04 16:12:03 [info ] pvpgn::bnetd::_setup_listensock: listening for bnet connections on 0.0.0.0:6112 TCP
Mar 04 16:12:03 [info ] pvpgn::bnetd::_setup_listensock: listening for w3route connections on 0.0.0.0:6200 TCP
Mar 04 16:12:33 [info ] pvpgn::bnetd::sd_accept: [144] accepted connection from 127.0.0.1:50018 on 0.0.0.0:6112
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_create: [144][400] sessionkey=0x54f6d678 sessionnum=0x00000000
Mar 04 16:12:33 [info ] pvpgn::bnetd::handle_init_packet: [144] client initiated bnet connection
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_set_archtag: [144] setting client arch to "IX86"
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_set_clienttag: [144] setting client type to "D2XP"
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_set_gamelang: [144] setting client gamelang to "zhTW"
Mar 04 16:12:33 [info ] pvpgn::bnetd::sd_accept: [328] accepted connection from 127.0.0.1:50019 on 0.0.0.0:6112
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_create: [328][400] sessionkey=0x54f6ceef sessionnum=0x00000001
Mar 04 16:12:33 [info ] pvpgn::bnetd::handle_init_packet: [328] client initiated file download connection
Mar 04 16:12:33 [info ] pvpgn::bnetd::file_send: [328] sending file "IX86ver1.mpq" ("files/IX86ver1.mpq") of length 6963
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_destroy: [328] closed file connection
Mar 04 16:12:33 [info ] pvpgn::bnetd::_client_authreq109: [144] CLIENT_AUTHREQ_109 ticks=0x55091bdc, verstr=1.0.12.0 exeinfo="Game.exe 05/28/08 01:44:02 61440" versionid=0x0000000c gameversion=0x01000c00 checksum=0x3d421510
Mar 04 16:12:33 [info ] pvpgn::bnetd::versioncheck_validate: got a matching entry: D2XP_112A
Mar 04 16:12:33 [info ] pvpgn::bnetd::_client_authreq109: [144] client matches versiontag "D2XP_112A"
Mar 04 16:12:33 [info ] pvpgn::bnetd::_client_authreq109: [144] no upgrade for D2XP_112A is available
Mar 04 16:12:33 [info ] pvpgn::bnetd::_client_fileinforeq: [144] file requested: "bnserver-D2DV.ini" - type = 0x80000004
Mar 04 16:12:33 [info ] pvpgn::bnetd::sd_accept: [328] accepted connection from 127.0.0.1:50020 on 0.0.0.0:6112
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_create: [328][400] sessionkey=0x54f69cb0 sessionnum=0x00000002
Mar 04 16:12:33 [info ] pvpgn::bnetd::handle_init_packet: [328] client initiated file download connection
Mar 04 16:12:33 [info ] pvpgn::bnetd::file_send: [328] sending file "bnserver-D2DV.ini" ("files/bnserver-D2DV.ini") of length 336
Mar 04 16:12:33 [info ] pvpgn::bnetd::conn_destroy: [328] closed file connection

**Comment by HarpyWar** [comment]
The reserved file names should be prohibited on Windows for d2dbs and pvpgn plain mode:
`com1, com2, com3, com4, com5, com6, com7, com8, com9, lpt1, lpt2, lpt3, lpt4, lpt5, lpt6, lpt7, lpt8, lpt9, con, nul, prn`

https://kb.acronis.com/node/39790

**Comment by MxCen** [comment]
修改account.c文件accountlist_load_account函数889行
if (stat(pathname, &statbuf) < 0) {
增加一个条件判断
改为
if (stat(pathname, &statbuf) < 0 || (statbuf.st_size == 0 && statbuf.st_mtime == -1)) {
