### ISSUE TITLE
Replace char's with std::string's

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#141]
#132

**Comment by cen1** [comment]
Does pvpgn need Unicode anywhere in the code? And what is the encoding coming from the game clients?

**Comment by xboi209** [comment]
StarCraft does Windows 1252 -> UTF-8 conversion when sending text to the server.
I think WarCraft 3 also uses UTF-8.

**Comment by xboi209** [comment]
Does the ````localize```` function return a string or char?
