### ISSUE TITLE
0x19 MessageBox

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#15]
![image](https://cloud.githubusercontent.com/assets/1463845/2885685/2fd1f2f4-d4cb-11e3-8107-5beb7e961805.png)
Successful implementation of packet 0x19 for MessageBox

```
//packet.h
t_server_messagebox         server_messagebox;
```

```
//packet.cpp
case SERVER_MESSAGEBOX:
    return "SERVER_MESSAGEBOX";
```

```
//bnetprotocol.h
#define SERVER_MESSAGEBOX 0x19ff
    typedef struct
    {
        t_bnet_header h;
        bn_int        style;
        /* Text */
        /* Caption */
    } PACKED_ATTR() t_server_messagebox;
#define SERVER_MESSAGEBOX_OK    0x00000000
#define SERVER_MESSAGEBOX_OK_CANCEL 0x00000001
```

```
//Example code:
t_packet *rpacket;

if ((rpacket = packet_create(packet_class_bnet)))
{
    packet_set_size(rpacket, sizeof(t_server_messagebox));
    packet_set_type(rpacket, SERVER_MESSAGEBOX);
    bn_int_set(&rpacket->u.server_messagebox.style, SERVER_MESSAGEBOX_OK);
    packet_append_string(rpacket, "Text");
    packet_append_string(rpacket, "");
    conn_push_outqueue(c, rpacket);
    packet_del_ref(rpacket);
}

return 0;
```

In `bn_int_set(&rpacket->u.server_messagebox.style, SERVER_MESSAGEBOX_OK);`
`SERVER_MESSAGEBOX_OK` creates an `Ok` button while `SERVER_MESSAGEBOX_OK_CANCEL` creates an `Ok` and `Cancel` button for the client.
![image](https://cloud.githubusercontent.com/assets/1463845/2885710/07962304-d4cc-11e3-90dd-31254d6c453d.png)
There is no purpose in having both `Ok` and `Cancel` buttons because the server will not know which button the user has pressed(and from my testing, you can ignore the messagebox and click other buttons such as `Join` and `Create`) so I've hardcoded `SERVER_MESSAGEBOX_OK` as the value.

**Comment by xpeh-owns** [comment]
> The way Starcraft works, at least as far as I remember, is it will pass the packet directly to the WinAPI MessageBox function. 
There was a bug in windows in which messagebox with certaing parameters caused bluescreen :)
