### ISSUE TITLE
Memory leak discussion

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#152]
I'm creating this issue to serve as a discussion so that any experienced C/C++ programmer can confirm my suspicions on potential memory leaks.

**Comment by xboi209** [comment]
###xstrdup()
````xstrdup()```` needs its results freed or else memory will stay consumed.
Potential issues:
* ````command.cpp````
  * Line 4213: Shouldn't ````xfree(data.p);```` be moved to after the entire if statement?
* ````tag.cpp````
  * Line 370: Does variable ````p```` also need to be freed?

**Comment by cen1** [comment]
I am just an average in C++ but I'll give it a try.

1. Struct attribute ```p``` is a pointer and it will be passed as a part of data struct to the timerlist_add_timer function. If you free it when the insert was successful, the pointer in the copied data structure will become invalid.

2. I believe malloc is executed once in this case and both pointers point to the same memory region. So freeing it once is enough, you'd do a double free which is bad.

3. I think it can be freed since it's only passed to ```sprintf``` and that will copy the value into the buffer.

4. I think yes. Also, what's up with ```tempacct```? Pretty sure that needs to be freed too (probably with some account function).

5. I think so. But it should be checked for null pointer because of line 170.

6. Seems that all the pointers defined at the beginning of the function are just iterators or temporary pointers to a global ```icon_head``` or it's attributes, they don't allocate anything as far as I can see.

7. Seems so.

8. Yes

9. No, it points to the same memory as ```s``` and ```s``` is freed.


I am only 90% positive on some of these so a third person chiming in would be great.

**Comment by xboi209** [comment]
So the offending line of code is from function ````file_get_defacct()```` [bnetd/storage_file.cpp Line 369](/HarpyWar/pvpgn/blob/master/src/bnetd/storage_file.cpp#L369).

The function is actually used in PvPGN code as a member of a struct called ````storage````: [bnetd/storage.h Line 46](/HarpyWar/pvpgn/blob/master/src/bnetd/storage.h#L46)

It sounds like the return value of ````file_get_defacct()```` needs to be freed with ````file_free_info()````.

````storage->get_defacct()```` is used in two places:
1. [bnetd/attrgroup.cpp Line 20](/HarpyWar/pvpgn/blob/master/src/bnetd/attrgroup.cpp#L20)
2. [bnetd/attrlayer.cpp Line 65](/HarpyWar/pvpgn/blob/master/src/bnetd/attrlayer.cpp#L65)

For ````1.````, the return value of ````storage->get_defacct()```` is converted into an ````unsigned int````.
For ````2.````, the return value is passed as a parameter to ````attrgroup_create_storage()````.

**Comment by Danteoriginal** [comment]
https://github.com/Danteoriginal/bnetd/blob/master/bnetd/bnetd-0.4.27.2/src/compat/memcpy.c

**Comment by xboi209** [comment]
@Danteoriginal 
What is this for?

**Comment by Danteoriginal** [comment]
also handles some of the bits, I thought that might interest them

**Comment by xboi209** [comment]
@Danteoriginal 
It's only for compatibility purposes, in case a compiler doesn't have an implementation of memcpy for some reason. It's safe to assume that any decent compiler will have memcpy implemented.

**Comment by Danteoriginal** [comment]
/* then nuke duplicate players after the real players */
	for (i=realcount; i<game->count; i++)
	{
	    game->players[i]       = NULL;
	    game->results[i]       = game_result_none;
	    game->report_heads[i]  = NULL;
	    game->report_bodies[i] = NULL;
	}
	
	if (realcount<1)
	{
	    eventlog(eventlog_level_info,"game_report","ignoring game");
	    return -1;
	}
    }
    
    eventlog(eventlog_level_debug,"game_report","realcount=%d count=%u winners=%u losers=%u",realcount,game->count,winners,losers);

#ifndef GAMEI_SERVER
    if ( game_get_type(game)!=game_type_ladder &&
         prefs_get_stats_all_ladder() && winners==1 && losers>=1 && 
         game_get_type(game)>=game_type_topvbot && game_get_type(game)<=game_type_oneonone )
    {
        fake_ladder = 1;
        eventlog(eventlog_level_debug,"game_report","fake ladder activated due to suitable game results");
    }
    else 
        fake_ladder = 0;
#else
    if ( game_get_type(game)!=game_type_ladder &&
         game_get_type(game)>=game_type_topvbot && game_get_type(game)<=game_type_oneonone &&
	 losers > 0 )
    {
        fake_ladder = 1;
        eventlog(eventlog_level_debug,"game_report","fake ladder activated due to suitable game results");
    }
    else 
        fake_ladder = 0;
#endif
    if (realcount>=1 && !game->bad)
	if (game_get_type(game)==game_type_ladder ||
	    game_get_type(game)==game_type_ironman ||
	    fake_ladder)
	{
	    t_ladder_id id;
"some things that caught my attention"

**Comment by xboi209** [comment]
@Danteoriginal 
I don't see anything here of interest for this discussion.

**Comment by xboi209** [comment]
The most obvious leaks remaining are related to icons and attributes. It's too difficult for me to fix these leaks because they're in lists which makes things a little more complex.

**Comment by xboi209** [comment]
File ````bnetd/attrgroup.cpp````
Function ````int attrgroup_set_attr(t_attrgroup *attrgroup, const char *key, const char *val, bool set_dirty)````
Code ````attr = attr_create(newkey, val);````

Lots of memory leaks when starting PvPGN and creating new accounts. The more accounts that PvPGN needs to load, the more memory that leaks due to this function.

**Comment by Kelwing** [comment]
The problem is not within this function itself.  It is supposed to allocate memory and store it off in a list.  The question is, why is it not being freed, and where should it be freed?
