### ISSUE TITLE
Error login PVPGN

### ISSUE THREAD

**Issue by slipknotivo** [pvpgn/pvpgn-server#153]
Apr 09 15:40:24 [debug] pvpgn::bnetd::ipbanlist_check: lastcheck: 1428604803, now: 1428604824, now-lc: 21.
Apr 09 15:40:24 [debug] pvpgn::bnetd::ipbanlist_check: checking 189.250.143.106
Apr 09 15:40:24 [info ] pvpgn::bnetd::sd_accept: [404] accepted connection from 189.250.143.106:49669 on 0.0.0.0:6112
Apr 09 15:40:24 [info ] pvpgn::bnetd::conn_create: [404][392] sessionkey=0x5526c7c6 sessionnum=0x00000001
Apr 09 15:40:24 [debug] pvpgn::bnetd::sd_accept: [404] client connected to a bnet listening address
Apr 09 15:41:09 [debug] pvpgn::bnetd::sd_tcpinput: [404] read returned -1 (closing connection)
Apr 09 15:41:09 [trace] pvpgn::bnetd::conn_shutdown: [404] connection allready closed
Apr 09 15:41:09 [info ] pvpgn::bnetd::conn_destroy: [404] closed init connection
Apr 09 15:41:24 [debug] pvpgn::bnetd::guiOnClose: GUI wants server dead...

**Comment by xboi209** [comment]
How can we reproduce this?
