### ISSUE TITLE
should be an error on flags?

### ISSUE THREAD

**Issue by lord-bagheera** [pvpgn/pvpgn-server#156]
Hello Harpy, i'll have 1.99.7-PRO run on debian with mysql. 

Using a normal 1.13c client of Diablo II and connecting to my realm (already work d2[cs|dbs|gs] without any problem) all clients connecting have the icon of open-character not the image of their characters
except in case of admins/operators. 

i'll test the flag commands as admin and seems work as expected except to set to the regular character icon, activating /flag to a cg 1 to test and i'll get same results.

**Comment by HarpyWar** [comment]
http://forums.harpywar.com/viewtopic.php?pid=7546
Custom icons should be ignored for `D2XP` and `D2DV` in code even if enabled in the config.

**Comment by RElesgoe** [comment]
#292
