### ISSUE TITLE
Any news about update?

### ISSUE THREAD

**Issue by anonprophet** [pvpgn/pvpgn-server#157]
can i use pvpgn pro for production server now?

**Comment by xboi209** [comment]
No, the current commit still has many memory leaks.

**Comment by anonprophet** [comment]
so you reccomend me use pvpgn 1.99.r577 ?

if someday pvpgn pro stable, can i upgrade to this ?

**Comment by xboi209** [comment]
1.99.r577 works well. If you want some of the features from PvPGN PRO, I recommend that you use an older commit that doesn't leak a lot of memory.

**Comment by cakobox** [comment]
which commit do you refer to (that doesn't leak a lot of memory) ?

**Comment by xboi209** [comment]
I don't know, you'll have to test commits yourself

**Comment by xboi209** [comment]
Pull request #172 should prevent recurring memory leaks.
