### ISSUE TITLE
Не могут подключится игроки к игре

### ISSUE THREAD

**Issue by Artyom91** [pvpgn/pvpgn-server#158]
Здравствуйте, второй раз уже ставлю сервер и сталкиваюсь всё с той же ошибкой, я создал игру, Всё ок, меня видно, но игроки не могут войти, просто даже сообщений никаких не вылазиет, просто ожидание...

**Comment by HarpyWar** [comment]
Скорее всего, у тебя закрыт порт 6112 извне (например, на роутере или фаерволлом на компе), поэтому другие игроки и не могут подключиться.
http://harpywar.com/?a=articles&b=1&c=0&d=19
http://harpywar.com/?a=articles&b=1&c=0&d=27

Для устранения этой проблемы, а так же для равномерного пинга у всех игроков, запускают хост-ботов (для Warcraft 3).
