### ISSUE TITLE
Maybe Memory Leak

### ISSUE THREAD

**Issue by DingGGu** [pvpgn/pvpgn-server#166]
![2015-08-16_010210](https://cloud.githubusercontent.com/assets/2981443/9289628/8c1504e6-43b2-11e5-8f40-9bbe12814cd0.jpg)

Maybe PvPGN has memory leak.
but we can't find what it cause of memory leaks.

we used custom pvpgn with 6000~7000 real time connections.

**Comment by xboi209** [comment]
My latest pull request #164 should reduce the amount of memory leaks, you should look into trying to apply my changes to your PvPGN.

**Comment by DingGGu** [comment]
Thanks, i will be apply that patches.

**Comment by xboi209** [comment]
Use #172 to avoid recurring memory leaks. Please tell me your results

**Comment by DingGGu** [comment]
wip

**Comment by RElesgoe** [comment]
Any updates on this?

**Comment by itsurea** [comment]
@RElesgoe 
I checked about the memory leak.
Pvpgn custom caused it itself.
I fixed it with valgrind.

thx relesgoe
