### ISSUE TITLE
How to Create Custom PvPGN Login

### ISSUE THREAD

**Issue by anonprophet** [pvpgn/pvpgn-server#168]
![wc3scrnshot_082015_234633_01](https://cloud.githubusercontent.com/assets/8217350/9392274/fd290104-47a5-11e5-81b3-5492cede756a.jpg)

how to make like that? have tutorial?

**Comment by cen1** [comment]
Pretty sure this has nothing to do with pvpgn. This is probably just a custom W3 theme mod.

**Comment by xboi209** [comment]
````icons-WAR3.bni```` should be modified.

**Comment by anonprophet** [comment]
@cen1 im not downloading a custom theme

if u login to pvpgn server IP : free.indogamers.us

u will see it, its from they server

**Comment by anonprophet** [comment]
@xboi209 do u know what the file name in icons-WAR3.bni i must edit?

or someone know what tools to use this and tutorial
