### ISSUE TITLE
Update Minimum Requirements

### ISSUE THREAD

**Issue by xboi209** [pvpgn/pvpgn-server#170]
CMake 3.1.0
Visual Studio 2012
G++ 4.8
Windows Vista+

**Comment by xboi209** [comment]
I'd like to update the minimum requirements to Visual Studio 2015/G++ 5 because they offer a more complete C++11 support but the drawback is that these compilers are too new so people may likely not have them yet or not willing to upgrade yet.

**Comment by xkpx64** [comment]
How can i compile with 5.2 gcc version?

**Comment by xboi209** [comment]
Add the C++11 flag

**Comment by xkpx64** [comment]
At CMakeLists.txt in 51 line 
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -pedantic -Wno-variadic-macros")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pedantic -Wno-variadic-macros")
Which is correct 14 or 11 and is this the correct file to edit?

**Comment by xboi209** [comment]
Either add the -Wno-narrowing flag or explicitly cast each of those values to a char

**Comment by xkpx64** [comment]
Thanks compiled!


/home/xd2/pvpgn/src/bnetd/i18n.cpp:473:1130: warning: overflow in implicit constant conversion [-Woverflow]
 51 }, { 0xB9, 0x2116 }, { 0xBA, 0x0454 }, { 0xBB, 0x00BB }, { 0xBC, 0x0458 }, { 0xBD, 0x0405 }, { 0xBE, 0x0455 }, { 0xBF, 0x0457 } };
                                                                                                                                    ^
/home/xd2/pvpgn/src/bnetd/i18n.cpp:473:1130: warning: overflow in implicit constant conversion [-Woverflow]

**Comment by xboi209** [comment]
Any objections to setting the minimum requirements for compiling PvPGN to Visual Studio 2015/G++5.2?

**Comment by HarpyWar** [comment]
I think it would be justified if most of the code will be rewritten using all C++ 11 features. For now it's better to save a compatibility at least since Visual Studio 2012.

**Comment by xboi209** [comment]
Well it wouldn't make sense to rewrite the code to use whatever Visual Studio 2012 supports and then go back and rewrite the code again to take advantage of the improvements in Visual Studio 2015

**Comment by HarpyWar** [comment]
What are the minimum requirements for programs compiled with VS2015?

**Comment by xboi209** [comment]
What do you mean?

**Comment by HarpyWar** [comment]
I mean can it be run on Windows XP for example.

**Comment by xboi209** [comment]
Yes, Visual Studio 2015 has an option to compile for Windows XP support.

**Comment by HarpyWar** [comment]
What's about G++ 5.2, which are minimal requirements for Linux core version?

**Comment by xboi209** [comment]
I'm not sure, that might be a hard question to answer. it's safe to say that as long as the OS supports G++5, it will be able to run the program.

**Comment by HarpyWar** [comment]
Ok, I rely onto your competence in this issue and agree to apply C++11 features if it will bring any advantages. This will not a problem if PvPGN will not run on old devices like routers.

**Comment by xboi209** [comment]
G++ minimum requirement will be 5.1
