### ISSUE TITLE
error in compile

### ISSUE THREAD

**Issue by Danteoriginal** [pvpgn/pvpgn-server#174]
hello harpywar

error in compile

![error](https://cloud.githubusercontent.com/assets/7907499/10261133/6e46f6c4-694e-11e5-9772-f12d5154d64f.png)

**Comment by HarpyWar** [comment]
Need more info from you to locate the problem https://github.com/pvpgn/pvpgn-magic-builder/wiki/Diagnosis-of-problems

**Comment by cen1** [comment]
Basically it can't find any compiler. Try to add your vs compiler into PATH.

**Comment by xboi209** [comment]
We need the full logs, there may be other errors
