### ISSUE TITLE
IRC working way

### ISSUE THREAD

**Issue by Grief-Code** [pvpgn/pvpgn-server#175]
- What is the actual integration of IRC into the PVPGN and how does it work?
- Can the PVPGN being an IRC server?
- Or can it only recieve IRC clients?
- Does it return the available channels?

**Comment by HarpyWar** [comment]
There is only a part of all supported IRC commands are implemented in PvPGN. IRC server is optional and it can be enabled in bnetd.conf.
WWOL games are working through IRC commands, but it was not finished to fully support all WWOL games features. 

So yes, it can be a simple IRC server and it can return available channels using command `/list`.

[Usage example with mIRC](http://translate.google.com/translate?hl=en&sl=ru&u=http%3A%2F%2Fharpywar.com/%3Fa%3Darticles%26b%3D1%26d%3D54&langpair=ru%7Cen&hl=en&ie=UTF8)

**Comment by anonprophet** [comment]
im use IRC as BOT, bcoz its more easy for me to create simple logic script

im using node-irc using javascript
https://github.com/martynsmith/node-irc

**Comment by Grief-Code** [comment]
The issue on IRC is that you need to provide a watcher.
I dont want to have clients connecting and administrating my rooms, since first user is the OP. Its probably a case i dislike.
I thought about an IRC gateway for PVPGN to OHConnect in order to share isntances, messages and actions from pvpgn to ohconnect and the other way around. But it seems that a simple websocket integration will make it a bit better :P

**Comment by HarpyWar** [comment]
General purpose of PvPGN is Battle.net server. If this functionality will not be used then PvPGN may be not a good choice.

**Comment by harleckinz** [comment]
hey @anonprophet! have you ever tried to connect with Matterbridge? I trying to make a discord-pvpgn bridge.
