### ISSUE TITLE
won't run Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by m241dan** [pvpgn/pvpgn-server#176]
I've got it compiled and installed but when I try to run bnetd, d2cs or d2dbs they don't work.

The error message I get when running in gdb is "Inferior 1 (process pid) exited normally"

64-bit issue? I'm stumped.

**Comment by xboi209** [comment]
Can you try using commit cac1d19a11efdce906192392c47f818dfe26ff26

**Comment by m241dan** [comment]
reverted that commit, made clean, still same thing.

**Comment by xboi209** [comment]
Try 98f7165e211ccf0868ee8b223d4f2c16f1a86442

**Comment by m241dan** [comment]
Same thing :( still not running and giving "Inferior 1" when run in GDB.

**Comment by xboi209** [comment]
Try this repository: https://github.com/xboi209/pvpgn

**Comment by m241dan** [comment]
"pvpgn-server/src/common/scoped_ptr.h:42:38: error: expected ‘)’ before ‘<’ token
   explicit scoped_ptr(std::unique_ptr<V>& aptr)
"

Won't make

**Comment by xboi209** [comment]
Are you sure you replaced **all** the files? The *std=c++11* flag should be passed to the compiler which is automatically done for G++

**Comment by m241dan** [comment]
hmmm, using g++-5.1, that could be the issue maybe?

**Comment by xboi209** [comment]
It isn't, try deleting and redownloading the files

**Comment by m241dan** [comment]
ok

**Comment by m241dan** [comment]
yup, just an idiot, compiled fine. It still just stops. You run it, and it gives no error. It's not listed under processes. If I run it in GDB it just says Inferior 1(which is the bnetd) exited normally.

**Comment by xboi209** [comment]
That's weird, two other people were able to run PvPGN on Ubuntu 14.04 recently (#173). I'm not sure what your problem is.

**Comment by m241dan** [comment]
No idea, I'll install it on my vps that is also 14.04 and see what happens.

**Comment by xboi209** [comment]
Try passing the *--debug* argument to PvPGN

**Comment by m241dan** [comment]
Permissions. --debug flag, good to know!

**Comment by xboi209** [comment]
So can you run PvPGN now?

**Comment by m241dan** [comment]
With your fork, I haven't tried with this one. But, I imagine it's the same thing. It complains of permissions issues of the .conf files.

**Comment by xboi209** [comment]
I just merged my fork with this repository, it shouldn't matter anymore.
Have you tried using sudo to run PvPGN?

**Comment by m241dan** [comment]
Yah, it works with sudo. But, it's not exactly my favorite idea.

**Comment by xboi209** [comment]
I'm not sure how to solve the problem if you won't use sudo.

**Comment by m241dan** [comment]
For now, its fine.
