### ISSUE TITLE
Ipscan not filtering correctly.

### ISSUE THREAD

**Issue by serpi90** [pvpgn/pvpgn-server#179]
As far as i remember, doing an _/ipscan_ on a server with displays a list with 25% of the users in the server.

The command implementation currently fetches the string representation of the ip address and then compares all the other connections ip adresses (String) for a match.

The problem is that `addr_num_to_ip_str`, uses static vars, and `_handle_ipscan_command` does not seem to be aware of this, because it stores the pointer to that static var, which will change during the scan.

Possible Solutions:
- Copy the result of `addr_num_to_ip_str` instead of just storing the pointer. or
- Compare the adressess as numbers instead as of using strcmp, should be faster, and would solve the problem.

Sorry no code or merge request, i don't have an available developing environment here.

**Comment by RElesgoe** [comment]
3b46205114ae6be51aeaaa80feb96ca0ebb4c197
