### ISSUE TITLE
Wrong data

### ISSUE THREAD

**Issue by Neubivljiv** [pvpgn/pvpgn-server#182]
I am using PvPGN 1.9.9.7-PRO on Ubuntu Server 14.04 x64 and every command I tested as admin shows wrong data. 
![wrong_data](https://cloud.githubusercontent.com/assets/339178/10670081/2502920c-78e4-11e5-9d95-960ee6dfa03e.jpg)
Tried to use some admin command (/rehash, /ipscan etc..) but I get message:
This command is reserved for admins
When I type /admins I can see my name as logged administrator. 
Also, /finger command shows wrong data: Created (shows current date instead of date when user created account). Country is wrong etc. 
News also shows wrong date (it's 10 february 2016), but date in news.txt is different.

**Comment by anonprophet** [comment]
u need change ur Command Groups in Database to 255

**Comment by xboi209** [comment]
Post all of your account attributes.

I forgot exactly how the country is determined but I think it's based on either the game client's language or your operating system's language.

**Comment by Neubivljiv** [comment]
Here is the data from the database
![pvpgn](https://cloud.githubusercontent.com/assets/339178/10676904/820c71a0-7909-11e5-9093-0c43f331b7e1.jpg)
Seems that auth_command_groups is 1 instead of 255.

**Comment by Neubivljiv** [comment]
And what about date? It's a bit annoying :) 
![untitled-2](https://cloud.githubusercontent.com/assets/339178/10677400/6e5eaa30-790c-11e5-82d8-9f7764a8bd07.jpg)
Date in news.txt is: {10/10/2015}

**Comment by xboi209** [comment]
Can you paste or upload your news.txt file somewhere? I tried replicating the date problem but it works fine for me.

**Comment by Neubivljiv** [comment]
It's just simple dummy text for testing:
> {10/10/2015}
> 
> Welcome to GamersHost Realm. 
> 
> Enjoy!

**Comment by xboi209** [comment]
I can't replicate the issue with that. Maybe try deleting the bncache.dat file in your WC3 folder

**Comment by Neubivljiv** [comment]
Yes, that was it. 
When I deleted bncache.dat it's all fine.

**Comment by anonprophet** [comment]
u can give auth_command_groups to grief-code without restart the server,  and maybe `/save` command work too like restart
using `/cg add grief-code 12345678`

**Comment by Neubivljiv** [comment]
Then the registration through the web loses its meaning. 
May only use bot for this, which will read data from the database and update the required information.

**Comment by anonprophet** [comment]
i will use IRC to executed command like `/addacct` `/setpass` every 10 seconds retrieve data from database.

for me IRC send 10 message to pvpgn in 1s no problem

**Comment by Neubivljiv** [comment]
It is also a good solution. I'll probably use the bot for this (we do not need flood/spam ).
Also, I just made a simple web interface for PVPGN:
![psgm](https://cloud.githubusercontent.com/assets/339178/10710658/f0179048-7a63-11e5-9e17-3cbccf231d47.jpg)

![psgm_options](https://cloud.githubusercontent.com/assets/339178/10710660/f6a00b52-7a63-11e5-99fa-8257c1b275fc.jpg)
I think it looks a bit clearer.
