### ISSUE TITLE
Не могут подключится к хосту в пользовательских играх

### ISSUE THREAD

**Issue by Artyom91** [pvpgn/pvpgn-server#188]
Здравствуйте, уже пробовал давно поставить pvpgn и ошибка одна и та же, не могут подключится например ко мне, если я создал игру в пользовательских играх. Так же и наоборот, я не могу к кому либо. Пишет игра не найдена, или не правильно указано название, ну стандартная фраза, ниже лог.

Вот я уже создавал такой вопрос: https://github.com/pvpgn/pvpgn-server/issues/158

Nov 07 05:30:02 [trace] _client_motdw3: lastnews() 1396087566 news_time 1096625167
Nov 07 05:30:05 [debug] _client_gamelistreq: GAMELISTREPLY looking for public games tag="W3XP" bngtype=0x0000e000 gtype=all
Nov 07 05:30:05 [debug] _client_gamelistreq: [18] GAMELISTREPLY sent 0 of 0 games
Nov 07 05:30:14 [info ] handle_bnet: Told Mutual Friends your in game ggg
Nov 07 05:30:14 [debug] _client_startgame4: [19] got startgame4 status for game "ggg" is 0x00000010 (gametype=0x2001 option=0x0045, flag=0x0000)
Nov 07 05:30:14 [info ] game_create: game "ggg" (pass "") type 1(UNKNOWN) startver 4 created
Nov 07 05:30:22 [debug] _client_gamelistreq: GAMELISTREPLY looking for public games tag="W3XP" bngtype=0x0000e000 gtype=all
Nov 07 05:30:22 [debug] _glist_cb: [18] considering listing game="ggg", pass="" clienttag="W3XP" gtype=1
Nov 07 05:30:22 [debug] trans_net: checking 46.229.140.200:6112 for client 77.35.58.241 ...
Nov 07 05:30:22 [debug] trans_net: no match found for 46.229.140.200:6112 (not translated)
Nov 07 05:30:22 [debug] _client_gamelistreq: [18] GAMELISTREPLY sent 1 of 1 games
Nov 07 05:30:30 [debug] _client_gamelistreq: GAMELISTREPLY looking for public games tag="W3XP" bngtype=0x0000e000 gtype=all
Nov 07 05:30:30 [debug] _glist_cb: [18] considering listing game="ggg", pass="" clienttag="W3XP" gtype=1
Nov 07 05:30:30 [debug] trans_net: checking 46.229.140.200:6112 for client 77.35.58.241 ...
Nov 07 05:30:30 [debug] trans_net: no match found for 46.229.140.200:6112 (not translated)
Nov 07 05:30:30 [debug] _client_gamelistreq: [18] GAMELISTREPLY sent 1 of 1 games
Nov 07 05:30:38 [debug] _client_gamelistreq: GAMELISTREPLY looking for public games tag="W3XP" bngtype=0x0000e000 gtype=all
Nov 07 05:30:38 [debug] _glist_cb: [18] considering listing game="ggg", pass="" clienttag="W3XP" gtype=1
Nov 07 05:30:38 [debug] trans_net: checking 46.229.140.200:6112 for client 77.35.58.241 ...
Nov 07 05:30:38 [debug] trans_net: no match found for 46.229.140.200:6112 (not translated)
Nov 07 05:30:38 [debug] _client_gamelistreq: [18] GAMELISTREPLY sent 1 of 1 games
Nov 07 05:30:46 [debug] _client_gamelistreq: GAMELISTREPLY looking for public games tag="W3XP" bngtype=0x0000e000 gtype=all
Nov 07 05:30:46 [debug] _glist_cb: [18] considering listing game="ggg", pass="" clienttag="W3XP" gtype=1
Nov 07 05:30:46 [debug] trans_net: checking 46.229.140.200:6112 for client 77.35.58.241 ...
Nov 07 05:30:46 [debug] trans_net: no match found for 46.229.140.200:6112 (not translated)
Nov 07 05:30:46 [debug] _client_gamelistreq: [18] GAMELISTREPLY sent 1 of 1 games

**Comment by HarpyWar** [comment]
Все описано в предыдущем вопросе.
Это проблема не сервера, а клиентов-игроков, т.к. после создания игры PvPGN не учавствует в подключении, а лишь передает IP адрес компьютера игрока-хоста другому игроку-клиенту, когда второй получает список игр. 
Если игрок-клиент не может соединиться на IP адрес игрока-хоста через порт (обычно 6112, если не изменен вручную), то у него появляется ошибка подключения.

**Comment by Artyom91** [comment]
@HarpyWar Если мне сейчас например на Рубатле проверить с тем же игроком и всё получится, значит что-то с pvpgn, верно?

**Comment by Artyom91** [comment]
@HarpyWar Сейчас уже идем проверять, еще один вопрос на засыпку.

Я использую еще хост боты Ohsystem, не знаю английский, долго переводить, вы там решили вопрос с интеграцией pvpgn?

**Comment by HarpyWar** [comment]
Соединение не будет происходить если PvPGN запускается у себя на компе, и на нем же создается игра (т.к. PvPGN уже использует порт 6112).

Интеграция на стороне бота ещё не делалась https://github.com/OHSystem/OHSystem/issues/404#issuecomment-146507163

**Comment by Artyom91** [comment]
@HarpyWar Я знаю, я pvpgn временно на VDS поднял. На рубатле тоже не можем войти к друг другу, скорей всего так и есть, ладно, спасибо, поднимем ботов )
