### ISSUE TITLE
Не проходит spoof проверка на боте через ваш pvpgn

### ISSUE THREAD

**Issue by Artyom91** [pvpgn/pvpgn-server#189]
@HarpyWar @xboi209 И так, здравствуйте. Я уже создавал такой вопрос, но вот сейчас снова поднял pvpgn и ошибка та же https://github.com/pvpgn/pvpgn-server/issues/126 .

Объясняю, я запустил бота на котором я админ, я уже больше двух лет юзаю ботов на выделенном сервере в Москве, к тому же, у меня самый крупный портал в России по хостингу ботов, hodovoi.

Когда на бот заходит кто либо из администрации идет автоматическая проверка на spoof, на Rubattle данная функция работает в идеале, на вашем pvpgn никак не реагирует и соответственно я остаюсь без прав.

Скриншот Rubattle:
![2015-11-07_223049](https://cloud.githubusercontent.com/assets/6318282/11015197/7c6a9648-85a0-11e5-952c-46ab2044e834.png)
На скриншоте видно, как я вошел и мне отправилась команда /whereis мой ник. Затем, появилось сообщение (самое последнее) что всё в порядке.

Скриншот Pvpgn:
![2015-11-07_223435](https://cloud.githubusercontent.com/assets/6318282/11015201/c0cdbefa-85a0-11e5-8bcc-d89ca14dff86.png)
На скриншоте видно, что никаких подобных манипуляций не проводится и я остаюсь со статусом non-spoofchecked.

Пожалуйста, исправьте это, без это функции не работают права на боте, она необходима как воздух.

**Comment by xboi209** [comment]
Как @cen1 изначально говорил, проблема с ботом, а не с PvPGN. Бот написан для работы с PvPGN, PvPGN не написан для работы с ботом и тем самым не должен модифицироваться для работы с конкретным ботом.
Бот проверяет строку, отправленную с сервера, которую текущая версия PvPGN модифицировала и даже перевела так, что бот не может успешно найти заданную строку.

**Comment by Artyom91** [comment]
@xboi209 Ну вот смотрите, данная проблема только с вашим pvpgn, если рассуждать вашей логикой, что PvPGN не написан для работы с ботом и не должен модифицироваться для работы с конкретным ботом, т.е, буквально все самые популярные pvpgn сервера внедряют это функцию для конкретного бота? Работает практически везде, кроме вашего.

И еще, если pvpgn не модифицируется для работы с ботом, зачем, например, Ohsystem делать модификацию для работы с pvpgn, зачем вообще запускать такую версию pvpgn если на ней боты работают не корректно, это одна из важнейших функций. Получается так, @HarpyWar призывает запускать ботов, потому что траблы с портами, а боты не могут работать, потому что pvpgn не модифицируется для ботов.

ЛАдно, не хотите исправлять это, ваше дело, буду искать другие pvpgn сборки.

**Comment by xboi209** [comment]
PvPGN не должен ограничиваться конкретной строкой, он должен быть в состоянии отправлять любую строку, которая ему потребуется. Это вы решите, либо вы модифицируете исходный код PvPGN, либо OHSystem, так как это специфично для ваших нужд.

**Comment by Artyom91** [comment]
@xboi209 Печально, что вы так считаете. Извините, но вы не правы.

**Comment by HarpyWar** [comment]
@Artyom91 Интеграция OHSystem с PvPGN реализована в рамках Lua. Мое видение этого состояло в том, чтобы предоставить удобную возможность модификации сервера без редактирования исходного кода C++.

Я отошел от поддержки PvPGN, и не до конца понимаю в чем проблема. Правильно ли я понимаю, что задача состоит в том, чтобы выдача команды `/whois` соответствовала боту? Если так, то эту команду можно переопределить через Lua - чтобы она выдавала нужную строку. Пример переопределения команды `/stats` есть в папке со скриптами.

**Comment by stas730** [comment]
Вы и на русском языке говорите?
