### ISSUE TITLE
fix rehash

### ISSUE THREAD

**Issue by Danteoriginal** [pvpgn/pvpgn-server#190]
fix
 when used rehash, returning to the original code

https://github.com/Danteoriginal/pvpgn-server/commit/e7420a23bef89b220941f248b93de4ab285cdd26

**Comment by xboi209** [comment]
There's no difference except that ````IDM_RESTART_LUA```` is ignored. It doesn't seem that there's anything wrong with the ````guiOnCommand()```` function.

**Comment by Danteoriginal** [comment]
xboi209 server restarts several times and like the third time you reboot the server goes down

**Comment by xboi209** [comment]
Your commit doesn't fix that crash at all, the function is unrelated. Created a new issue #191
