### ISSUE TITLE
Started games appeared in the gamelist

### ISSUE THREAD

**Issue by Neubivljiv** [pvpgn/pvpgn-server#192]
Games hosted via ghost++ bot (modified) that already started shows on the gamelist on PVPGN, so users got message "unable to find game or something". Games "hangs" on the list for few hours (PVPGN server didn't clean up games that already started). 
Whether someone familiar with this problem?

**Comment by xboi209** [comment]
Do you have a server log that you can submit? I don't feel like testing this myself

**Comment by anonprophet** [comment]
do u want to try host ghost++ on my server ?

**Comment by Neubivljiv** [comment]
Well log file is huge and not sure what I need to look. I just see some logs like:
> Nov 15 14:38:09 [debug] game_del_player: game "-OHS- DotA -apem #47102" has ref=1, count=1; trying to remove player "OHS07"
> Nov 15 14:38:09 [debug] game_del_player: removing player #0 "OHS07" from "-OHS- DotA -apem #47102", 0 players left
> Nov 15 14:38:09 [debug] game_del_player: player "OHS07" left without reporting (valid) results
> Nov 15 14:38:09 [info ] conn_destroy: [29] "OHS07" logged out

Seems that bot disconnect sometimes and reconnect. After reconnect:
> Nov 15 14:39:39 [info ] conn_set_channel: [29] joined channel "clan ohs"
> Nov 15 14:39:39 [debug] get: returning nullptr

> Nov 15 14:39:44 [debug] _client_startgame4: [19] got startgame4 status for game "-OHS- LoD #47098" is 0x00000010 (gametype=0x2003 option=0x0043, flag=0x0000)
> Nov 15 14:39:45 [info ] handle_bnet: Told Mutual Friends your in game -OHS- DotA -apem #47103
> Nov 15 14:39:45 [debug] _client_startgame4: [29] got startgame4 status for game "-OHS- DotA -apem #47103" is 0x00000010 (gametype=0x0003 option=0xffff, flag=0x0000)

**Comment by xboi209** [comment]
Full logs are appreciated

**Comment by Neubivljiv** [comment]
Uploaded on our cloud. 
Here is the log (not that this file is ~300MB):
https://replays.gamers.host/resources/bnetd.log
