### ISSUE TITLE
Question: Checksum / Hashes?

### ISSUE THREAD

**Issue by CanadianJeff** [pvpgn/pvpgn-server#194]
I just want to know if there is a way to verify CRC32, MD5, SHA1 files for various games?

this is what I have for Patched Version 2.02 (USA) Warcraft II BNE

```
root@xubuntu:/home/jefferyw/.wine/drive_c/Program Files (x86)/Warcraft II BNE# sha1sum *.mpq
76cf76672a7af8b8b93d5e386ad208fa7ba2cf66  War2Dat.mpq
3e786d6fd16b538b5b45ab971b6612970bd7ed6c  War2Patch.mpq
root@xubuntu:/home/jefferyw/.wine/drive_c/Program Files (x86)/Warcraft II BNE# sha1sum *.dll
d85bc8a2aec0eafa35f59baa1cc9293661c7b618  Smackw32.dll
a8d7f56fd81976e98e7dadf0efae4625f6749b84  storm.dll
e1f1485fcf3a35b23dc3d226521d2510ce693f5c  W2Local.dll
root@xubuntu:/home/jefferyw/.wine/drive_c/Program Files (x86)/Warcraft II BNE# sha1sum *.exe
df28b0cbbd2645d95df18790b997f8965df7dd6c  BNUpdate.exe
acfa1ad7ec34dfdf6ec326a77a4dd9c685616b26  Warcraft II BNE.exe
e4423464c978874dae5e43338d33e69dc58e48ac  Warcraft II Map Editor.exe
```

**Comment by xboi209** [comment]
You'll have to write your own DLL, pack it inside a MPQ, sign it, and send it to the client via [CheckRevision](https://github.com/pvpgn/pvpgn-server/issues/112) or [ExtraWork](https://github.com/pvpgn/pvpgn-server/issues/72)

**Comment by CanadianJeff** [comment]
sorry I wanted to know if the hashes that I have are correct

**Comment by xboi209** [comment]
This question isn't appropriate for this project then. If you want to know, just download a fresh set of files from Blizzard and compare the hashes to your installation.

**Comment by CanadianJeff** [comment]
how do I download fresh files from blizzard? I got these from a burnt CD that I bought at a thrift store

**Comment by xboi209** [comment]
Well firstly, you would need a legitimate cd-key which I assume you don't have so you're out of luck.

**Comment by CanadianJeff** [comment]
I have a legit cd-key this game is too old to download from the blizzard website

**Comment by xboi209** [comment]
Well I'm sorry but you'll have to ask someone else for the hashes.

**Comment by CanadianJeff** [comment]
do you not have the hashes or unwilling to reveal the hashes

**Comment by xboi209** [comment]
I don't have the hashes.

**Comment by CanadianJeff** [comment]
I wish I kept my original CD but I threw it out years ago and now I wanted to play again all I can find are expensive copies sold online or cheapo cd burnt copies at thrift shops

**Comment by CanadianJeff** [comment]
ok posted my question on legacy battle net forums

http://us.battle.net/en/forum/topic/20044776757
