### ISSUE TITLE
cant compile with lua

### ISSUE THREAD

**Issue by kojekteabro** [pvpgn/pvpgn-server#195]
im tryin to running pvpgn 1.99-pro on centos 6.

but stuck with bellow error ..

CMake Error at cmake/Modules/FindLua.cmake:65 (MESSAGE):
  Could not find Lua5.1
Call Stack (most recent call first):
  ConfigureChecks.cmake:48 (find_package)
  CMakeLists.txt:25 (include)

i guess it cant find lua libdir or something , here is where lua location .

[root@localhost build]# which lua
/usr/bin/lua

if i compile without lua everything is fine.
am i miss of something, or can i modified anything to make this compile with lua ?

**Comment by HarpyWar** [comment]
You have to install not only the runtime (lua5.1) but also the development packages (liblua5.1-0-dev). 

Try
```
yum install lua-devel
or
yum install compat-lua-devel-5.1.5
```
I'm not sure about package name in CentOS, but Lua version must be 5.1.x (not 5.2.x or 5.3.x).

**Comment by kojekteabro** [comment]
it pass cmake -D CMAKE_INSTALL_PREFIX=/usr/local/pvpgn -D WITH_MYSQL=true -D WITH_LUA=true ../

but now its failed when tryin to make ,...

/home/pvpgn-server/src/bnetd/luawrapper.h:102:43: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
   void find(const char* name, int index = LUA_GLOBALSINDEX) throw() { lua_getfield(st, index, name); }
                                           ^
/home/pvpgn-server/src/bnetd/luawrapper.h: In constructor ‘lua::table::table(lua::vm&)’:
/home/pvpgn-server/src/bnetd/luawrapper.h:258:55: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
   explicit table(vm& _vm) :stack(_vm.get_st()), index(LUA_GLOBALSINDEX) {}
                                                       ^
/home/pvpgn-server/src/bnetd/luawrapper.h: In constructor ‘lua::bind::bind(lua::vm&)’:
/home/pvpgn-server/src/bnetd/luawrapper.h:299:14: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
    cur_index(LUA_GLOBALSINDEX), mutex(_vm.mutex)

**Comment by kojekteabro** [comment]
everything is find i changed it to ubuntu 15.10 ,..
