### ISSUE TITLE
Lua quiz not running

### ISSUE THREAD

**Issue by kojekteabro** [pvpgn/pvpgn-server#196]
yesterday quiz runing well ,..

but this morning when i check , no quiz running on chat , i try to stop , and start again but give nothing response but bellow is log from server ...

Mar 05 09:06:34 [error] lua_handle_command: /home/pvpgn/var/pvpgn/lua/quiz/quiz.                                                                              lua:120: attempt to compare string with number
Mar 05 09:06:34 [debug] handle_command: got unknown command "/quiz stop"
Mar 05 09:06:44 [error] lua_handle_command: /home/pvpgn/var/pvpgn/lua/quiz/quiz.                                                                              lua:120: attempt to compare string with number
Mar 05 09:06:44 [debug] handle_command: got unknown command "/quiz stop"

**Comment by kojekteabro** [comment]
its running again , after /rehash lua

**Comment by HarpyWar** [comment]
Edit line 120 in [quiz.lua](https://github.com/pvpgn/pvpgn-server/blob/master/lua/quiz/quiz.lua#L120) from 
```
if q_records_diff[tusername] < 0 then
```
to
```
if tonumber(q_records_diff[tusername]) < 0 then
```
Let me know if the error appears after that.
