### ISSUE TITLE
User Notification Message

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#2]
http://developer.berlios.de/bugs/?func=detailbug&bug_id=15327&group_id=2291
watch.cpp line 184
message_send_text(dest_c, message_type_whisper, NULL, msg); --> message_send_text(dest_c, message_type_whisper, my_c, msg);

**Comment by kryshtof** [comment]
It seems both previous and current approach disrupts your conversation (using /r) because when anyone on your friend list joins/leaves game/server your reply either goes to friend who joined/leaved (current) or to server (previous, = error) instead of the person you were whispering to...
