### ISSUE TITLE
 Php Track & track.h

### ISSUE THREAD

**Issue by Cedyk** [pvpgn/pvpgn-server#200]
Hello, sorry for my horrible English, I am Argentine. I was looking about TrackPHP, although it is a dead code seems to work and that part can optimize it. But for that to work you would need to add that "track.h" file that includes the pvpgn server (attached). I wondered if they could add it to the project so work on the new version of TrackPHP then share the code. Of course, I would appreciate an answer.
[tracker.zip](https://github.com/pvpgn/pvpgn-server/files/222534/tracker.zip)

**Comment by cen1** [comment]
Can you clarify what you want to add to this project? Tracker.h or TrackPHP?

**Comment by Cedyk** [comment]
TrackPHP is a code of track.muleslow.net extracted site (I hope not be taken as spam), which are allowed to list the pvpgn servers connected to the network so that users have a list of servers by country, with their websites and other data. This code is currently dead, I would like to revive him, work on the optimize and upgrade. For that, the same code calls the accession of this file. As I understand how it works the "track" is generating a request to "x" website from time to time by sending the data you want to display.

**Comment by xboi209** [comment]
I don't understand why you want the track.h file uploaded to this repository. It seems as though it's a very old version of the file from BNETD, and PvPGN already maintains the most up-to-date version of this file. You haven't spoken about how you want this to be changed other than optimizing it, which is still vague.
