### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by XanderGS** [pvpgn/pvpgn-server#207]
Hello, any feedbacks on the stability of latest commit?

Thank you

**Comment by RElesgoe** [comment]
The latest commit is not stable, I recommend using one of the releases for building or deploying: https://github.com/pvpgn/pvpgn-server/releases

**Comment by XanderGS** [comment]
So the Nov 17, 2015  would be good to go on a production server?

Thanks for the fast answer too, much appreciated.

**Comment by RElesgoe** [comment]
Yes, the ````1.99.7.cbca36ac7dca6d1900a023de162d9b5931c1c054```` release is good.

**Comment by XanderGS** [comment]
Thank you, appreciated.

**Comment by XanderGS** [comment]
I've sent you an email if you can check it

**Comment by RElesgoe** [comment]
I didn't receive any email.

**Comment by XanderGS** [comment]
Should arrive shortly, taken from your github profile, hope you don't mind.
