### ISSUE TITLE
Help me create d2gs to 1.14b (Windows)

### ISSUE THREAD

**Issue by d2blackwolf** [pvpgn/pvpgn-server#208]
I can not create a d2gs to 1.14b version for windows.

You can create for me? Please!
I can not!

Thank you very much.

**Comment by RElesgoe** [comment]
D2GS is a separate project, ask the maintainers of D2GS.

**Comment by HarpyWar** [comment]
There is no version 1.14b for D2GS yet. The latest one can be downloaded from http://pvpgn.pro or using Magic Builder.

**Comment by d2blackwolf** [comment]
My D2GS drop after a while, and this information appears in d2gs.txt:

06/18 23:20:54.391 D2GSErrorHandle: Error occur, exiting...

I'm using D2GS version 1.13c with Patch of 1.14b

You know how to fix?

**Comment by HarpyWar** [comment]
I meant that there is no way to run 1.14b untill it will not be released by Marsgod or someone else.
