### ISSUE TITLE
versioncheck entry for Diablo 2 1.13D?

### ISSUE THREAD

**Issue by filaname** [pvpgn/pvpgn-server#209]
Diablo 2: Lord of Destruction 1.14C - Windows:

????
????
????

**Comment by psyhlo** [comment]
I want to ask the same. Is there will be versioncheck entry for Diablo 2 1.13D, as there is already for 1.14C
Or at least how can i make it by myself

BTW
Great work for the project you are gods ;)

**Comment by RElesgoe** [comment]
@psyhlo no one has submitted a D2 1.13d versioncheck entry yet. You can attempt to connect to your own server with D2 1.13d and then use the information from the server logs to create a versioncheck entry.

**Comment by psyhlo** [comment]
Thanks i'll try
