### ISSUE TITLE
How to disable Warden?

### ISSUE THREAD

**Issue by b1nn** [pvpgn/pvpgn-server#213]
I've saw that it is deprecated, so how to disable it?

There's another version of working warden?

I'm working in a new PvPgn modified server hosted in Brazil to get good ping for south and if possible north america, I'm looking to pay for someone make all the necessary configurations and modifications, please contact me

**Comment by RElesgoe** [comment]
PvPGN does not support Warden at all.

**Comment by b1nn** [comment]
While in game I'm receiving this message: "You are killed by Warden because error response.[reason=255]

**Comment by HarpyWar** [comment]
@b1nn PvPGN and D2GS are different projects https://github.com/pvpgn/pvpgn-server/issues/212#issuecomment-231573929

Warden can be disabled in d2server.ini `EnableWarden=0` https://github.com/tesseract2048/d2gs/issues/3
You can try post your job offer in Freelance section of http://forums.harpywar.com

**Comment by stas730** [comment]
Warden is available in Warcraft 3 or Starcraft at all?

**Comment by RElesgoe** [comment]
PvpGN does not support Warden in any game.
