### ISSUE TITLE
CD Key checking

### ISSUE THREAD

**Issue by stas730** [pvpgn/pvpgn-server#215]
We need to add key checking and some keys.
Example:
0.
Owner: Test CD Key
Key: ABCDE-FGHIJ-KLMNO-PQRST-UVWXY
1.
Owner: Another Test CD Key
Key: THEAN-OTHER-CDKEY-FORBN-ETSRV

**Comment by HarpyWar** [comment]
Describe use case of this.

**Comment by stas730** [comment]
We need to implement full Battle.net Classic?
0. We need full BNet
1. For me. I want to create open source Blizzard games versions.
2. For developers.
3. For testers.

**Comment by stas730** [comment]
Addition for this message: I need full Battle.net 2.0, too. But it's not PvPGN task. I will try to port it after MaNGOS implementation.
I need Warden, too. But is it exist for WarCraft or StarCraft?

**Comment by stas730** [comment]
This question, too: development is in progress or it is freezed for some time?
Maybe, I will start "freeing" games from WoW (Battle.net 2.0). I will start developing classic games after full basic functional will be implemented (Warden, CD Key checking are not implemented basic functional for now).

**Comment by cen1** [comment]
I can see an edge use case where PvPGN host would want to turn on CD key checking to allow only legitimate buyers on his/her server but as far as I know there is no way to validate CD keys at this point or ever. It's secret sauce from Blizzard which was never cracked or disclosed.
Besides that I don't understand why you need this to "start developing classic games", whatever that means. CD key checking and Warden are not essential Battle.net mechanics which are worth emulating. You can already implement some of your own Warden functionality via SID_EXTRAWORK  to read game memory etc. There is no reason for PvPGN to implement it though.

**Comment by stas730** [comment]
I think, we need to try.
Battle.net server is up now. We can buy one copy and test it? Then sniff packets and implement it.
To implement Warden, we need to do many work. We know Warden basics? We need to test checks.
I think, we CAN implement this stuff.

**Comment by stas730** [comment]
Addition to previous message:
We can implement all basic stuff using sniffing. All Battle.net games. Battle.net 2.0.
We cannot do things, that not required for me (this thing does not exists in classic games, I think. In WoW it is scripting. One quest and one quest(giver) or functions to add it are required for me for all sandboxes)

**Comment by stas730** [comment]
We can't do this things with sniffing (additional). But we can do all basic things with sniffing.

**Comment by stas730** [comment]
The hardest thing is "Blizzlike" bug porting…

**Comment by stas730** [comment]
I think, Blizzard doing this steps for register new key:
0. Some software company sending message to Blizzard. Blizzard creating "CD Key Owner" for it.
1. Company buying some games
2. Blizzard registering new keys
3. This company sells this games
I think, Blizzard contain keys in database.
——
What is Blizzard maps in Warcraft 3? Signed by Blizzard signature? Hardcoded?

**Comment by RElesgoe** [comment]
PvPGN does not have access to Blizzard's CD key database and therefore can't validate keys.

**Comment by stas730** [comment]
It is critical for me. Are there any PvPGN fork?

**Comment by RElesgoe** [comment]
It's impossible to access Blizzard's database. If you want to create your own database for PvPGN to check against, it's pointless because people can reinstall their games with different CD keys.

**Comment by stas730** [comment]
We need to add our own database disabled by default. I will enable it on my server after porting Warden. How to implement it?

**Comment by stas730** [comment]
Because I want to create my own open source Warcraft, Diablo and StarCraft. Then I will create own CD key database.

**Comment by HarpyWar** [comment]
@stas730 you need to handle a client packet [SID_AUTH_CHECK](https://redux.bnetdocs.org/?op=packet&pid=408)

**Comment by stas730** [comment]
I will try to sniff. After implementation, can I send pull request?

**Comment by RElesgoe** [comment]
The packet is already documented and implemented.

**Comment by stas730** [comment]
Ok. I will try. You will accept pull request with CD key checking? Disabled by default, of course.

**Comment by RElesgoe** [comment]
I won't accept it here, you should fork this repository instead.

**Comment by HarpyWar** [comment]
@stas730 look into the function [_client_authreq109](https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/handle_bnet.cpp#L1090-L1095).

Potentially it's dangerous and illegitimately if working CD keys will be stored on your server. Even if not, as @RElesgoe and @cen1 wrote, actually cd key checking is useless for non-blizzard servers and it should not be implemented in PvPGN. This will only add additional needless complexity for end users.
If you plan to sell cd-keys then you can just sell a new account registrations. If you want to lock cd-key then you can just lock an account.

**Comment by stas730** [comment]
No. I want to create maximum Blizzlike server. I have methods to hide and do illegal stuff. I will use my own keys because keys is stuff like account DB — it's secret. And I will create my own Battle.net and Battle.net 2.0 — with anonymity (Tor) and security (EV SSL for site, EdDSA and other).

**Comment by stas730** [comment]
Lock CD key? Server handles locked key as non-existing key? Or special response?

**Comment by HarpyWar** [comment]
You can choose in code what a server will do with locked key. Server should response to a client's packet https://redux.bnetdocs.org/?op=packet&pid=408 with the packet https://redux.bnetdocs.org/?op=packet&pid=106
Depending on the response a game client will connect to the server or show a corresponding error message.

**Comment by stas730** [comment]
All packets are sniffed? I must not buy War3 for implement key checking?

**Comment by HarpyWar** [comment]
Sure, as you can see all the Battle.net packets are documented on http://bnetdocs.org and most of them are implemented in PvPGN.

**Comment by stas730** [comment]
Most, not all? I can implement this packages using only docs?

**Comment by stas730** [comment]
Please, reply.

**Comment by RElesgoe** [comment]
Not all packets are implemented in PvPGN because some packets have been superseded by others or are unnecessary. Some packets have fields whose purpose are still unknown, but could usually still be implemented because those fields may have only a single known value.

**Comment by HarpyWar** [comment]
Several packets are deprecated or unknown, so they are useless. Or for example 0x5E SID_WARDEN can not be implemented, @RElesgoe already wrote you about this https://github.com/pvpgn/pvpgn-server/issues/216#issuecomment-234919270. 
I don't have the complete picture of this part, you can compare yourself [bnet_protocol.h](https://github.com/pvpgn/pvpgn-server/blob/master/src/common/bnet_protocol.h) with https://bnetdocs.org/packet/index

**Comment by stas730** [comment]
WoW Warden is easier than classic?

**Comment by HarpyWar** [comment]
You can compare your knowledge about WoW Warden with https://wiki.skullsecurity.org/Starcraft_Warden and decide what is easier or harder.

**Comment by stas730** [comment]
I have question: If I can develop Warden using this data, can I create GNU version without changes (using macOS version)? Or Mac version is not compatible with GNU/Linux, GNU/Hurd and GNU/kFreeBSD?
—
MD5 and RSA. LOL.
MD5 is now cracked and weak. Skein is better. RSA is weaker than DSA and maybe EC/EdDSA.

**Comment by RElesgoe** [comment]
Just write cross platform code and compile for the operating systems that you want to compile for.

**Comment by stas730** [comment]
My question is another — Mac Warden is only for Mac or for all *nix?

**Comment by RElesgoe** [comment]
I'm not aware of Warden existing for Mac at all, and Battle.net games do not support other unix-like operating systems.

**Comment by stas730** [comment]
Check WoW Warden code. It is available for Mac because WoW available for Mac.

**Comment by stas730** [comment]
Or BNet classic games does not support Mac?

**Comment by RElesgoe** [comment]
That does not mean that the classic games support a Mac Warden.
