### ISSUE TITLE
Implement Warden

### ISSUE THREAD

**Issue by stas730** [pvpgn/pvpgn-server#216]
We need to implement full Battle.net? We need to implement Warden. Please, implement.

**Comment by RElesgoe** [comment]
There is no need to implement Warden, PvPGN has multiple ways to add an antihack system(SID_READMEMORY, CheckRevision, and ExtraWork.

**Comment by stas730** [comment]
D2GS Warden is compatible with WarCraft and StarCraft? For port.

**Comment by RElesgoe** [comment]
No

**Comment by stas730** [comment]
I NEED IT. LAZY IDIOTS LIKE TRINITYCORE?

**Comment by stas730** [comment]
I will implement Warden anyway.
Required functions for me:
0. Warden
1. CD Key handling
2. Other

**Comment by HarpyWar** [comment]
Warden is not a trivial task. It may need a lot of time to research, programming and support it up to date.
If you can do it yourself or you have people resources to make it open-source - you are welcome. 

The best way to do it I think is ExtraWork https://github.com/pvpgn/pvpgn-server/issues/72
But you can implement it in your client-side launcher instead.

**Comment by stas730** [comment]
I read old news "Warden code has been leaked". I have Clientless WoW client (cloned before repo closing). In this client I have client for Warden.
I have two questions — Warden is one program or it is different for all games? We need to buy ONE copy for test Warden ban reasons (if it isn't already known) or Blizzard can "ban CD key"?

**Comment by Dramacydal** [comment]
It is different for all games and every build of that game

**Comment by stas730** [comment]
But can port Diablo Warden to StarCraft or WarCraft with some changes? What is known differencies for now?

**Comment by HarpyWar** [comment]
"Warden" is mostly not a server side feature. 
It's simply a code that executes on a client side that can search for a memory modifications or running cheat programs. So, each game must have it's own implementation.

**Comment by stas730** [comment]
Ok. How Warden works?
0. Memory checking client and sending info to server
1. Warden checking this data for "malware"
2. If cheat detected, Warden doing something with player account

**Comment by stas730** [comment]
It is right?

**Comment by HarpyWar** [comment]
Yes something like that.

**Comment by RElesgoe** [comment]
I don't think it's even possible to compile a Warden module for official clients to use since it's digitally signed, and I'm guessing it's signed with the strong digital signature (2048-bit RSA key).

**Comment by stas730** [comment]
WoW Warden is working. Classic games are older than WoW.

**Comment by stas730** [comment]
What "Closed Battle.net" means in D2GS?

**Comment by HarpyWar** [comment]
@stas730 http://harpywar.com/?a=articles&b=2&c=2&d=21
Note, you should ask the such questions on forums, but not here https://github.com/pvpgn/pvpgn-server/issues/212#issuecomment-231573929

**Comment by stas730** [comment]
@HarpyWar, Вы тоже на русском говорите?

**Comment by Kelwing** [comment]
@stas730 If you need this so bad, maybe you should implement it yourself.  This is an open source project developed entirely by volunteers.  Commenting and calling the "LAZY IDIOTS" is very oxymoronic (considering everyone is a volunteer), and won't get you anywhere.  They've given you plenty of alternatives that will get the job done.  There also simply isn't enough demand.  One person asking for one difficult to implement feature will always lose to simple features demanded by more people.  Knock it off.
