### ISSUE TITLE
Create versioncheck entry for StarCraft 1.17.0

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#217]
```
# StarCraft: Brood War 1.17.0 - (Brood War mode)
"A=2521522835 B=3428392135 C=218673704 4 A=A^S B=B-C C=C+A A=A-B" \
 "ver-ix86-1.mpq" \
 IX86 \
 SEXP \
 "StarCraft.exe 07/11/16 15:59:46 1243112" \
 0x000000d5 \
 1.17.0.1 \
 0xcb82b07c \
 SEXP_1170
```

```
# StarCraft: Brood War 1.17.0 - (StarCraft mode)
"A=2521522835 B=3428392135 C=218673704 4 A=A^S B=B-C C=C+A A=A-B" \
 "ver-ix86-1.mpq" \
 IX86 \
 STAR \
 "StarCraft.exe 07/11/16 15:59:46 1243112" \
 0x000000d5 \
 1.17.0.1 \
 0xcb82b07c \
 STAR_1170
```

```
# StarCraft (Standalone) 1.17.0
```

Starting with 1.17.0, StarCraft and StarCraft: Brood War now requires CheckRevision's .dll to be digitally signed.
[ver-IX86-#.zip](https://github.com/pvpgn/pvpgn-server/files/383299/ver-IX86-.zip)

**Comment by Aloki** [comment]
```
# Starcraft (Standalone) 1.17.0
"A=2521522835 B=3428392135 C=218673704 4 A=A^S B=B-C C=C+A A=A-B" \
 "ver-IX86-1.mpq" \
 IX86 \
 STAR \
 "StarCraft.exe 07/11/16 15:59:51 1243112" \
 0x000000d5 \
 1.17.0.0 \
 0xa5e7b4cc \
 STAR_1170

```

**Comment by xpeh-owns** [comment]
What is actually the latest version of SC pvpgn works with?

**Comment by RElesgoe** [comment]
@xpeh-owns without these versioncheck entries, 1.16.1, with the entries, 1.17.0

**Comment by xpeh-owns** [comment]
Which is the last version that uses old protocol?

**Comment by RElesgoe** [comment]
@xpeh-owns 1.17.0

**Comment by xpeh-owns** [comment]
Would you update Supported Clients in readme.md?

**Comment by RElesgoe** [comment]
@xpeh-owns The readme is updated, 1.17.0 won't work until these versioncheck entries are added to PvPGN.

**Comment by xpeh-owns** [comment]
So please add them :-P

**Comment by RElesgoe** [comment]
There's a lot of other things to take care of, this is low priority.

**Comment by xpeh-owns** [comment]
It takes 2 minutes, lol.

**Comment by RElesgoe** [comment]
You're free to make the changes and create a pull request for it.

**Comment by xpeh-owns** [comment]
This will take much more that 2 minutes as I never did this :-P

**Comment by xpeh-owns** [comment]
Is the problem just to add 2 entries to conf or something else?

**Comment by cen1** [comment]
Yes, that is all.
