### ISSUE TITLE
Update trackers

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#225]
- Remove ````track.dreaming-bg.com```` (dead)
- Add ````track.eurobattle.net````

**Comment by cen1** [comment]
track.muleslow.net and track.pvpgn.org are run by the same person and resolve to the same IP. Therefore track.muleslow.net can probably be safely removed. Current configuration probably sends duplicate tracking info to the same tracker which is not a big deal but it's redundant.
