### ISSUE TITLE
[Question] accessing account information in d2cs

### ISSUE THREAD

**Issue by d2dude** [pvpgn/pvpgn-server#236]
Hi, I'm working in handle_d2cs.cpp.  I notice in d2cs we use a const char * instead of a t_account *, so we are not able to use account_get_sex and such things.  If I want to access an account's profile information from d2cs, how do you recommend doing this?

Thank you

**Comment by RElesgoe** [comment]
````t_account * accountlist_find_account(char const * username);````
Include ````account.h````

**Comment by d2dude** [comment]
Thanks for your reply, that function is very helpful

I'm getting some linking errors that I don't fully understand when using functions from account.h. 
Please let me know if I should open a separate issue for this.
When I use the magic-maker, I get these errors:
```
handle_d2cs.obj : error LNK2019: unresolved external symbol "struct pvpgn::bnetd::account_struct * __cdecl pvpgn::bnetd::accountlist_find_account(char const *)" (?accountlist_find_account@bnetd@pvpgn@@YAPAUaccount_struct@12@PBD@Z) referenced in function "int __cdecl pvpgn::d2cs::on_client_creategamereq(struct pvpgn::d2cs::t_connection *,struct pvpgn::t_packet *)" (?on_client_creategamereq@d2cs@pvpgn@@YAHPAUt_connection@12@PAUt_packet@2@@Z) [C:\Users\d2dude\Desktop\pvpgn-magic-builder-2.13\build\src\d2cs\d2cs.vcxproj]
handle_d2cs.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pvpgn::bnetd::account_get_sex(struct pvpgn::bnetd::account_struct *)" (?account_get_sex@bnetd@pvpgn@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAUaccount_struct@12@@Z) referenced in function "int __cdecl pvpgn::d2cs::on_client_creategamereq(struct pvpgn::d2cs::t_connection *,struct pvpgn::t_packet *)" (?on_client_creategamereq@d2cs@pvpgn@@YAHPAUt_connection@12@PAUt_packet@2@@Z) [C:\Users\d2dude\Desktop\pvpgn-magic-builder-2.13\build\src\d2cs\d2cs.vcxproj]


C:\Users\d2dude\Desktop\pvpgn-magic-builder-2.13\build\src\d2cs\Release\d2cs.exe : fatal error LNK1120: 2 unresolved externals [C:\Users\d2dude\Desktop\pvpgn-magic-builder-2.13\build\src\d2cs\d2cs.vcxproj]
```

for this code:
```
//file is handle_d2cs.cpp
//snip base includes
#include bnetd/account.h
#include bnetd/account_wrap.h

static int on_client_creategamereq(t_connection * c, t_packet * packet) {
    char const * username;
    char const * sex;
    pvpgn::bnetd::t_account * account;
    //snip

    if (!(username = d2cs_conn_get_account(c))) {
        eventlog(eventlog_level_error, __FUNCTION__, "missing account for connection");
        return -1;
    }
    account = pvpgn::bnetd::accountlist_find_account(username);
    sex = pvpgn::bnetd::account_get_sex(account).c_str();
    //snip
}
```

I am investigating what link errors are and how they are caused.  I am using the [list compiled by this gentleman](http://stackoverflow.com/a/12573818/4206756).  I'm not sure, but one of the bullets lists library order as a possible culprit -- do my imports need to be in a certain order for this to work?  Thank you for your help

**Comment by d2dude** [comment]
I may be barking up the wrong tree so to speak, but after researching and several attempts to fix, I tried to add account.cpp as an external dependency to the d2cs project build to try and resolve the above linking issue, following this advice:

```
A build dependency is only defined as a project dependency in the solution. In earlier versions of Visual Studio, this level of dependency was sufficient. However, starting with Visual Studio 2010, Visual Studio requires a project-to-project reference. If your project does not have a project-to-project reference, you may receive this linker error. Add a project-to-project reference to fix it.
```
However, my changes seem to be overwritten when I run the magic builder, meaning it is generating fresh project files from some configuration or something (I am admittedly very new to these projects).

Scratching my head..  My next try will be following docs/compilevisualstudio2015.md without the help of magic-builder

**Comment by RElesgoe** [comment]
I noticed that none of the other files in the d2cs project does not include any headers from the bnetd project, it seems that ````accountlist_find_account()```` shouldn't be used then.

**Comment by d2dude** [comment]
Ohhh I see, is there another way to access the profile information?

**Comment by RElesgoe** [comment]
I'm not sure, I'm not familiar with the code in the d2cs and d2db projects.

**Comment by d2dude** [comment]
Darn.  Thank you for your time and assistance
