### ISSUE TITLE
Windows build fails due to ZLIB_WINAPI macro if zlibwapi.dll is NOT used

### ISSUE THREAD

**Issue by cen1** [pvpgn/pvpgn-server#24]
Since I don't like "magic" things I decided to build for Windows from source the regular way. The tutorial is here http://pvpgn.wikia.com/wiki/Windows_Source_Install and the problem lies in point 4.

Code in bnetd->anongames_info.cpp line 32 assumes that everyone building for windows will use prebuilt zlibwapi.dll library. This is different than normal zlib.lib/zlib.dll build which you get if you build zlib from source. The difference is described in zlib FAQ in points 6 and 7: http://www.zlib.net/DLL_FAQ.txt

The simple solution when using your own zlib is to simply comment out the macro but that's obviously not a solution. We would need a new global macro which you could define in cmake at build time to switch between the two calling conventions.

I didn't test this on your fork but I assume it's the same problem because I am guessing nobody in the past X years actually tried to build without magic builder. I checked the magic builder and as I thought it ships with zlibwapi.dll by default.

**Comment by HarpyWar** [comment]
Somebody knows where to download official `zlib1.dll` of new version 1.2.11?
By the link I see a package `zlib<version>-dll.zip` only for version 1.2.8 https://sourceforge.net/projects/libpng/files/zlib/

When I build it from the sources `contrib/vstudio/` it produces `zlibwapi.dll`

**Comment by cen1** [comment]
What if you simply rename the dll?

**Comment by cen1** [comment]
I think you need to remove the ZLIB_WINAPI macro and change the output name.
