### ISSUE TITLE
Set UNICODE for Visual Studio

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#241]
Use the wide version of WinAPI functions instead of ANSI.

**Comment by cen1** [comment]
After googling a bit you just need to add these definitions to cmake and VS will pick it up:
ADD_DEFINITIONS(-DUNICODE)
ADD_DEFINITIONS(-D_UNICODE)

**Comment by RElesgoe** [comment]
http://stackoverflow.com/questions/7953025/why-both-unicode-and-unicode
It seems that just ````UNICODE```` will suffice.
