### ISSUE TITLE
pvpgn и gcb

### ISSUE THREAD

**Issue by Artyom91** [pvpgn/pvpgn-server#255]
@HarpyWar Здравствуйте. Много времени прошло с разборов полета этой темы.
Здесь есть описание: https://github.com/pvpgn/pvpgn-server/issues/129

Так вот, я научился компилить GCB с тех времен и нашел исправление, исправление вот: https://github.com/uakfdotb/gcb/issues/28#issuecomment-72589902 но оно не полное, суть в следующем:

Исправление не полное, ip адрес изменяется, но хосты перестает видеть в гарене. Т.е вроде бы всё работает, но ботов в гарене не отображает.

Может попробуем еще раз разобраться?

**Comment by HarpyWar** [comment]
Вам следует обратиться к разработчикам ghost с этим вопросом, т.к. он не относится напрямую к PvPGN.
