### ISSUE TITLE
BUG: /channels -- 3 problems

### ISSUE THREAD

**Issue by reillychase** [pvpgn/pvpgn-server#260]
This is tested on 1.99.7.1:
#1 When you are logged in using a game client (I used Warcraft II), '/channels' returns an error that the game client tag must be supplied. I tested on a version 1.99.0 PvPGN server and it was working without supplying the client tag
#2 Even when game client tag is supplied ('/channels w2bn') the return output is:

-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----

instead of the channels
#3 Also need to checkout the '/channels all' command which returns:

-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----
-----------name----------- users ----admin/operator----

![pvpgn-channels-bug](https://cloud.githubusercontent.com/assets/17455708/19602879/9021a988-9774-11e6-96f4-251becf8f2b1.png)

**Comment by aancw** [comment]
I think that @HarpyWar misstyping. Open src/bnetd/command.cpp and edit function **_handle_channels_command** 

change `message_send_text(c, message_type_info, c, msgtemp);` at the end of function to `message_send_text(c, message_type_info, c, msgtemp0);`

That should work again!
