### ISSUE TITLE
How do I compine PVPGN for Windows ?

### ISSUE THREAD

**Issue by ghostdlr** [pvpgn/pvpgn-server#262]
Is there any tutorial on how to compile pvpgn source code for Windows ? 

Can I do it with Visual Studio ?

**Comment by RElesgoe** [comment]
See the README or docs/compile.visualstudio2015.md

**Comment by cen1** [comment]
In short: `cmake -G "Visual Studio 14 2015" -H./ -B./build` will produce .sln project in build directory. From there you simply open it and build it.
