### ISSUE TITLE
No artifacts for download at build servers?

### ISSUE THREAD

**Issue by Karaulov** [pvpgn/pvpgn-server#264]
No artifacts in build servers for download?

For example:
![kejwzpx 1](https://cloud.githubusercontent.com/assets/6445336/20561743/1a340f0e-b191-11e6-87d8-af4d1ad8c811.png)

![xi9j8dg 1](https://cloud.githubusercontent.com/assets/6445336/20561755/29141230-b191-11e6-8233-bce1ba154716.png)

How to download build pvpgn from appveyor/travis-ci?

**Comment by RElesgoe** [comment]
I suggest using the [latest release](https://github.com/pvpgn/pvpgn-server/releases) uploaded here on Github.

**Comment by Karaulov** [comment]
But here have not latest build 

![g7bc0xa 1](https://cloud.githubusercontent.com/assets/6445336/20590802/5f8fb74c-b236-11e6-8833-def1d9c8fd64.png)

**Comment by RElesgoe** [comment]
If you're looking to create a production-ready server, I would suggest using the latest release that's posted on Github. Otherwise, you will need to compile the code yourself for now.

**Comment by HarpyWar** [comment]
I got it working, now artifacts are available in Appveyor. Earlier it were uploaded on Dropbox.
I guess it's a nice feature that may helps in several cases. Like help analyzing a user's crash dump of a specified commit (there are symbol files are included in debug builds), or if user want to try the latest features, or may be create some autotesting tools of the latest source code to use on Windows.

**Comment by Karaulov** [comment]
Thank you! )
