### ISSUE TITLE
man Pages needs Toggle to enable/disable and/or Cmake path option

### ISSUE THREAD

**Issue by Espionage724** [pvpgn/pvpgn-server#265]
PvPGN on `make install` wants to install man pages to a location accessible by root. I compile PvPGN as a non-privileged user, and this causes the install process to fail on the man page step.

I don't exactly need the man pages, so perhaps a Cmake option to disable them might be viable. Alternatively, a Cmake option to set the man directory would also work (I could set the directory to a location my PvPGN user can access). I have no idea if the man pages could work from a non-standard directory though so I'm not sure how good of an idea this is.

**Comment by cen1** [comment]
I think you got the compiling and installing step confused. `make` compiles it but `make install` installs it (basically, it copies files to `/usr/local/*` which requires root. I don't see a problem here.

**Comment by Espionage724** [comment]
Ah, I usually run 'make install' when I compile things just so it'll automatically put the compiled stuff in the expected folder.

With PvPGN (and other game servers), I have a dedicated non-privileged account that can only write to a few folders. `CMAKE_INSTALL_PREFIX` covers everything except the man pages, which is a forced define to `SHARE_INSTALL_PREFIX` in `src/cmake/Modules/DefineInstallationPaths.cmake`.

As a quick hack-fix, I changed the `SHARE_INSTALL_PREFIX` to `CMAKE_INSTALL_PREFIX` at https://github.com/pvpgn/pvpgn-server/blob/master/cmake/Modules/DefineInstallationPaths.cmake#L41

**Comment by cen1** [comment]
Ah I see. The define is at https://github.com/pvpgn/pvpgn-server/blob/master/cmake/Modules/DefineInstallationPaths.cmake#L61 but it's already used previously. That block should probably be moved further up (like at line 10) and then it should be fine. Can you try this and make a pull request if it works?
