### ISSUE TITLE
Explore options to not require sudo when running bnetd

### ISSUE THREAD

**Issue by cen1** [pvpgn/pvpgn-server#269]
Atm the default install requires sudo to run bnetd. We should fix this. There is no really good reason why we need to run as root.

**Comment by DragonZX** [comment]
Why? As I understand we may to use any user and --chuid $USERID:$GROUPID to run a daemon

**Comment by cen1** [comment]
It is not documented anywhere at the moment and the current init script does not use it. I think bnetd drops privileges by itself on startup. `Dec 30 16:22:08 [debug] give_up_root_privileges: about to give up root privileges
`

**Comment by DragonZX** [comment]
No, bnetd.conf has options 
```
#effective_user  = games
#effective_group = games
```
to run it under. So to redirect priviledges you need to use superuser priviledges, but Debian init script by _Miquel van Smoorenburg_ and _Ian Murdock_  uses root ATM.
As for me - I've modified it to run binary under pvpgn user - It's not bad security practice. 
So, it's only options to think.

**Comment by cen1** [comment]
Installing to home folder works fine and does not require sudo to run. Running under it's own user is also possible so closing.
