### ISSUE TITLE
problem when compiling

### ISSUE THREAD

**Issue by venmade** [pvpgn/pvpgn-server#275]
When compiling "cd build && make"

I get some errors:
/root/pvpgn-server/src/common/bigint.cpp: In constructor 'pvpgn::BigInt::BigInt(uint32_t)':
/root/pvpgn-server/src/common/bigint.cpp:73:10: warning: right shift count >= width of type [-Wshift-count-overflow]
    input >>= bigint_base_bitcount;

/root/pvpgn-server/src/bnetd/anongame_wol.cpp: In function 'int pvpgn::bnetd::_get_pair(int*, int*, int, bool)':
/root/pvpgn-server/src/bnetd/anongame_wol.cpp:336:36: warning: integer overflow in expression [-Woverflow]
     *i = (max * rand() / (RAND_MAX + 1));
                                    ^
/root/pvpgn-server/src/bnetd/anongame_wol.cpp:339:36: warning: integer overflow in expression [-Woverflow]
     *j = (max * rand() / (RAND_MAX + 1));
                                    ^
/root/pvpgn-server/src/bnetd/anongame_wol.cpp:343:37: warning: integer overflow in expression [-Woverflow]
      *j = (max * rand() / (RAND_MAX + 1));

/root/pvpgn-server/src/bnetd/tracker.cpp: In function 'int pvpgn::bnetd::tracker_send_report(const t_addrlist*)':
/root/pvpgn-server/src/bnetd/tracker.cpp:122:89: warning: zero-length gnu_printf format string [-Wformat-zero-length]
 snprintf(reinterpret_cast<char*>(packet.platform), sizeof packet.platform, "");
                                                                              ^
/root/pvpgn-server/src/bnetd/tracker.c

I tried to assemble the build at:
Centos, Ubuntu, Debian and everywhere the same.

**Comment by cen1** [comment]
Does the build actually fail? All I see here are warnings not errors.

**Comment by venmade** [comment]
Build, not counting these "warnings" is successful.
- but, do not run itself pvpgn server.

**Comment by cen1** [comment]
For installing you need to run `make install` which will put your binary at `/usr/local/sbin/bnetd`, your config files in `/usr/local/etc` and logs/other files to `/usr/local/var`.

**Comment by venmade** [comment]
I used the installation method:
sudo apt-get -y install build-essential git cmake zlib1g-dev
git clone https://github.com/pvpgn/pvpgn-server.git
cd pvpgn-server && cmake -G "Unix Makefiles" -H./ -B./build
cd build && make

Perhaps I need to use the old method of installation?
System Ubuntu 16.04

**Comment by venmade** [comment]
No comment... I just forgot about the command make install
And himself came up with the problem.
