### ISSUE TITLE
PVPGN

### ISSUE THREAD

**Issue by Allecsxx** [pvpgn/pvpgn-server#277]
HI,

I can't make it work... Every time i'm trying to connect through battlenet it says "you may try to connect to a invalid b net server".Using gateway editor and checking on 127.0.0.1 it says "connected". I can't get my head arround what's not good. I've tried using 192.168.0.21 (my lan ip) instead of 127.0.0.1 on batconfd but still no change! 

Server is now running.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Dec 28 15:54:38 [info ] pvpgn::bnetd::storage_init: initializing storage layer (available drivers: file)
Dec 28 15:54:38 [info ] pvpgn::bnetd::storage_init: using file storage driver
Dec 28 15:54:38 [info ] pvpgn::FDWSelectBackend::FDWSelectBackend: fdwatch select() based layer initialized (max 1000 sockets)
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/deDE/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/esES/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::i18n_load: localization file loaded "conf\i18n/common.xml"
Dec 28 15:54:38 [info ] pvpgn::bnetd::server_set_hostname: set hostname to "alex-PC"
Dec 28 15:54:38 [info ] pvpgn::bnetd::AdBanner::AdBanner: Created ad id=0x00000000 filename="ad000001.png" link="http://pvpgn.pro" client="W3XP" lang="NULL"
Dec 28 15:54:38 [info ] pvpgn::bnetd::AdBanner::AdBanner: Created ad id=0x00000001 filename="ad000002.mng" link="http://pvpgn.pro" client="W3XP" lang="NULL"
Dec 28 15:54:38 [info ] pvpgn::bnetd::AdBanner::AdBanner: Created ad id=0x00000002 filename="ad000001.smk" link="http://pvpgn.pro" client="NULL" lang="NULL"
Dec 28 15:54:38 [info ] pvpgn::bnetd::output_init: initializing output file
Dec 28 15:54:38 [info ] pvpgn::bnetd::accountlist_create: started creating accountlist
Dec 28 15:54:38 [info ] pvpgn::bnetd::accountlist_load_all: loaded 0 user accounts in 0 seconds
Dec 28 15:54:38 [info ] pvpgn::bnetd::ladder_createxptable: set war3 xpcalc maxleveldiff to 6
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/SEXP_AR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/SEXP_CR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/SEXP_AW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/SEXP_CW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/SEXP_AG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/SEXP_CG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/STAR_AR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/STAR_CR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/STAR_AW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/STAR_CW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/STAR_AG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/STAR_CG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_AR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_CR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_AW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_CW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_AG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_CG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_ARI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_CRI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_AWI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_CWI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_AGI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W2BN_CGI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/RAL2_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/TSUN_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/TSXP_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W3XP_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/WAR3_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/YURI_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W3XP_TEAM_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/WAR3_TEAM_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W3XP_FFA_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/WAR3_FFA_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/W3XP_AT_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::loadBinary: successfully loaded var\ladders/WAR3_AT_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/SEXP_AR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/SEXP_CR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/SEXP_AW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/SEXP_CW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/SEXP_AG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/SEXP_CG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/STAR_AR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/STAR_CR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/STAR_AW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/STAR_CW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/STAR_AG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/STAR_CG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_AR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_CR_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_AW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_CW_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_AG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_CG_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_ARI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_CRI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_AWI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_CWI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_AGI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W2BN_CGI_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/RAL2_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/TSUN_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/TSXP_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W3XP_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/WAR3_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/YURI_SOLO_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W3XP_TEAM_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/WAR3_TEAM_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W3XP_FFA_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/WAR3_FFA_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/W3XP_AT_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::LadderList::saveBinary: successfully saved var\ladders/WAR3_AT_LADDER
Dec 28 15:54:38 [info ] pvpgn::bnetd::tracker_set_servers: tracking packets will be sent to 69.23.104.66:6114
Dec 28 15:54:38 [info ] pvpgn::bnetd::tracker_set_servers: tracking packets will be sent to 94.26.48.7:6114
Dec 28 15:54:38 [info ] pvpgn::bnetd::tracker_set_servers: tracking packets will be sent to 94.212.26.90:6114
Dec 28 15:54:38 [info ] pvpgn::bnetd::tracker_set_servers: tracking packets will be sent to 144.76.61.239:6114
Dec 28 15:54:38 [info ] pvpgn::bnetd::aliasfile_load: done loading aliases
Dec 28 15:54:38 [info ] pvpgn::trans_load: trans file loaded
Dec 28 15:54:38 [info ] pvpgn::bnetd::anongame_infos_load: got langID: []
Dec 28 15:54:38 [info ] pvpgn::bnetd::anongame_infos_load: got langID: [deDE]
Dec 28 15:54:38 [info ] pvpgn::bnetd::anongame_infos_load: got langID: [zhCN]
Dec 28 15:54:38 [info ] pvpgn::bnetd::anongame_infos_load: got langID: [ruRU]
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: Loading Lua interface...
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/antihack/starcraft.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/command/ping.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/command/redirect.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/command/stats.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/command/w3motd.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/enum/attr.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/enum/eventlog.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/enum/game.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/enum/message.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/enum/messagebox.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/enum/tag.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/account.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/account_wrap.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/channel.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/eventlog.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/game.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/extend/message.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/ghost/command.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/ghost/command_callback.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/ghost/ghost.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/ghost/handle.lua
Dec 28 15:54:38 [info ] pvpgn::bnetd::lua_load: lua/ghost/helper.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/bitwise.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/common.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/convert.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/file.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/math.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/string.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/table.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/include/timer.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/quiz/command.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/quiz/helper.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/quiz/quiz.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/quiz/records.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/config.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/handle_channel.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/handle_client.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/handle_command.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/handle_game.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/handle_server.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/handle_user.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: lua/main.lua
Dec 28 15:54:39 [info ] pvpgn::bnetd::lua_load: Lua sripts were successfully loaded (42 files)
Dec 28 15:54:39 [info ] lua/antihack/starcraft.lua:20: Starcraft Antihack activated
Dec 28 15:54:39 [info ] pvpgn::bnetd::_setup_listensock: listening for bnet connections on 127.0.0.1:6112 TCP
Dec 28 15:54:39 [info ] pvpgn::bnetd::_setup_listensock: listening for w3route connections on 0.0.0.0:6200 TCP

**Comment by Allecsxx** [comment]
FOR WAR3 USE

**Comment by Allecsxx** [comment]
Dec 28 15:59:49 [info ] pvpgn::bnetd::sd_accept: [760] accepted connection from 127.0.0.1:60383 on 127.0.0.1:6112
Dec 28 15:59:49 [info ] pvpgn::bnetd::conn_create: [760][740] sessionkey=0x1482975740 sessionnum=0x00000000
Dec 28 15:59:49 [info ] pvpgn::bnetd::conn_destroy: [760] closed init connection

**Comment by cen1** [comment]
Which w3 version? Do you use w3l?

**Comment by Allecsxx** [comment]
TFT 1.27a

**Comment by Allecsxx** [comment]
LOL ... the issue is sorted :))) starting with w3l works smoothly :)))) i only tried with frozen throne and war3
