### ISSUE TITLE
Technical issues (again, database)

### ISSUE THREAD

**Issue by venmade** [pvpgn/pvpgn-server#284]
Problem solved (formally it was not)

**Comment by cen1** [comment]
Seems like a bug in driver detection in storage.cpp. Will take a look.

**Comment by venmade** [comment]
@cen1 I have studied storage.cpp and incoming data to it.
- also, compare the file storage.cpp with other versions of pvpgn
- and found no "in my opinion" problems.

problem is found?
- maybe I'm missing something. (sometimes the installation goes normally and everything works fine)

**Comment by cen1** [comment]
Did you try to enable more loglevels in config?

**Comment by venmade** [comment]
@cen1 At the moment I installed the system 3: Centos, Debian, Ubuntu.
I'll check on some of the systems will work to connect to the database.

loglevels settings I have not changed, they are standard:
loglevels = fatal, error, warn, info, debug, trace
Errors in the log no.

**Comment by venmade** [comment]
@cen1 Can we contact you via email to try to resolve and understand the problem?

**Comment by cen1** [comment]
I will try to reproduce your exact commands on 16.04 in the next day and see what happens.

**Comment by venmade** [comment]
@cen1 I very much hope that in the near future will be able to solve the issue.
And I would like to know whether you are working on a commercial basis? (I would like to ask some technical questions)

**Comment by cen1** [comment]
Hi, I spun up a fresh ubuntu 16.04 and followed your commands. Everything works fine, tables were created.
`
cmake -G "Unix Makefiles" -H./ -B./build -DWITH_MYSQL=true
`
`
storage_path = "sql:mode=mysql;host=127.0.0.1;name=pvpgn;user=root;pass=123456;default=0;prefix=pvpgn_"
`

Perhaps CMake cache is messing up with you? If you run cmake without -DWITH_MYSQL first perhaps you should delete the build folder after the second run.
