### ISSUE TITLE
Problem with installing in custom CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by pztrn** [pvpgn/pvpgn-server#285]
OS: FreeBSD 11-RELEASE amd64.

```
-- Installing: /home/pvpgn/server/etc/pvpgn/i18n/zhTW
-- Installing: /home/pvpgn/server/etc/pvpgn/i18n/zhTW/bnmotd.txt
CMake Error at /home/pvpgn/source/build/man/cmake_install.cmake:39 (file):
  file cannot create directory: /man.  Maybe need administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:34 (include)


*** Error code 1

Stop.
make: stopped in /usr/home/pvpgn/source/build
```

**Comment by RElesgoe** [comment]
Try running CMake with ````sudo````.

**Comment by pztrn** [comment]
I will not do that. If I'm using -DCMAKE_INSTALL_PREFIX, then all parts of generated cmake files should respect it. But it turns out that man files installation does not respect it. After removing man-related lines from cmake_install file - everything installed in CMAKE_INSTALL_PREFIX as supposed to.

**Comment by RElesgoe** [comment]
Actually, I just accepted a pull request a few minutes ago that is supposed to fix this issue. Can you try pulling the latest changes?

**Comment by pztrn** [comment]
Yep, now paths in cmake_install.cmake are fine. Thanks!

**Comment by RElesgoe** [comment]
#283 #265
