### ISSUE TITLE
Hieroglyphs in the user list (GUI version)

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#286]
([reported by r000t](http://forums.pvpgn.pro/viewtopic.php?pid=8533#p8533) on forums)
![default](https://cloud.githubusercontent.com/assets/1132835/22027369/b6f9fe1a-dce4-11e6-9020-b4e490f062ff.png)

**Comment by HarpyWar** [comment]
The issue is confirmed, I see hieroglyphs too on my Windows 10 (Russian locale). It was ok before one of your commits in the first half of 2016, may be earlier.
One of the users also wrote that sometimes login is unsuccessfull for several accounts on 1.99.7.1-PRO but these accounts work on old 1.99. May be these two problems are associated.

**Comment by RElesgoe** [comment]
> One of the users also wrote that sometimes login is unsuccessfull for several accounts on 1.99.7.1-PRO but these accounts work on old 1.99. May be these two problems are associated.

That sounds like a separate problem, but I'm not aware of any changes that would cause accounts to not work with 1.99.7.1-PRO.

**Comment by HarpyWar** [comment]
He sent you a database dump with accounts which not work in PRO version. Check it please in forum PM, when you have a time.

**Comment by RElesgoe** [comment]
026751e2cf14cd77b68ff5ff8dd5003d1e6eab4f
