### ISSUE TITLE
w3motd.txt is broken

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#288]
In earlier pvpgn builds text from the file [w3motd.txt](https://github.com/pvpgn/pvpgn-server/blob/master/conf/i18n/w3motd.txt) displays as follow, and the last line is invisible as intended
![default](https://cloud.githubusercontent.com/assets/1132835/22304492/b62c8380-e348-11e6-8f18-b457f364c28a.png)

But now it show always only last line (it seems new lines do not handled properly)
![default](https://cloud.githubusercontent.com/assets/1132835/22304501/bffd7658-e348-11e6-8935-1d1cc4fe8dfd.png)

**Comment by RElesgoe** [comment]
What patch are you using? Try using pre-1.27a patch.

**Comment by HarpyWar** [comment]
Patch 1.26.0.1, but it does not depend on the client version. 
The 1st screen above was made today on build 2015/02 on the same Warcraft 3 client. And 2d screen on build 2016/09.

**Comment by yujintong** [comment]
replace handle_bnet.cpp file codes:
                                        std::snprintf(serverinfo, sizeof serverinfo, "%s\n", &line[1]);
to 
					strncat(serverinfo, &line[1], strlen(&line[1]));
					strcat(serverinfo, "\n");

**Comment by RElesgoe** [comment]
38c78a5a1c48c4e39bf3e6e11be6b417e0b82101
