### ISSUE TITLE
Remove cdb support

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#289]
cdb storage is similar to plain text when each account has its own data file. 

Why to cut it off:
* cdb performance is imperceptible on so small databases
* cdb format is not human readable, I didn't find user friendly database viewers and editors
* Less source code to support in the future
* Nobody uses pvpgn with cdb. It was added when there was no sql support. Now it's better to use sqlite instead.

**Comment by cen1** [comment]
Seems reasonable. The fact that nobody objected speaks for itself.

**Comment by pkubica** [comment]
Hi,
I would like to ask if is there any way (tool, script..) how to migrate existing database from cdb to sql based database? 
I have only a few accounts (for Diablo II) which I want to preserve. If it is possible to do it only manually, could you point me how to do that?

Thank you,
Petr

**Comment by xpeh-owns** [comment]
@pkubica https://github.com/pvpgn/pvpgn-server/blob/master/scripts/storage/cdb2sql.pl

**Comment by RElesgoe** [comment]
0923f6a52e261d38ba2ed6715278a40262621fcc
