### ISSUE TITLE
PvPGn and WC3 FT not connect

### ISSUE THREAD

**Issue by bleachhun** [pvpgn/pvpgn-server#293]
![help](https://cloud.githubusercontent.com/assets/1648035/24075745/6145ddb0-0c21-11e7-9847-7cec35280e06.png)
-Ooops game not print screen fail....-
Games Version 1.27.1.7085
Not connection. Port:6112 and 6200 ping okay. Gateway Editor Ping Ok.

Debian 8

**Comment by cen1** [comment]
Are you using w3l?

**Comment by bleachhun** [comment]
w3l? Warcraft 3 launcher? 

Gateway Editor -> launch WC3 FT -> Connect Server -> Notconnecting to battlenet please chech internet error.

**Comment by cen1** [comment]
You need this https://github.com/w3lh/w3l to join with Warcraft 3
