### ISSUE TITLE
news.txt и баг с датой

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#303]
Здравствуйте. В файле news.txt такое текст:
{27/04/2017}
Начались первый тесты сервера.
------------------
Почему-то в игре отображает на два года больше и дата другая.

4 марта 2019.

**Comment by HarpyWar** [comment]
Delete `bncache.dat` inside game folder and try again.

**Comment by TemKaSD** [comment]
@HarpyWar Я знаю, что эти данные кешируются. При переходе между серверами например, они обновляются. Вот, без изменений:

![2017-04-29_142253](https://cloud.githubusercontent.com/assets/6318282/25552813/ba35fd02-2ce6-11e7-9ca0-159c6abe80ce.png)
![2017-04-29_142547](https://cloud.githubusercontent.com/assets/6318282/25552827/206f4196-2ce7-11e7-8352-0b0c9e20090e.png)

И почему-то пишет 1 новый предмет, а не 1 новая новость.

**Comment by Dramacydal** [comment]
Потому что писать надо {04/27/2017}
