### ISSUE TITLE
Фильтр ботов по каналам

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#305]
@HarpyWar Прив. Подскажите пожалуйста, возможно ли такое через Pvpgn?
Я запустил ботов ghost++ на разные каналы, как сделать, чтобы боты хостили только на каналах?
Т.е я запускаю бот 1 на канал 1, бот 2 на канал 2, мне нужно чтобы бот 1 НЕ отображался на канале 2 и наоборот.

**Comment by HarpyWar** [comment]
а) Если команды вводятся в pvpgn через `/host`, и затем перенаправляются боту, то это можно реализовать через Lua https://forums.pvpgn.pro/viewtopic.php?id=1644
У каждого своя реализация, поэтому как именно это сделать каждый решает сам https://forums.pvpgn.pro/viewtopic.php?id=1680

б) Если команды отправляются напрямую боту через `/whisper bot host ...`, то нужно изменять исходники бота, чтобы он проверял находится ли отправляющий ему команду пользователь на канале с ботом или нет.
Впрочем, если команды проксируются через pvpgn (первый вариант), то ghost бот может выполнять ту же проверку исключительно у себя.
