### ISSUE TITLE
Will pvpgn support starcraft 1.18?

### ISSUE THREAD

**Issue by cysin** [pvpgn/pvpgn-server#306]
Will pvpgn support starcraft 1.18?

**Comment by tagban** [comment]
Not yet. They are making so many adjustments, plus it no longer checks the registry for server addresses rather grabs a list each time from battle.net.

**Comment by RElesgoe** [comment]
It definitely won't be supported, at least not by me. The protocol is entirely different and undocumented.
Lastly, Blizzard is truly maintaining the game now, which I believe we should respect.

**Comment by HarpyWar** [comment]
Just for note.
There is Fish Battle.net server which works with old and new Starcraft, including Remastered (if I'm not mistaken that server worked on PvPGN earlier?).
If connect with old Starcraft it will ask about update, but if click Cancel it allows to login to the server:

![2017-08-31 11 40 34](https://user-images.githubusercontent.com/1132835/29914715-31f284f2-8e42-11e7-95ca-64089de5c60b.png)
![2017-08-31 11 40 38](https://user-images.githubusercontent.com/1132835/29914720-33e96384-8e42-11e7-9105-aaeb4f932cd4.png)
![2017-08-31 11 41 19](https://user-images.githubusercontent.com/1132835/29914754-553e8cda-8e42-11e7-8649-0c4fb2470a4d.png)

In new Starcraft you can login with the same account, and see exactly the same motd, and check logged in accounts using /whois:

![2017-08-31 11 44 51_low](https://user-images.githubusercontent.com/1132835/29915114-76cce58a-8e43-11e7-8768-d5b3303219e7.gif)
![2017-08-31 11 45 12_low](https://user-images.githubusercontent.com/1132835/29915131-85876118-8e43-11e7-9a25-3d6e78deeeed.gif)
![2017-08-31 11 45 50_low](https://user-images.githubusercontent.com/1132835/29915143-8f2622a4-8e43-11e7-9f2c-b1ede41491a5.gif)

But old users can't play between new Starcraft users. Games between different versions are not visible (also you are not able to join if type a game name).

So Fish Battle.net server supports both old and new Starcraft now. 
It looks like Battle.net server list in new Starcraft is loading from a remote Blizzard server now, unlike it was stored in Windows registry in earlier versions.

Game lobby protocol could be changed and improved in new Starcraft. For example, sometimes game is started after a long delay (up to 30 seconds), but then there are no lags or few lags inside game, unlike in old Starcraft. So anyway it's not possible to play between old and new Starcraft.
Theoretically it's possible update PvPGN to support the new version. But it may be required to modify the Starcraft client too to add support for custom Battle.net servers. Or create a "proxy server" that return custom server list, with replace it in user /etc/hosts

**Comment by xpeh-owns** [comment]
> The protocol is entirely different and undocumented.
WUT????

**Comment by RElesgoe** [comment]
It's believed that there is a separate protocol that acts as a proxy between the client and the old Battle.net protocol. Packets are encrypted so we won't be able to inspect anything.
