### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#307]
Need to be researched why these errors appear in logs on a new server. Fix or supress them, or switch to other type (warn/debug).

> 1.
> When I first run pvpgn.exe this error shows up:
> Apr 27 10:11:49 [error] pvpgn::bnetd::friendlist_unload: got NULL flist
> it displays so much times how many users i have registered
> 2.
> When I just restart the server from the upper menu, without quitting the whole program, this error shows up:
> Apr 27 10:16:14 [error] pvpgn::_process_option: option 'w2bn_iconfile' unknown

https://forums.pvpgn.pro/viewtopic.php?id=1765

**Comment by RElesgoe** [comment]
Whoever has the second problem with `w2bn_iconfile` probably modified the bnetd.conf file. The term doesn't appear anywhere when you search this repository.

**Comment by RElesgoe** [comment]
8b333d0fd902a5326ccfc6b8a4cf4d8a800c4c32
