### ISSUE TITLE
Как правильно обновлять pvpgn?

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#309]
Здравствуйте. Как правильно обновлять pvpgn чтобы сохранить все настройки?

**Comment by HarpyWar** [comment]
На PRO версии по сравнению с 1.8.5 или 1.99 добавлены дополнительные файлы конфигов и дополнительные опции в существующих конфигах. 
Лучше всего настроить новый сервер заново, перенеся вручную данные из старых конфигов.
Структура базы данных не изменялась, поэтому существующую БД можно использовать для любой версии сервера.
