### ISSUE TITLE
can't compile using magic builder 

### ISSUE THREAD

**Issue by Nightshades1** [pvpgn/pvpgn-server#310]
Hey, i have VC 14 (visual studio 2015 installed) i have almost 70% of the header "NOT FOUND" windows.h not found, and the others seem to be linux header file ...

Can't you make a damn proper solution ready mate ? that would solve most of the problem, thanks.

**Comment by RElesgoe** [comment]
Can you copy and paste the exact error message

**Comment by Nightshades1** [comment]
Hey, how can i paste the error ? it's from wget many header not found, too much errors.

**Comment by Nightshades1** [comment]
Damn it seem i need to download Windows SDK 10... will be great 12GB download with 60kb/s lol.
i used build_pvpgn.bat > text.txt for the output, packed in a .rar you can get it on my account: http://www.mediafire.com/file/eww71hdjw2s2267/text.rar

I don't know if it's because i don't have windows 10 SDK installed or it seem that it's reading Visual Studio 2017 RC path (i only have Visual studio 2017 installed with c#) maybe there is a bug or something as i selected visual studio 2015 (not sure what's the problem with those headers not found).

And what's that POSIX if it's linux related idk as i'm always on windows 👍 thx.

**Comment by cen1** [comment]
Try the CMake way as described in the readme, it should be able to find the correct dependencies or tell you what is actually missing.

**Comment by Nightshades1** [comment]
Ok i used it like this

C:\pvpgn-magic-builder\module\tools\cmake-3.8.0-rc4-win32-x86\bin>cmake -g "Visual Studio 14 2015" -H../../../../source -B../../../../build
-- pvpgn is used as APPLICATION_NAME
-- Found MySQL: C:/pvpgn-magic-builder/module/include/mysql/5.7.17/libmysql.lib
-- Checking POSIX headers
-- Checking optional POSIX/required SUS headers
-- Checking FreeBSD-based headers
-- Checking BSD headers
-- Checking Linux headers
-- Checking Win32 headers
-- Checking other headers
-- Checking for single argument mkdir MKDIR_TAKES_ONE_ARG
-- Checking for single argument mkdir MKDIR_TAKES_ONE_ARG - found
-- Configuring done
-- Generating done
-- Build files have been written to: C:/pvpgn-magic-builder/build

C:\pvpgn-magic-builder\module\tools\cmake-3.8.0-rc4-win32-x86\bin>cmake -g "Visual Studio 14 2015" -H../../../../source -B../../../../build

This seem to have correctly build the .sln in the build folder, i will see if i can compile.

**Comment by Nightshades1** [comment]
lol and i can't compile shit i have build error everywhere

**Comment by RElesgoe** [comment]
Windows SDK is required

**Comment by Nightshades1** [comment]
Ah damn i won't be able until i'm on a proper network, i had some doubt but yeah windows SDK :( Thanks for the confirmation, i think you should add that it "require windows SDK" to avoid confusion for people like me :D i had made a basic install of visual studio.

Thanks for the confirmation i think you can close that "issue".

**Comment by HarpyWar** [comment]
Updated in Magic Builder readme. May be your issue also related to this:
https://github.com/pvpgn/pvpgn-magic-builder
> WARNING!
> DO NOT download by clicking on a green button "Clone or download" at the right top corner on this page. In this auto created archive Github replaces Windows carriage return to UNIX format inside *.bat files, because of this scripts may not work properly with wierd errors.
