### ISSUE TITLE
Username is cut in GUI input

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#312]
Select username in the user list, open from the main menu Admin Commands > User Actions  > AdminControlPanel, but only first character filled instead of full username

![image](https://cloud.githubusercontent.com/assets/1132835/26425216/ae53b0c4-40dc-11e7-8d28-0cb63c5934ab.png)

Break point should be set on this line https://github.com/pvpgn/pvpgn-server/blob/61be2e63b6db8d6124534f55a5ec1685acf24ea4/src/win32/winmain.cpp#L764

![image](https://cloud.githubusercontent.com/assets/1132835/26425376/2b0ac774-40dd-11e7-9d87-03e5b2008129.png)

**Comment by RElesgoe** [comment]
9e0a01455df836e4da461317e9b2e2fc23604423
