### ISSUE TITLE
Пользователи в сети работает не корректно

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#313]
@HarpyWar Прив. Давно уже заметил, раньше в друзьях своих смотрел на самом сервере, сейчас установил pvpgn-status и увидел себя в списке онлайн, хотя уже вышел из игры минут 20 назад. Так вот, почему-то пользователи остаются в сети даже через минут 30-40 после того как вышли.

**Comment by TemKaSD** [comment]
@HarpyWar Сразу вопрос на засыпку, логины, через которые хостит ghost++ тоже считаются как пользователями, как это исправить?

**Comment by HarpyWar** [comment]
1) Это англоязычный ресурс. Если желаете получить ответ на вопрос пишите на английском. Иначе обращайтесь на русскоязычный форум.
2) Это репозиторий pvpgn, но не ghost или скрипта pvpgn-status. 
3) Не нужно обращаться лично ко мне, ни здесь ни на форуме. Это сообщество и вопросы направляются всем участникам.

Касательно первого вопроса, проверяйте время последнего обновления файла var/status.xml (или status.dat, в зависимости от опции XML_status_output в bnetd.conf). И опцию output_update_secs, которая задает интервал обновления файла.
Скрипт pvpgn-status просто отображает данные из этого файла.
