### ISSUE TITLE
Can not connect. Please help!

### ISSUE THREAD

**Issue by slaklad** [pvpgn/pvpgn-server#319]
I have built the server on ubuntu 16 64bit for Warcraft 3 : Frozen Throne
Server IP: 18.231.14.167
My Warcraft client version: 1.28.5.7680
Please help me figure out. When I try to connect to my server it here what i get from the logs :

Jul 17 03:32:14 [info ] _setup_listensock: listening for bnet connections on 0.0.0.0:6112 TCP
Jul 17 03:32:14 [info ] _setup_listensock: listening for w3route connections on 0.0.0.0:6200 TCP
Jul 17 03:32:51 [debug] ipbanlist_check: lastcheck: 0, now: 1500262371, now-lc: 1500262371.
Jul 17 03:32:51 [debug] ipbanlist_check: checking 191.177.185.158
Jul 17 03:32:51 [info ] sd_accept: [22] accepted connection from 191.177.185.158:5836 on 0.0.0.0:6112
Jul 17 03:32:51 [info ] conn_create: [22][20] sessionkey=0x854000292 sessionnum=0x00000000
Jul 17 03:32:51 [debug] sd_accept: [22] client connected to a bnet listening address
Jul 17 03:32:51 [info ] handle_init_packet: [22] client initiated bnet connection
Jul 17 03:32:51 [trace] conn_shutdown: [22] connection already closed
Jul 17 03:32:51 [debug] conn_set_class: added latency check timer
Jul 17 03:32:51 [debug] _client_countryinfo109: [22] COUNTRYINFO_109 packet tzbias=0x00b4 lcid=1046 langid=1046 arch="IX86" client="W3XP" versionid=0x0000001c gamelang="enUS"
Jul 17 03:32:51 [debug] _client_countryinfo109: [22] COUNTRYINFO_109 packet from "Brazil" "BRA"
Jul 17 03:32:51 [info ] conn_set_archtag: [22] setting client arch to "IX86"
Jul 17 03:32:51 [info ] conn_set_clienttag: [22] setting client type to "W3XP"
Jul 17 03:32:51 [info ] conn_set_gamelang: [22] setting client gamelang to "enUS"
Jul 17 03:32:51 [debug] _client_countryinfo109: [22] selecting version check
Jul 17 03:32:51 [debug] versioncheck_create: version check entry archtag=IX86, clienttag=W3XP
Jul 17 03:32:51 [debug] _client_countryinfo109: [22] selected "ver-IX86-1.mpq" "A=1239576727 C=1604096186 B=4198521212 4 A=A+S B=B-C C=C^A A=A+B"
Jul 17 03:32:51 [debug] sd_tcpinput: [22] read returned -1 (closing connection)
Jul 17 03:32:51 [info ] conn_destroy: [22] closed bnet connection

**Comment by cen1** [comment]
For 1.28.5 you need to merge https://github.com/pvpgn/pvpgn-server/pull/318 and you need to build the latest w3l master

**Comment by slaklad** [comment]
Thanks. which versions Works right away? Versions supported should be  on the documentation. As well as this info. Because currently it says it works with any client version

**Comment by cen1** [comment]
W3 is getting patched very often lately so support is added with a bit of delay.

**Comment by slaklad** [comment]
I'm not complaining about delaying support for version. It's lacking information about a lot of things. I'm trying to setup a server but now  you are talking about  w3l master where can I get a documentation about it? how do compile ? 

- Which client versions are working right away? without using w3l master?

**Comment by cen1** [comment]
You can't join pvpgn without w3l, it is kind of a common knowledge. You need to build w3l.exe, w3lh.dll and w327.dll from https://github.com/w3lh/w3l and put them in your w3 folder, then run w3 via w3l.exe.

Current pvpgn master supports 1.28.2, if you merge my pull requests it supports latest also.

**Comment by RElesgoe** [comment]
4c6f55d98d3b9167172ff762ad6283aa771f8528
