### ISSUE TITLE
Only one user allowed at a time even with max_concurrent_logins = 0

### ISSUE THREAD

**Issue by Duvy2** [pvpgn/pvpgn-server#326]
Multiple logins from the same account is not working regardless of the bnetd.conf "max_concurrent_logins" property.
If I try to log in with an already logged in user, the warcraft says:
"The account does not exists"

I tried 0, 1, or more values for the "max_concurrent_logins", but the pvpgn does allow only one login per account.

Anyone has some suggestion?

**Comment by RElesgoe** [comment]
PvPGN does not support multiple logins to the same account. The `max_concurrent_logins` option limits the overall amount of concurrent users on the server.
