### ISSUE TITLE
Problem in PVPGN db ?

### ISSUE THREAD

**Issue by Karaulov** [pvpgn/pvpgn-server#327]
**Problem:** can't lock accounts

in bnetd.log : 
**[error] pvpgn::bnetd::account_get_boolattr_real: bad boolean value "t" for key "BNET\auth\lock"**

**Reason:** https://i.imgur.com/2iN5mVJ.png
![2in5mvj 1](https://user-images.githubusercontent.com/6445336/32494942-b20d45ec-c3d4-11e7-90f4-99c89c8e1d44.png)

**Comment by HarpyWar** [comment]
Already fixed https://github.com/pvpgn/pvpgn-server/issues/301

**Comment by Karaulov** [comment]
If for fix need edit mysql table, then problem not fixed...:)

Ok :)

**Comment by HarpyWar** [comment]
That's right, it's fixed for a new installation.
For existing servers you have to manually increase a field size from 1 to 6.
