### ISSUE TITLE
Forbid reading of BNET\acct\verifier with /set

### ISSUE THREAD

**Issue by xpeh-owns** [pvpgn/pvpgn-server#333]
Reason is the same as for BNET\acct\passhash1. As for writing I don't see any necessity since admin-chpass does the same.

**Comment by HarpyWar** [comment]
I think it could be done the same way as I did it for `passhash1` and `username` fields https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/command.cpp#L4630-L4634
