### ISSUE TITLE
Make single release

### ISSUE THREAD

**Issue by xpeh-owns** [pvpgn/pvpgn-server#335]
https://github.com/pvpgn/pvpgn-server/releases
Is there a reason to make a release for every db supported instead all in one?

**Comment by RElesgoe** [comment]
They contain different binaries, it allows people to download only what they need.

**Comment by xpeh-owns** [comment]
How different they are? Every supports it's own Db? And I propose to make 1 release that supports all DB.

**Comment by HarpyWar** [comment]
It's not possible to make a single release with all supported storages.
There is a single storage interface and a storage type is replaced at compile time by `#ifdef` keyword.
