### ISSUE TITLE
versioncheck.conf to json

### ISSUE THREAD

**Issue by xpeh-owns** [pvpgn/pvpgn-server#336]
First results: https://gist.github.com/xpeh-owns/881f040050dd4a4c89cbd34831eccd11
- Order of appearence? Currently it's 'WAR3', 'W3XP', 'STAR', 'SEXP', 'W2BN', 'DRTL', 'D2XP', 'D2DV'. Newer versions are below, opposite to .conf
- Key names/order?

You will add newer versions manually, right?

**Comment by RElesgoe** [comment]
W2BN should be next to W3XP. Can you reverse the order so that the newest versions are at the top instead of oldest.

**Comment by xpeh-owns** [comment]
> Can you reverse the order so that the newest versions are at the top instead of oldest.
But why? 
You proposition of tag order?

**Comment by RElesgoe** [comment]
It's quicker to manually insert new entries at the top.

Since WarCraft 2 and WarCraft 3 are the same series, they should be next to each other.

**Comment by xpeh-owns** [comment]
> It's quicker to manually insert new entries at the top.

If you mean...
So please the whole clienttag order.

**Comment by RElesgoe** [comment]
What I mean is that the objects in each array should be sorted so that the newest versions are at the top (e.g. 1.16.1 at the top for STAR and SEXP).
The order of clients should be WAR3, W3XP, W2BN, STAR, SEXP, DRTL, D2XP, D2DV.

**Comment by xpeh-owns** [comment]
> What I mean is that the objects in each array should be sorted so that the newest versions are at the top (e.g. 1.16.1 at the top for STAR and SEXP).

Yes, I've got it.

**Comment by xpeh-owns** [comment]
https://gist.github.com/xpeh-owns/1d76c897891f9538a63814a55d2ddc12
Need converter from json to conf?

**Comment by xpeh-owns** [comment]
War 2 and 3 are the same series but war2 is never updated, opposite to star/sexp

**Comment by xpeh-owns** [comment]
https://gist.github.com/xpeh-owns/3d13e9d504408e0e41f10c7bc98e8583

**Comment by xpeh-owns** [comment]
Why is there no Mac versions? I've got versioncheck from your rep.

**Comment by RElesgoe** [comment]
People never submitted versioncheck entries for Mac clients.

**Comment by xpeh-owns** [comment]
Surely they exist somewhere, probably even on harpywar forum.
So do you need json-conf converter? Even if you use json in your server original pvpgn still can't do it.

**Comment by RElesgoe** [comment]
A converter script would be nice, it could be placed in the scripts directory in this repository. Just make a pull request for it.

**Comment by xpeh-owns** [comment]
I already made one :) This json is produced with a script with no edits after.

**Comment by xpeh-owns** [comment]
So how to upload them? Never had worked with git and github :)

**Comment by RElesgoe** [comment]
Just make another Gist and I'll upload it.

**Comment by xpeh-owns** [comment]
I'll probably have to commit something else in the future.

**Comment by RElesgoe** [comment]
Can you modify your script to output tabs instead of spaces.
Before ````"WAR3": [```` should be a single tab. Before ````"title"````, ````"architecture"````, etc. should be 2 tabs.

**Comment by RElesgoe** [comment]
@xpeh-owns  I need the file to be modified like so:
````
{  
    "WAR3":{  
        "0x1c":{  
            "checkrevision_file":"ver-IX86-1.mpq",
            "equation":"A=1239576727 C=1604096186 B=4198521212 4 A=A+S B=B-C C=C^A A=A+B",
            "entries":[  
                {  
                    "title":"Warcraft III - ROC 1.28.2.",
                    "architecture":"IX86",
                    "version":"1.28.2.227",
                    "hash":"0x2dc96bf5",
                    "file_metadata":"War3.exe 05/20/17 13:25:29 558568",
                    "versiontag":"WAR3_1282"
                },
                {  
                    "title":"Warcraft III - ROC 1.28.1.",
                    "architecture":"IX86",
                    "version":"1.28.1.197",
                    "hash":"0x1fbde0fd",
                    "file_metadata":"War3.exe 04/17/17 12:06:57 536040",
                    "versiontag":"WAR3_1281"
                },
                {  
                    "title":"Warcraft III - ROC 1.28",
                    "architecture":"IX86",
                    "version":"1.28.0.37",
                    "hash":"0xe00c3096",
                    "file_metadata":"War3.exe 04/17/17 12:06:57 536040",
                    "versiontag":"WAR3_128"
                }
            ]
        },
        "0x1b":{  
            "checkrevision_file":"ver-IX86-1.mpq",
            "equation":"B=454282227 C=2370009462 A=2264812340 4 A=A^S B=B-C C=C-A A=A+B",
            "entries":[  
                {  
                    "title":"Warcraft III - ROC 1.27b",
                    "architecture":"IX86",
                    "version":"1.27.1.173",
                    "hash":"0x4026b5b0",
                    "file_metadata":"War3.exe 12/09/16 06:05:09 515048",
                    "versiontag":"WAR3_127B"
                }
            ]
        }
    }
}
````

**Comment by RElesgoe** [comment]
New format:
````
{  
    "WAR3":{  
		"IX86":{  
			"0x1c":{  
				"checkrevision_file":"ver-IX86-1.mpq",
				"equation":"A=1239576727 C=1604096186 B=4198521212 4 A=A+S B=B-C C=C^A A=A+B",
				"entries":[  
					{  
						"title":"Warcraft III - ROC 1.28.2.",
						"version":"1.28.2.227",
						"hash":"0x2dc96bf5",
						"file_metadata":"War3.exe 05/20/17 13:25:29 558568",
						"versiontag":"WAR3_1282"
					},
					{
						"title":"Warcraft III - ROC 1.28.1.",
						"version":"1.28.1.197",
						"hash":"0x1fbde0fd",
						"file_metadata":"War3.exe 04/17/17 12:06:57 536040",
						"versiontag":"WAR3_1281"
					},
					{  
						"title":"Warcraft III - ROC 1.28",
						"version":"1.28.0.37",
						"hash":"0xe00c3096",
						"file_metadata":"War3.exe 04/17/17 12:06:57 536040",
						"versiontag":"WAR3_128"
					}
				]
			},
			"0x1b":{  
				"checkrevision_file":"ver-IX86-1.mpq",
				"equation":"B=454282227 C=2370009462 A=2264812340 4 A=A^S B=B-C C=C-A A=A+B",
				"entries":[  
					{  
						"title":"Warcraft III - ROC 1.27b",
						"version":"1.27.1.173",
						"hash":"0x4026b5b0",
						"file_metadata":"War3.exe 12/09/16 06:05:09 515048",
						"versiontag":"WAR3_127B"
					}
				]
			}
		},
		"XMAC":{
		}
    }
}
````

I considered moving `checkrevision_file` and `equation` under the architecture objects, but it would be too time consuming to go back and update every entry.

**Comment by RElesgoe** [comment]
74b06d022b0b61538590e8c30ec20830ebdd3c5c
