### ISSUE TITLE
Stable Release

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#337]
Reffering to the comment https://github.com/pvpgn/pvpgn-server/issues/181#issuecomment-361039954
I suggest to keep stable code in `master` branch, and create `develop` branch on github. Ideally with multiple `feature` branches for each feature which then could be merged with `develop`. But at least first two will be already very good.
A successful branching model is described on http://nvie.com/posts/a-successful-git-branching-model/

@RElesgoe actually we do not have a stable release now. Your current release is unstable and contains bugs. Instead of that I always suggest users to download automated nightly binaries from https://pvpgn.pro.
But many users still download it from Releases section on github and ask about the fixed bugs. For example this https://forums.pvpgn.pro/viewtopic.php?pid=9698#p9698

**Comment by RElesgoe** [comment]
@HarpyWar I would consider the nightly binaries unstable since they have the latest changes that aren't tested. We should still use the Releases, but decide which commit is stable enough to build on and release. I haven't had the time to regularly distribute binaries though.

**Comment by HarpyWar** [comment]
Therefore nightly binaries should be created from `develop` branch, and stable binaries - from `master`.
It's easier to start these branches from the next "stable" release.

**Comment by RElesgoe** [comment]
Created ````develop```` branch: https://github.com/pvpgn/pvpgn-server/tree/develop

**Comment by HarpyWar** [comment]
All commits from a branch are automatically added in related pull request like here https://github.com/pvpgn/pvpgn-server/pull/340
One of a reason why it's better to add long term features into a different branch.
