### ISSUE TITLE
Problem with Realm D2CS "sqlist_check_timeout"

### ISSUE THREAD

**Issue by filaname** [pvpgn/pvpgn-server#338]
I'm having a problem in **D2CS**, can someone point me a direction to solve?

### **D2CS.LOG**
![d2cs](https://user-images.githubusercontent.com/20021506/35770572-0e2eda50-0905-11e8-8c40-0ee77588a0df.png)

The symptom of this _"anomaly"_ is the blocking in the selection of chars.

![error_game](https://user-images.githubusercontent.com/20021506/35770567-f6158342-0904-11e8-9df7-a96256614b1c.jpg)

Players who are online on the server continue to play normally, only the players who want to connect have problems when selecting the character.

**NOTE**: I can only normalize by restarting the **D2CS** process

When I tried to use the **/rehash realms** command to reload the **D2CS**, the Realm is released for some connections and after 5 seconds, the error repeats again, blocking the selection of the characters.

and these errors occurred to me:

### **D2CS.LOG**
```
[error] net_listen: error bind listen socket
[error] server_listen: error listen socket
[error] d2cs_server_process: failed to setup listen socket
[error] main: failed to run server
```

My **PvPGN PRO** is the most update and I have used some previous versions of **PvPGN PRO(A few months ago)**, but the error continues. I already changed OS. I went through **Ubuntu 16.04 64-bit, Ubuntu 14.04 32-bit**, and I'm with **Debian 8 Jessie 64-bit**, where the same problem occurs.

When using **Ubuntu**, this error also appeared in the kernel. I do not know if there's anything to it.

### **Kernel Panic**

![kernel_panic](https://user-images.githubusercontent.com/20021506/35770583-370a2e02-0905-11e8-9cf4-c9aa4ce636bc.jpg)

Could someone help me with this?

**Comment by filaname** [comment]
Update: I am now using the **PvPGN PRO** Windows version running with **Wine** on **Debian 8 64-bit** OS.

I am using the same configuration in **PvPGN**, both in the Linux/Windowns version.

Apparently, the problem was in **PvPGN** for Linux, maybe something in the build, or in my OS.

So far working well, keep you informed..

**Comment by filaname** [comment]
dont work

**Comment by RElesgoe** [comment]
Turn on debug and trace error levels and then run PvPGN again. Post full logs.

**Comment by filaname** [comment]
@RElesgoe Where to turn on debugging in Linux?

Error logs are already active.

I just tested on the Windows system and it works fine for 3 days in a row.

So the problem is with the Linux operating system. The funny thing is that the problem started after restarting the machine. Before that, there was no problem.

Could it have been some service that did not start after reboot? Something related to connection jacks?

Because always close to 10.000 connections made, this error occurs and players can not connect to REALM.

I'm posting more information here to help others with the same problem.

**Comment by HarpyWar** [comment]
> Where to turn on debugging in Linux?

bnetd.conf, d2cs.conf
```
loglevels = fatal,error,warn,info,debug,trace
```

But this should be your system issue, not pvpgn. Looks like sqlist_check_timeout appear while kernel blocks the d2cs process, therefore all connections are dropped.

If you run d2cs on VDS then try another hosting provider.
[https://helpful.knobs-dials.com/index.php/INFO:_task_blocked_for_more_than_120_seconds.](https://helpful.knobs-dials.com/index.php/INFO:_task_blocked_for_more_than_120_seconds.)
