### ISSUE TITLE
PVPGN Crashes when player disconnects, WC3

### ISSUE THREAD

**Issue by basedchinchin** [pvpgn/pvpgn-server#339]
This could be a one off issue, or a known bug, but during a 1v1 game on W3, the other player disconnected as to signal a GG and a victory for me. When I left the game I found that I had no connection to my own BNet server. I checked the server application and the output log was littered with a repeating line posted here:

Feb 05 10:28:49 [info ] pvpgn::bnetd::handle_w3route_packet: [624] got username 'Kyle'
Feb 05 10:28:49 [info ] pvpgn::bnetd::conn_set_clienttag: [624] setting client type to "W3XP"
Feb 05 10:57:20 [info ] pvpgn::bnetd::conn_destroy: [624] closed w3route connection
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 8
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 9
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 10
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 11
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 12
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 13
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 14
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 15
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 16
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 17
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 18
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 19
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 20
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 21
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 22
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 23
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 24
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 25
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 26
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 27
Feb 05 10:57:21 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 28
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 29
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 30
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 31
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 32
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 33
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 34
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 35
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 36
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 37
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 38
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 39
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 40
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 41
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 42
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 43
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 44
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 45
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 46
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 47
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 48
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 49
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 50
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 51
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 52
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 53
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 54
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 55
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 56
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 57
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 58
Feb 05 10:57:22 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 59
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 60
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 61
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 62
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 63
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 64
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 65
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 66
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 67
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 68
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 69
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 70
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 71
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 72
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 73
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 74
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 75
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 76
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 77
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 78
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 79
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 80
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 81
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 82
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 83
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 84
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 85
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 86
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 87
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 88
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 89
Feb 05 10:57:23 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 90
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 91
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 92
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 93
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 94
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 95
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 96
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 97
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 98
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 99
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 100
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 101
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 102
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 103
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 104
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 105
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 106
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 107
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 108
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 109
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 110
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 111
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 112
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 113
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 114
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 115
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 116
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 117
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 118
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 119
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 120
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 121
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 122
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 123
Feb 05 10:57:24 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 124
Feb 05 10:57:25 [error] pvpgn::bnetd::anongame_get_player: invalid plnum: 125

After this final line the server suddenly crashed and closed. Is this a known bug? Or am I missing something?

Operating System is Windows Server 2012 R2 if that matters. And I am running 1.99.7.1 PRO

**Comment by RElesgoe** [comment]
I believe this is the same issue as #314. Try downloading PvPGN binaries from https://pvpgn.pro

**Comment by cen1** [comment]
Disconnect was not tested with that patch so it could be a new bug. Let us know.
