### ISSUE TITLE
Diablo 2 LOD 1.14d update

### ISSUE THREAD

**Issue by DevilOfIce** [pvpgn/pvpgn-server#341]
Hello
I write here hoping to get some help.
I have a server of Diablo 2 running on my pc(windows xp)
My problem is next on that pc i can run diablo 2 lod 1.13 and it wont update, so on that pc i can play as long i want no problems.
But when me or my friends try to connect from different pc (winxp / win7) game will autoupdate to 1.14d and it wont let us in server. 
Question is next how can i make it so that : 
A) Game wont update 1.13 to 1.14d 
Or 
B) How can i fix mybserver so it lets 1.14d game join my server.
Tnx for helping

![20180301_232102](https://user-images.githubusercontent.com/36893131/36870802-e47687e0-1da8-11e8-80f5-42b885c11fef.jpg)
![20180301_232011](https://user-images.githubusercontent.com/36893131/36870803-e4bd53aa-1da8-11e8-8101-6e89c8ff98aa.jpg)

**Comment by RElesgoe** [comment]
What commit/version of PvPGN are you running? Post logs with debug and trace levels enabled.

**Comment by DevilOfIce** [comment]
Pvpgnn bnetd mod 1.8.5

And i have no idea where i can find debugs list

**Comment by RElesgoe** [comment]
1.8.5 isn't supported here.
