### ISSUE TITLE
[CLOSED] PvPGN cannot be run on Windows 32 bit

### ISSUE THREAD

**Issue by Happin3ss** [pvpgn/pvpgn-server#343]
Currently I'm running PvPGN on Windows server 2003 SP 2 32 bit. The *.exe files always inform it is not a valid Win32 application. So I believed there are something wrong here because It should be run well on x86 system.
 It's still run well on my x64 server :)

SORRY MY MISTAKE. I SHOULD CHECK THAT THE MINIMUM OS SUPPORT IS WINDOWS SERVER 2008

**Comment by MineSAT** [comment]
I am running the server under ubuntu 16.04 x64 and it works correctly
