### ISSUE TITLE
PVPGN Diablo II 1.09D support

### ISSUE THREAD

**Issue by TurBoss** [pvpgn/pvpgn-server#346]
the readme doesn't show 1.09d support

I din't managed to get master to work with it

is there any plan to support it

Thanks

**Comment by RElesgoe** [comment]
Assuming you're talking about Diablo 2 and it's expansion, I don't know why PvPGN doesn't support it. It would help if you posted logs though.

**Comment by TurBoss** [comment]
yes yes sorry I was talking about Diablo II LOD :)



[d2cs.log](https://github.com/pvpgn/pvpgn-server/files/1957104/d2cs.log)
[bnetd.log](https://github.com/pvpgn/pvpgn-server/files/1957105/bnetd.log)

**Comment by RElesgoe** [comment]
The logs seem to be cut off

**Comment by TurBoss** [comment]
[bnetd.log](https://github.com/pvpgn/pvpgn-server/files/1957115/bnetd.log)
[d2cs.log](https://github.com/pvpgn/pvpgn-server/files/1957116/d2cs.log)

did some activity but can't do much more as I can't join games

what logs are relevant?

thanks

**Comment by RElesgoe** [comment]
Actually they don't seem cut off. But I don't see an attempt from a D2 client to connect.

**Comment by TurBoss** [comment]
[d2dbs-gs.log](https://github.com/pvpgn/pvpgn-server/files/1957121/d2dbs-gs.log)
forgot  this one

**Comment by TurBoss** [comment]
[bnetd.log](https://github.com/pvpgn/pvpgn-server/files/1957132/bnetd.log)
[d2cs.log](https://github.com/pvpgn/pvpgn-server/files/1957133/d2cs.log)
[d2dbs-gs.log](https://github.com/pvpgn/pvpgn-server/files/1957134/d2dbs-gs.log)
[d2dbs.log](https://github.com/pvpgn/pvpgn-server/files/1957135/d2dbs.log)


I'm sorry for the confusison I could caused
this are the fresh install logs

Thank you

**Comment by RElesgoe** [comment]
I see that a D2 client was able to successfully connect and log in. I don't see any problem on PvPGN's end.

**Comment by TurBoss** [comment]
so this is more a D2GS related stuff

ok I'm closing this thank  you so much
