### ISSUE TITLE
Show games with password to admins

### ISSUE THREAD

**Issue by Kelly32** [pvpgn/pvpgn-server#353]
By default pvpgn can hide/display games with password using this setting in bnetd.conf 
>hide_pass_games = true

The bug here is that even if the setting is set to `true` normal players can still see passworded games that that shouldn't happen as the option is enabled. Can we have so that only admins (maybe certain cg) can see the full list of games normal players the public games? This is mainly important for games like warcraft and diablo games.

**Comment by RElesgoe** [comment]
How is this important for WarCraft and Diablo games?

**Comment by Kelly32** [comment]
@RElesgoe, for example in diablo games you dont want players to see private games created by other players but only public games and you want for admins to see them and check all games list if anyone is cheating. Cheating with a bot for example will create private games one after another with increasing number and it's easy to track if you are able to see full games list.

**Comment by Kelly32** [comment]
@HarpyWar, maybe a lua command can be added for this?

**Comment by HarpyWar** [comment]
It's possible to override returned game list from Lua in `handle_game.lua` > `function handle_game_list(account)` 

Example code which returns only games with passwords for admins, edit it to your needs:
```Lua
local gamelist = {}
-- is admin account
local is_admin = account_get_auth_admin(account.name, nil)

if (is_admin) then
	-- get server games
	local glist = server_get_games()
	-- iterate games
	for i,game in pairs(glist) do
		-- if game password is not empty
		if not string:empty(game.pass) then
			-- then add to games
			table.insert(gamelist, game.id)
			table.insert(gamelist, game.name)
			return {"id", "name"}, gamelist
		end
	end
end
-- return new gamelist
return gamelist
```

[Game object properties](https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/luaobjects.cpp#L179-L241)
[Account object properties](https://github.com/pvpgn/pvpgn-server/blob/master/src/bnetd/luaobjects.cpp#L107-L148)

**Comment by Kelly32** [comment]
Thanks @HarpyWar. Do I need to replace the entire function or can I keep war3xp one too? I see current function is related to ghost for warcraft. Also can you make it please so it returns all games with pass for certain command group only instead of all admins? So only admins with certain cg that I choose can see that.

**Comment by HarpyWar** [comment]
This requires testing, so I can't do it now.
Example of reading command groups of account https://github.com/pvpgn/pvpgn-server/blob/master/lua/handle_command.lua#L49
You can keep code for ghost or just remove it if you don't plan to use it. Anyway it should be disabled from `config.lua`.

You can debug and finish the script by yourself with `/rehash lua` and `DEBUG("text")` inside Lua scripts to display veriable values and any text in main server log. 
Also you can see script errors in logs with a line number if something wrong. It's impossible to crash a server from Lua.

**Comment by Kelly32** [comment]
I'm not good with lua so whenever you have time I would appreciate if you can take a look and make so cg flag can be used instead of all admins, only when you have time. Will test the command today anyway to see if all works good. Thanks again, helpful as always.

**Comment by RElesgoe** [comment]
Have you tried using the `/games all` command? I'm not entirely sure if it shows passworded games though. Let me know if it doesn't.

**Comment by Kelly32** [comment]
@RElesgoe I am testing now and used `/games all` command and seems it shows all games including passworded games to normal players too so this is not good. `hide_pass_games = true` is set inside bnetd.conf yet any player can see password games too.

@HarpyWar, I replaced the lua function. When using `/games` I can only see public games, when using `/games all` I can see all games including passworded but non-admins can see those too.

**Comment by Kelly32** [comment]
This will block the command for all normal players though and they should be allowed to see normal games. Something seems to be broken with `hide_pass_games = true` when using `/games all` in pro because in pvpgn this should block password games from being displayed.

**Comment by RElesgoe** [comment]
I don't think the `/game all` command takes into account of the `hide_pass_games` option, but that needs to be fixed some day. The `/games` command is unnecessary for normal users since they could still view the game list as they usually do, so that's why restricting the `/games` command to certain command groups can be a workaround to your problem.

**Comment by Kelly32** [comment]
@RElesgoe, how about setting `/games all` as separate command and have different cg? This will solve the problems because players can still use `/games` and see public and admins have `/games all` to see all the games. Command `/games` it is necessary for normal users for games like diablo because full games do not appear in the game list at 8/8 players anymore and for farm games it's important to have that.

**Comment by Kelly32** [comment]
@RElesgoe, maybe if you only give a certain command group number the permission it won't be as overkill? Let's say only those with cg 3 can see and if we need to change that we only modify that file in source. Either way I bet many will love this new commit and thank you for being so fast, will test this as soon as I get to pc.

**Comment by RElesgoe** [comment]
It's pretty arbitrary and inconsistent to restrict this specific command and parameter to a specific command group. If you still want this feature, you would have to implement it yourself.

**Comment by Kelly32** [comment]
@RElesgoe, I just tested the new commit on the release source that I use and works perfect, thanks a lot for that. Yes, maybe giving specific cg is personal preference because I would prefer not to give someone `/admin +username` for that alone so in this case cg makes more sense. Could you maybe point me to what I need to edit to achieve this goal?

**Comment by RElesgoe** [comment]
You'll want to modify the `_glist_cb()` function in `src/bnetd/command.cpp` and add a check for the command group of the account belonging to `cbdata->c`.

**Comment by RElesgoe** [comment]
You should replace 
`else if (cbdata->tag == 0 && account_get_auth_admin(conn_get_account(cbdata->c), nullptr) != 1)`
with 
`else if (cbdata->tag == 0 && !(account_get_command_groups(conn_get_account(cbdata->c)) & 1 << (3 - 1)))`

**Comment by Kelly32** [comment]
Thanks a lot, much appreciated. The setting in `bnetd.conf` works correctly now too, you guys were so fast.
