### ISSUE TITLE
[error] _client_changegameport:

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#359]
![image png 4e8589a78c8f06fedd4c8f7063a83353](https://user-images.githubusercontent.com/6318282/41373964-31003d5c-6f95-11e8-947f-d0c4e6c42063.png)
@HarpyWar Здравствуйте. После игры на боте у игроков разрывает соединение с battle.net. В логах следующее:

> Jun 13 22:11:50 [error] _client_changegameport: [41] invalid port in changegameport packet: 2
> Jun 13 22:11:50 [error] handle_bnet_packet: [41] (logged in) got error handling packet type 0x45ff, len 6
> Jun 13 22:16:13 [error] game_set_status: attempting to set status 'open' (2) to started game
> Jun 13 22:19:17 [error] game_set_status: attempting to set status 'open' (2) to started game
> Jun 13 22:23:28 [error] game_set_status: attempting to set status 'open' (2) to started game
> Jun 13 22:25:23 [error] game_set_status: attempting to set status 'open' (2) to started game
> Jun 13 22:25:52 [error] game_set_status: attempting to set status 'open' (2) to started game
> Jun 13 22:34:43 [error] game_set_status: attempting to set status 'open' (2) to started game
> Jun 13 22:35:22 [error] game_set_status: attempting to set status 'open' (2) to started game

Как фиксить?

**Comment by TemKaSD** [comment]
@HarpyWar Пожалуйста, помогите. У меня нет знаний в английском языке, я не могу на нем корректно задать свой вопрос.

https://wc3.games/forums/topic/33-mozhno-li/?do=findComment&comment=199

**Comment by HarpyWar** [comment]
1) У меня нет достаточного опыта в хостинге бота чтобы понять в чем проблема.
2) Поскольку проблема проявляется на боте, то скорее всего, она и находится именно на боте, но не pvpgn. Чтобы утверждать обратное, сперва проверьте на каких версиях сервера это происходит. Например, на 1.8.5 и на старой 1.99. 
Далее с этим стоит обратиться к разработчикам бота, чтобы они подтвердили что проблема находится именно на pvpgn. От этого можно будет отталкиваться.

**Comment by TemKaSD** [comment]
@HarpyWar Я всё понимаю, я не готов утверждать из-за бота это или нет. Помогите проанализировать логи тогда, где найти строку этого разъединения чтобы узнать что за ошибка. Проявление следующее:

Человек играет от получаса на боте, после завершения игры на боте его выкидывает на канал и там пишет вот это сообщение. Мои боты на серверах Garena, Rubattle, Iccup и мой сервер, такое проявляется только на моем сервере больше нигде.

Версия моего pvpgn последняя, качал две недели назад. Я понимаю что вы не будете смотреть лог который я прикрепил, ну а в друг. Это выборка лога с той минуты когда человек на боте начал игру ( бот стартанул, карта zombie666 ) и когда он завершил игру и его дропнуло с сервера.

[pvpgn.txt](https://github.com/pvpgn/pvpgn-server/files/2242082/pvpgn.txt)

**Comment by HarpyWar** [comment]
В этом логе нет ни соединений, ни разъединений игроков. Если лог обрезан, то так делать не нужно, если хотите чтобы его проанализировали.
Не указан ник игрока, который был разъединен.
Не указано разъединяются ли от pvpgn все игроки одной и той же игры, или только некоторые. Всегда или только по истечении 30 минут.
Можно ли это повторить с первого раза, или разъединения происходят случайно. Если можно проверить с первого раза, то как я уже писал выше, стоит это проверить на предыдущих версиях pvpgn.

Если бот находится на той же машине, что и pvpgn, то стоит попробовать запустить бота на отдельной. В этом случае, так как разъединения только с вашего сервера, есть предположение, что бот посылает игрокам какой-то пакет, на который клиент игры реагирует как на пакет от pvpgn, и помимо отключения от игры так же отключает и от pvpgn.
