### ISSUE TITLE
Suggestion - WCIII: RoC Battle.net Beta Support

### ISSUE THREAD

**Issue by yuiop213** [pvpgn/pvpgn-server#360]
Hello, can you please add support for WCIII: RoC Battle.net Beta?
You find information about it here: http://www.blizzardarchive.com/pub/index.php?id=roc
The reason is because the game is unplayable (without using terrible AI mods) since it was built for multiplayer only and the original servers are long since dead.
Also, there were previously two private server projects for it called Warforge and Wargasm (which were both FOSS I think), but they did not support the latest beta patches and the respective original files are difficult to source.

**Comment by yuiop213** [comment]
Also the TFT expansion beta is multiplayer only and has dead servers as well, however the differences between beta and the final game aren't as stark as between the RoC beta and retail versions.
Information on it here: http://www.blizzardarchive.com/pub/index.php?id=tft

**Comment by RElesgoe** [comment]
I believe that WC3 beta support (from another project) is the reason why Blizzard took down bnetd, so I will avoid this. Secondly, I think the communication between WC3 beta and the server isn't documented, so it would require research that no one is willing to do.
