### ISSUE TITLE
Unable to reach berlios.de

### ISSUE THREAD

**Issue by iforgotthequestion** [pvpgn/pvpgn-server#363]
Currently installing pvpgn on Linux 16.04.  Finished install process and attempting to run with `bnetd` command. Checking with the `service` command, I can see that pvpgn has started and crashed/failed.  Calling `service pvpgn status`, yields: 

> Jul 26 11:41:58 apollo systemd[1]: Starting LSB: Gaming server that emulates Battle.net(R)...
> Jul 26 11:41:58 apollo pvpgn[8537]: You are missing the pvpgn support files and daemon will not start without them.
> Jul 26 11:41:58 apollo pvpgn[8537]: Run 'sudo pvpgn-support-installer' or read /usr/share/doc/pvpgn/README.Debian
> Jul 26 11:41:58 apollo systemd[1]: Started LSB: Gaming server that emulates Battle.net(R).
> Jul 26 11:47:55 apollo systemd[1]: Stopping LSB: Gaming server that emulates Battle.net(R)...
> Jul 26 11:47:55 apollo pvpgn[10780]: Stopping bnetd daemon: bnetd.
> Jul 26 11:47:55 apollo systemd[1]: Stopped LSB: Gaming server that emulates Battle.net(R).

Running `sudo pvpgn-support-installer' yields:

> Creating temporary working directory...
> Placing the archive in the temporary directory...
> --2018-07-26 12:00:16--  http://download.berlios.de/pvpgn/pvpgn-support-1.2.tar.gz
> Resolving download.berlios.de (download.berlios.de)... failed: Name or service not known.
> wget: unable to resolve host address ‘download.berlios.de’

Clearly the host (berlios.de) is unavailable/not responding.  Is there an alternate location to get this files from?

**Comment by HarpyWar** [comment]
Support files were separated from server files in 1.8.5 and 1.99, but now they are included in the repository and release archive, you can find them in `files` directory:
```
bnserver-D2DV.ini
bnserver-D2XP.ini
bnserver-WAR3.ini
bnserver.ini
icons-WAR3.bni
icons.bni
icons_STAR.bni
IX86ver1.mpq
PMACver1.mpq
XMACver1.mpq
ver-ix86-1.mpq
```

How did you install pvpgn, that you have not these files?

**Comment by iforgotthequestion** [comment]
Installed from Linux instructions at https://pvpgn.pro/pvpgn_installation.html.  This was probably my error to install it from here rather than the Github source. I'll look into patching my current install and/or wiping and reinstalling in the next couple days and update this thread.

**Comment by cen1** [comment]
I believe this was answered sufficiently, all support files can be downloaded from this repo. Closing.
