### ISSUE TITLE
PvPGN изменяет пароль только после перезагрузки

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#364]
@HarpyWar Здравствуйте. Сделал регистрацию на баттле нет через свой сайт, всё в порядке. Сделал смену пароля, новый пароль работает только после перезагрузки PvPGN. Что-то можно с этим сделать?

**Comment by HarpyWar** [comment]
Использовать бота, который будет соединяться через telnet и выполнять команду /set BNET\\acct\\passhash1 на обновление хеша пароля. Через /set обновление любых полей БД происходит сразу же, без необходимости перезагрузки.
https://forums.pvpgn.pro/viewtopic.php?pid=9444#p9444

P.S. Не нужно обращаться здесь на русском, и тем более лично ко мне. Для этого есть форум, где могут ответить на русском, и не только я.
