### ISSUE TITLE
sql_load_teams: error query db

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#373]
[error] sql_load_teams: error query db (query:"SELECT teamid, size, clienttag, lastgame, member1, member2, member3, member4, wins,losses, xp, level, rank FROM pvpgn_arrangedteam WHERE teamid > 0")
![screenshot_2](https://user-images.githubusercontent.com/6318282/51410733-37276200-1bb1-11e9-98b6-1c56963d3187.png)

no colum rank:
![screenshot_3](https://user-images.githubusercontent.com/6318282/51410778-4f977c80-1bb1-11e9-961d-ecbcb61d4ead.png)

**Comment by HarpyWar** [comment]
By a reason you have not it, so just add it manually.
This column should be created on first start in empty database https://github.com/pvpgn/pvpgn-server/blob/master/conf/sql_DB_layout.conf.in#L186
