### ISSUE TITLE
I use it in CentOS ,and can not "make" through successful

### ISSUE THREAD

**Issue by woodgreat** [pvpgn/pvpgn-server#374]
I wanna build a free starcraft I server on a CentOS server (7.2) , I follow the tips the site wrote , and I know it for Debian like linux , but I use the method it may good for . after 1 Day try , I give up , so what's the real way to open ? thanks.

**Comment by cen1** [comment]
There are instructions for Centos 7 in the readme. Tried those?

**Comment by woodgreat** [comment]
> There are instructions for Centos 7 in the readme. Tried those?

It done ! thanks , and I completed the info of CentOS7 part and submit pull request.

by the way, Do you know how to stop the "bnetd" ? like "service bnetd stop",thanks all the same "_"

**Comment by cen1** [comment]
`pkill bnetd`or `ps aux |grep bnetd` followed by `kill <pid>` or you can run it in `screen`

**Comment by woodgreat** [comment]
Thanks buddy, I got it ,I just give a tips that make it more standard . A new question here ,is "When I create new test account entered starcraft Lobby( the Hall) the little image which left side the name is shown'n00b', I want change it ,but can't ,and I want change it after create the account at once If it could ?" ,So where is the image "n00b" location I can't find it .
