### ISSUE TITLE
The left side the name is shown'n00b', I want change it ,but can't 

### ISSUE THREAD

**Issue by woodgreat** [pvpgn/pvpgn-server#376]
I got it ,I just give a tips that make it more standard . A new question here ,is "When I create new test account entered starcraft Lobby( the Hall) the little image which left side the name is shown'n00b', I want change it ,but can't ,and I want change it after create the account at once If it could ?" ,So where is the image "n00b" location I can't find it .

**Comment by HarpyWar** [comment]
`files/icons.bni`
https://github.com/pvpgn/bni-icon-builder

**Comment by woodgreat** [comment]
thank you ,the "n00b" is noob is signed , I know !
