### ISSUE TITLE
Ports issue

### ISSUE THREAD

**Issue by styla01** [pvpgn/pvpgn-server#383]
Hello,

I try to install into virtual server with ubuntu 18.
but i cant solve the ports errors, here are some of my attemps http://prntscr.com/ock43y
please any hint to fix it...

In ubuntu I run the ghostbot + mysql DB and works fine.

LE Print with port http://prntscr.com/ockx8g

**Comment by cen1** [comment]
It looks as if you are running a pvpgn instance already (can't bind to port 6112). Check running processes and kill all pvpgn instances, then try again. If port still can't bind check which process is using port 6112.
```
netstat -tulpn |grep 6112
```

**Comment by styla01** [comment]
You are right. i thought if i got fatall error there was a exit too.
Thanks cen!
