### ISSUE TITLE
Ubuntu 18.04 compile error

### ISSUE THREAD

**Issue by iceyman** [pvpgn/pvpgn-server#384]
:~$ cd pvpgn-server && cmake -G "Unix Makefiles" -H./ -B./build
-- The CXX compiler identification is Clang 6.0.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- pvpgn is used as APPLICATION_NAME
-- The C compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so
-- Looking for gethostbyname in nsl
-- Looking for gethostbyname in nsl - found
-- Looking for socket in socket
-- Looking for socket in socket - not found
-- Looking for inet_aton in resolv
-- Looking for inet_aton in resolv - found
-- Looking for __inet_aton in bind
-- Looking for __inet_aton in bind - not found
-- Checking POSIX headers
-- Looking for C++ include arpa/inet.h
-- Looking for C++ include arpa/inet.h - found
-- Looking for C++ include dirent.h
-- Looking for C++ include dirent.h - found
-- Looking for C++ include grp.h
-- Looking for C++ include grp.h - found
-- Looking for C++ include fcntl.h
-- Looking for C++ include fcntl.h - found
-- Looking for C++ include netdb.h
-- Looking for C++ include netdb.h - found
-- Looking for C++ include netinet/in.h
-- Looking for C++ include netinet/in.h - found
-- Looking for C++ include poll.h
-- Looking for C++ include poll.h - found
-- Looking for C++ include pwd.h
-- Looking for C++ include pwd.h - found
-- Looking for C++ include sys/mman.h
-- Looking for C++ include sys/mman.h - found
-- Looking for C++ include sys/resource.h
-- Looking for C++ include sys/resource.h - found
-- Looking for C++ include sys/select.h
-- Looking for C++ include sys/select.h - found
-- Looking for C++ include sys/socket.h
-- Looking for C++ include sys/socket.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include sys/time.h
-- Looking for C++ include sys/time.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/utsname.h
-- Looking for C++ include sys/utsname.h - found
-- Looking for C++ include sys/wait.h
-- Looking for C++ include sys/wait.h - found
-- Looking for C++ include termios.h
-- Looking for C++ include termios.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Checking optional POSIX/required SUS headers
-- Looking for C++ include sys/timeb.h
-- Looking for C++ include sys/timeb.h - found
-- Checking FreeBSD-based headers
-- Looking for include files sys/types.h, sys/event.h
-- Looking for include files sys/types.h, sys/event.h - not found
-- Looking for C++ include sys/param.h
-- Looking for C++ include sys/param.h - found
-- Checking BSD headers
-- Looking for C++ include sys/file.h
-- Looking for C++ include sys/file.h - found
-- Checking Linux headers
-- Looking for C++ include sys/epoll.h
-- Looking for C++ include sys/epoll.h - found
-- Checking Win32 headers
-- Looking for C++ include windows.h
-- Looking for C++ include windows.h - not found
-- Looking for C++ include winsock2.h
-- Looking for C++ include winsock2.h - not found
-- Looking for C++ include ws2tcpip.h
-- Looking for C++ include ws2tcpip.h - not found
-- Looking for C++ include process.h
-- Looking for C++ include process.h - not found
-- Checking other headers
-- Looking for C++ include dir.h
-- Looking for C++ include dir.h - not found
-- Looking for C++ include direct.h
-- Looking for C++ include direct.h - not found
-- Looking for C++ include ndir.h
-- Looking for C++ include ndir.h - not found
-- Looking for C++ include sys/dir.h
-- Looking for C++ include sys/dir.h - found
-- Looking for C++ include sys/ndir.h
-- Looking for C++ include sys/ndir.h - not found
-- Looking for C++ include sys/poll.h
-- Looking for C++ include sys/poll.h - found
-- Looking for chdir
-- Looking for chdir - found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Looking for fork
-- Looking for fork - found
-- Looking for ftime
-- Looking for ftime - found
-- Looking for getgid
-- Looking for getgid - found
-- Looking for getgrnam
-- Looking for getgrnam - found
-- Looking for getlogin
-- Looking for getlogin - found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for getpwnam
-- Looking for getpwnam - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getuid
-- Looking for getuid - found
-- Looking for ioctl
-- Looking for ioctl - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for _mkdir
-- Looking for _mkdir - not found
-- Looking for mkdir
-- Looking for mkdir - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for pipe
-- Looking for pipe - found
-- Looking for poll
-- Looking for poll - found
-- Looking for setitimer
-- Looking for setitimer - found
-- Looking for setpgid
-- Looking for setpgid - found
-- Looking for setpgrp
-- Looking for setpgrp - found
-- Looking for setsid
-- Looking for setsid - found
-- Looking for setuid
-- Looking for setuid - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sigaddset
-- Looking for sigaddset - found
-- Looking for sigprocmask
-- Looking for sigprocmask - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for uname
-- Looking for uname - found
-- Looking for wait
-- Looking for wait - found
-- Looking for waitpid
-- Looking for waitpid - found
-- Performing Test HAVE_MAKE_UNIQUE
-- Performing Test HAVE_MAKE_UNIQUE - Success
-- Looking for gethostname
-- Looking for gethostname - found
-- Looking for select
-- Looking for select - found
-- Looking for socket
-- Looking for socket - found
-- Looking for recv
-- Looking for recv - found
-- Looking for send
-- Looking for send - found
-- Looking for recvfrom
-- Looking for recvfrom - found
-- Looking for sendto
-- Looking for sendto - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for getservbyname
-- Looking for getservbyname - found
-- Checking for single argument mkdir MKDIR_TAKES_ONE_ARG
-- Checking for single argument mkdir MKDIR_TAKES_ONE_ARG - not found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/#####/pvpgn-server/build
#####@game#####:~/pvpgn-server$ cd build && make
Scanning dependencies of target compat
[  1%] Building CXX object src/compat/CMakeFiles/compat.dir/gettimeofday.cpp.o
[  1%] Building CXX object src/compat/CMakeFiles/compat.dir/mmap.cpp.o
[  2%] Building CXX object src/compat/CMakeFiles/compat.dir/pdir.cpp.o
In file included from /home/#####/pvpgn-server/src/compat/pdir.cpp:20:
/home/#####/pvpgn-server/src/compat/pdir.h:21:10: fatal error: 'string' file not
      found
#include <string>
         ^~~~~~~~
1 error generated.
src/compat/CMakeFiles/compat.dir/build.make:110: recipe for target 'src/compat/C                                                                                                                                                             MakeFiles/compat.dir/pdir.cpp.o' failed
make[2]: *** [src/compat/CMakeFiles/compat.dir/pdir.cpp.o] Error 1
CMakeFiles/Makefile2:251: recipe for target 'src/compat/CMakeFiles/compat.dir/al                                                                                                                                                             l' failed
make[1]: *** [src/compat/CMakeFiles/compat.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cen1** [comment]
Weird, I'll check it otu later today.

**Comment by styla01** [comment]
i had similar issues, i used 'sudo' and fixed
https://github.com/pvpgn/pvpgn-server/issues/349

**Comment by cen1** [comment]
@iceyman I spun up a fresh 18.04 vm and it compiles no problem. Have you followed instructions for Ubuntu 16.04 in README?

**Comment by cen1** [comment]
Trying to convince clang to use libstdc++ or libc++ to no avail on 18.04. I'll just blame it on faulty ubuntu packaging. Let me know if you succeeded with gcc.

**Comment by rawbitt** [comment]
I'm having the same error on Ubuntu 18.04. 

> i had similar issues, i used 'sudo' and fixed 
> #349

`sudo` doesn't help (the error you reference here looks different)

Anyone have any suggestions for what to try here? Maybe a package-version issue?

**Comment by cen1** [comment]
@rawbitt did you try with gcc?

**Comment by rawbitt** [comment]
@cen1 cmake is new to me, can you give me the build commands for gcc (after git clone)? Just want to me sure I'm doing it right.

**Comment by cen1** [comment]
The original poster had problems because he used clang compiler but if you follow ubuntu compile instructions it should detect gcc by default. Can you paste your CMake generator log and make build log to see what your problem is?

**Comment by rawbitt** [comment]
> cd pvpgn-server && cmake -G "Unix Makefiles" -H./ -B./build
```
-- The CXX compiler identification is Clang 6.0.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- pvpgn is used as APPLICATION_NAME
-- The C compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so
-- Looking for gethostbyname in nsl
-- Looking for gethostbyname in nsl - found
-- Looking for socket in socket
-- Looking for socket in socket - not found
-- Looking for inet_aton in resolv
-- Looking for inet_aton in resolv - found
-- Looking for __inet_aton in bind
-- Looking for __inet_aton in bind - not found
-- Checking POSIX headers
-- Looking for C++ include arpa/inet.h
-- Looking for C++ include arpa/inet.h - found
-- Looking for C++ include dirent.h
-- Looking for C++ include dirent.h - found
-- Looking for C++ include grp.h
-- Looking for C++ include grp.h - found
-- Looking for C++ include fcntl.h
-- Looking for C++ include fcntl.h - found
-- Looking for C++ include netdb.h
-- Looking for C++ include netdb.h - found
-- Looking for C++ include netinet/in.h
-- Looking for C++ include netinet/in.h - found
-- Looking for C++ include poll.h
-- Looking for C++ include poll.h - found
-- Looking for C++ include pwd.h
-- Looking for C++ include pwd.h - found
-- Looking for C++ include sys/mman.h
-- Looking for C++ include sys/mman.h - found
-- Looking for C++ include sys/resource.h
-- Looking for C++ include sys/resource.h - found
-- Looking for C++ include sys/select.h
-- Looking for C++ include sys/select.h - found
-- Looking for C++ include sys/socket.h
-- Looking for C++ include sys/socket.h - found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - found
-- Looking for C++ include sys/time.h
-- Looking for C++ include sys/time.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include sys/utsname.h
-- Looking for C++ include sys/utsname.h - found
-- Looking for C++ include sys/wait.h
-- Looking for C++ include sys/wait.h - found
-- Looking for C++ include termios.h
-- Looking for C++ include termios.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Checking optional POSIX/required SUS headers
-- Looking for C++ include sys/timeb.h
-- Looking for C++ include sys/timeb.h - found
-- Checking FreeBSD-based headers
-- Looking for include files sys/types.h, sys/event.h
-- Looking for include files sys/types.h, sys/event.h - not found
-- Looking for C++ include sys/param.h
-- Looking for C++ include sys/param.h - found
-- Checking BSD headers
-- Looking for C++ include sys/file.h
-- Looking for C++ include sys/file.h - found
-- Checking Linux headers
-- Looking for C++ include sys/epoll.h
-- Looking for C++ include sys/epoll.h - found
-- Checking Win32 headers
-- Looking for C++ include windows.h
-- Looking for C++ include windows.h - not found
-- Looking for C++ include winsock2.h
-- Looking for C++ include winsock2.h - not found
-- Looking for C++ include ws2tcpip.h
-- Looking for C++ include ws2tcpip.h - not found
-- Looking for C++ include process.h
-- Looking for C++ include process.h - not found
-- Checking other headers
-- Looking for C++ include dir.h
-- Looking for C++ include dir.h - not found
-- Looking for C++ include direct.h
-- Looking for C++ include direct.h - not found
-- Looking for C++ include ndir.h
-- Looking for C++ include ndir.h - not found
-- Looking for C++ include sys/dir.h
-- Looking for C++ include sys/dir.h - found
-- Looking for C++ include sys/ndir.h
-- Looking for C++ include sys/ndir.h - not found
-- Looking for C++ include sys/poll.h
-- Looking for C++ include sys/poll.h - found
-- Looking for chdir
-- Looking for chdir - found
-- Looking for epoll_create
-- Looking for epoll_create - found
-- Looking for fork
-- Looking for fork - found
-- Looking for ftime
-- Looking for ftime - found
-- Looking for getgid
-- Looking for getgid - found
-- Looking for getgrnam
-- Looking for getgrnam - found
-- Looking for getlogin
-- Looking for getlogin - found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for getpwnam
-- Looking for getpwnam - found
-- Looking for getrlimit
-- Looking for getrlimit - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getuid
-- Looking for getuid - found
-- Looking for ioctl
-- Looking for ioctl - found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for _mkdir
-- Looking for _mkdir - not found
-- Looking for mkdir
-- Looking for mkdir - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for pipe
-- Looking for pipe - found
-- Looking for poll
-- Looking for poll - found
-- Looking for setitimer
-- Looking for setitimer - found
-- Looking for setpgid
-- Looking for setpgid - found
-- Looking for setpgrp
-- Looking for setpgrp - found
-- Looking for setsid
-- Looking for setsid - found
-- Looking for setuid
-- Looking for setuid - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sigaddset
-- Looking for sigaddset - found
-- Looking for sigprocmask
-- Looking for sigprocmask - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for uname
-- Looking for uname - found
-- Looking for wait
-- Looking for wait - found
-- Looking for waitpid
-- Looking for waitpid - found
-- Performing Test HAVE_MAKE_UNIQUE
-- Performing Test HAVE_MAKE_UNIQUE - Success
-- Looking for gethostname
-- Looking for gethostname - found
-- Looking for select
-- Looking for select - found
-- Looking for socket
-- Looking for socket - found
-- Looking for recv
-- Looking for recv - found
-- Looking for send
-- Looking for send - found
-- Looking for recvfrom
-- Looking for recvfrom - found
-- Looking for sendto
-- Looking for sendto - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for getservbyname
-- Looking for getservbyname - found
-- Checking for single argument mkdir MKDIR_TAKES_ONE_ARG
-- Checking for single argument mkdir MKDIR_TAKES_ONE_ARG - not found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pvpgn/pvpgn-server/build
```
> cd build && make
```
Scanning dependencies of target compat
[  1%] Building CXX object src/compat/CMakeFiles/compat.dir/gettimeofday.cpp.o
[  1%] Building CXX object src/compat/CMakeFiles/compat.dir/mmap.cpp.o
[  2%] Building CXX object src/compat/CMakeFiles/compat.dir/pdir.cpp.o
In file included from /home/pvpgn/pvpgn-server/src/compat/pdir.cpp:20:
/home/pvpgn/pvpgn-server/src/compat/pdir.h:21:10: fatal error: 'string' file not
      found
#include <string>
         ^~~~~~~~
1 error generated.
src/compat/CMakeFiles/compat.dir/build.make:110: recipe for target 'src/compat/CMakeFiles/compat.dir/pdir.cpp.o' failed
make[2]: *** [src/compat/CMakeFiles/compat.dir/pdir.cpp.o] Error 1
CMakeFiles/Makefile2:251: recipe for target 'src/compat/CMakeFiles/compat.dir/all' failed
make[1]: *** [src/compat/CMakeFiles/compat.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by rawbitt** [comment]
I wasn't entirely familiar with cmake choosing clang or gcc, so I found this on google:
`-DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++`

Looks to be building ... will confirm shortly.
