### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by frizar** [pvpgn/pvpgn-server#386]
> 1) Replace all a.a.a.a, b.b.b.b, c.c.c.c, d.d.d.d → x.x.x.x, **and forward ports 6112 and 4000 on a router to this local IP**.

How to do it right?
![image](https://user-images.githubusercontent.com/8735701/62006484-b3df5e00-b149-11e9-9680-9fe886b3409b.png)

I have this config, is this correct?

**Comment by cen1** [comment]
Looks good to me.

**Comment by frizar** [comment]
I can connect to my server by local IP, but my friend can not connect to me by my public IP. I check ports and they closed.
![image](https://user-images.githubusercontent.com/8735701/62007642-b39a8f00-b158-11e9-87da-5a75d067af2a.png)

**Comment by frizar** [comment]
nvm... Window Firewall problem

**Comment by frizar** [comment]
![image](https://user-images.githubusercontent.com/8735701/62008859-923da100-b160-11e9-9fec-39434720973d.png)

I cant create a game :(

**Comment by cen1** [comment]
Have you configured address translation? I don't know much about d2 but it seems like it's needed https://github.com/pvpgn/pvpgn-server/blob/master/conf/address_translation.conf.in
