### ISSUE TITLE
Cannot join custom game or normal game with message "the game you attempted to join could not be found"

### ISSUE THREAD

**Issue by aperture147** [pvpgn/pvpgn-server#395]
I'm running on ubuntu and forwarded port 6112 to 6119. The game appear on the custom game list but cannot join with message "the game you attempted to join could not be found"

**Comment by cen1** [comment]
After you host the game double check whether your host is actually accessible (to check if port forwarding is OK) either with telnet from external client or for example https://www.canyouseeme.org/ (IP is your host IP, not the pvpgn server ip)

**Comment by aperture147** [comment]
I also tried on the official server.pvpgn.pro server but this problem still persist. Found the game but couldn’t join in. Is there any config which I need to do on the client machine? My client is running the latest windows 10.

**Comment by cen1** [comment]
I am not sure I understand. If you host the game manually then by definition you are already in the game lobby. Do you use another PC to host the game? What game did you find on pvpgn.pro server, just some random game?

**Comment by aperture147** [comment]
I'm having this problem:
https://www.linuxquestions.org/questions/linux-software-2/can%27t-join-games-on-pvpgn-4175497465/
I tried forwarding the port in the router and it works, but isn't that mean I have to manually forward the port on any router where I want to host the game? Is there any workaround for this problem?

**Comment by cen1** [comment]
Yes, that is exactly what it means. The workaround is to use a dedicated hosting bot which you put on some server and it hosts games for you, see for example https://github.com/uakfdotb/ghostpp

**Comment by aperture147** [comment]
Thanks! That’s exactly what I want!
