### ISSUE TITLE
Raspberry Pi Compatible?

### ISSUE THREAD

**Issue by WandeingLagomorph793** [pvpgn/pvpgn-server#402]
Figure I'd check here, but is it possible to run a server with this program using a Raspberry Pi?

**Comment by cen1** [comment]
It should in theory but I would be surprised if it builds out of the box.

**Comment by WandeingLagomorph793** [comment]
Gotcha. Doesn't have to be a RSPI, but I'm thinking of running a server with this, so any small system should be good, if it works with Linux that's perfect but I don't expect that.

**Comment by cen1** [comment]
If you have a RPi, clone the repo and try to compile it, report the results, would be good to know if it builds or not and how hard it would be to make it build.
