### ISSUE TITLE
Master branch missing?

### ISSUE THREAD

**Issue by WandeingLagomorph793** [pvpgn/pvpgn-server#407]
Went to see if I could set this up on Linux (I'm running Manjaro 5.6.12.1, so Arch based) and foiund the master was missing.

**Comment by cen1** [comment]
Master branch exists. ??

**Comment by WandeingLagomorph793** [comment]
"As master branch is broken by last pull request, there is only develop is available to download from https://pvpgn.pro/download.html "

Someone mentioned it being broken, when I check that link there's *just* development branches, no master, apparently it got broken by a pull request.
