### ISSUE TITLE
W3 MOTD broken

### ISSUE THREAD

**Issue by RElesgoe** [pvpgn/pvpgn-server#408]
@HarpyWar 
> As `master` branch is broken by last pull request, there is only `develop` is available to download from https://pvpgn.pro/download.html
>
> There is a rubbish displayed instead of contents from `w3motd.txt` (it was correct in the latest `master`)
> https://forums.pvpgn.pro/viewtopic.php?id=2225
>
> ![изображение](https://user-images.githubusercontent.com/1132835/82733120-68babb00-9d1a-11ea-9c52-cb3438aacdd4.png)

**Comment by HarpyWar** [comment]
Still incorrect output (develop branch)

![WC3ScrnShot_070820_102818_04](https://user-images.githubusercontent.com/1132835/86892798-66b18d80-c109-11ea-9f12-28d4b8968762.png)

**Comment by RElesgoe** [comment]
@HarpyWar Latest commit fixes the extra 'I' character at the beginning of each line. My WC3 received the news correctly.
