### ISSUE TITLE
Which branch is more relevant?

### ISSUE THREAD

**Issue by venmade** [pvpgn/pvpgn-server#409]
Hi, which is more relevant from this?
https://github.com/pvpgn/pvpgn-server/tree/develop 
or
https://github.com/pvpgn/pvpgn-server/tree/feature-email
Now I see a complete transfer of everything to the develop branch
what about the new mail function?

**Comment by RElesgoe** [comment]
Use the `develop` branch.

**Comment by HarpyWar** [comment]
Use `develop` or `master` branch. 
Look for commit history on github to compare changes. `master` should be always main and stable, but now is `develop` for a period of time. 
Other branches are features which can be merged or not. Try it only if you have enough info about changes and how to test them.

**Comment by HarpyWar** [comment]
https://github.com/pvpgn/pvpgn-server/issues/337
