### ISSUE TITLE
CMake linux with mysql version has error.

### ISSUE THREAD

**Issue by Fatorin** [pvpgn/pvpgn-server#411]
I want build linux with mysql version, but when I follow step build , I get error and build failed.

I upload error message, please tell how can I fix this problem, thanks!
![ERROR](https://user-images.githubusercontent.com/23738444/83781533-41bc9b80-a6c1-11ea-838f-b76ab30e8156.png)

**Comment by HarpyWar** [comment]
It's because type `my_bool` was changed to `bool` in MySQL 8.x.
Use `develop` branch, it was fixed there https://github.com/pvpgn/pvpgn-server/commit/60f07511327e481751a9e69ee96e12865781fa26

**Comment by Fatorin** [comment]
Thank you so much , it's work!!!!! Very Thanks!!
