### ISSUE TITLE
Way to install on Arch?

### ISSUE THREAD

**Issue by WandeingLagomorph793** [pvpgn/pvpgn-server#412]
I'm on a Manjaro Linux distro and I'm trying to test out PVPGN, what's the best way to go about that? Looking at the build instructions and did some independent testing with WINE, which seems to work okay though being able to run this natively would be best.

**Comment by cen1** [comment]
You have instructions in main readme for general linux/ubuntu/debian/centos and fedora. Can't be much different for arch.

**Comment by WandeingLagomorph793** [comment]
Looks about right, apart from MySQL, that's MariaDB instead but everything else lines up.

Tried buidling it but at the 50% range I got this


[ 51%] Building CXX object src/bnetd/CMakeFiles/bnetd.dir/attrgroup.cpp.o
[ 52%] Building CXX object src/bnetd/CMakeFiles/bnetd.dir/attrlayer.cpp.o
[ 52%] Building CXX object src/bnetd/CMakeFiles/bnetd.dir/autoupdate.cpp.o
[ 53%] Building CXX object src/bnetd/CMakeFiles/bnetd.dir/channel_conv.cpp.o
[ 53%] Building CXX object src/bnetd/CMakeFiles/bnetd.dir/channel.cpp.o
In file included from /home/chao/pvpgn-server/src/bnetd/luainterface.h:26,
                 from /home/chao/pvpgn-server/src/bnetd/channel.cpp:47:
/home/chao/pvpgn-server/src/bnetd/luawrapper.h: In member function ‘void lua::vm::reg(const char*, const luaL_Reg*)’:
/home/chao/pvpgn-server/src/bnetd/luawrapper.h:106:4: error: ‘luaL_register’ was not declared in this scope; did you mean ‘lua_register’?
  106 |    luaL_register(st, package, members);
      |    ^~~~~~~~~~~~~
      |    lua_register
/home/chao/pvpgn-server/src/bnetd/luawrapper.h: At global scope:
/home/chao/pvpgn-server/src/bnetd/luawrapper.h:157:43: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
  157 |   void find(const char* name, int index = LUA_GLOBALSINDEX)
      |                                           ^~~~~~~~~~~~~~~~
/home/chao/pvpgn-server/src/bnetd/luawrapper.h: In constructor ‘lua::table::table(lua::vm&)’:
/home/chao/pvpgn-server/src/bnetd/luawrapper.h:359:55: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
  359 |   explicit table(vm& _vm) :stack(_vm.get_st()), index(LUA_GLOBALSINDEX)
      |                                                       ^~~~~~~~~~~~~~~~
/home/chao/pvpgn-server/src/bnetd/luawrapper.h: In constructor ‘lua::bind::bind(lua::vm&)’:
/home/chao/pvpgn-server/src/bnetd/luawrapper.h:396:14: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope
  396 |    cur_index(LUA_GLOBALSINDEX), mutex(_vm.mutex)
      |              ^~~~~~~~~~~~~~~~
make[2]: *** [src/bnetd/CMakeFiles/bnetd.dir/build.make:239: src/bnetd/CMakeFiles/bnetd.dir/channel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:975: src/bnetd/CMakeFiles/bnetd.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

**Comment by HarpyWar** [comment]
Make sure liblua 5.1  is installed. Greater versions are not supported.

**Comment by WandeingLagomorph793** [comment]
> Make sure liblua 5.1 is installed. Greater versions are not supported.

Looking for it now, all I'm finding are the most up to date versions of liblua, no 5.1 outside of an obscure site hosting for centOS

**Comment by cen1** [comment]
If you don't need any lua features you can also set WITH_LUA=false in cmake configure step.

**Comment by WandeingLagomorph793** [comment]
> If you don't need any lua features you can also set WITH_LUA=false in cmake configure step.

Cant recall a lot of lua specific features for what I'm doing, which is just a Warcraft III server, so I might try giving that one a shot, is there a file I edit to set that or is that in a configuration step after running the correct commands? Wanting to make sure I get it right.

**Comment by cen1** [comment]
remove the folder generated by cmake (usually called build) and rerun the cmake command from the readme, this time with the flag turned off
