### ISSUE TITLE
Error when they connecting on my created game.

### ISSUE THREAD

**Issue by bgamez23** [pvpgn/pvpgn-server#414]
![image](https://user-images.githubusercontent.com/1854368/87029662-04dd4a80-c213-11ea-9f5e-4d91ed779ef6.png)

**Comment by bgamez23** [comment]
i can join to other but they can't join if im the host

**Comment by MineSAT** [comment]
@bgamez23 the cliente needs port forward for open the NAT and play with others 😉

**Comment by bgamez23** [comment]
we are using private ip like hamachi so we still need to port forward?because we can still play if we use local area network but not working on battlenet
