### ISSUE TITLE
Latest plain build

### ISSUE THREAD

**Issue by StevenFredette** [pvpgn/pvpgn-server#418]
I keep getting I need libcurl.dll when I execute pvpgn console or pvpgn. (Not sure what dependency I need for windows.) I download from your site that has all the development binaries. I want to try the email features.

Window 10 current and windows server r2 20102.

**Comment by RElesgoe** [comment]
Download the DLL files from https://github.com/pvpgn/pvpgn-server/tree/develop/lib/curl/7.70.0 and place them in your pvpgn directory.

**Comment by StevenFredette** [comment]
> Download the DLL files from https://github.com/pvpgn/pvpgn-server/tree/develop/lib/curl/7.70.0 and place them in your pvpgn directory.

I tried above and got this error
![image](https://user-images.githubusercontent.com/31942238/91612523-9d5a9600-e94b-11ea-8a94-2a83d725c866.png)

Error: Window 2012 r2 64bit.

I will edit for windows 10.

**Comment by RElesgoe** [comment]
Try installing Microsoft Visual C++ Redistributable for Visual Studio 2019 x86
https://aka.ms/vs/16/release/VC_redist.x86.exe

**Comment by StevenFredette** [comment]
> Try installing Microsoft Visual C++ Redistributable for Visual Studio 2019 x86
> https://aka.ms/vs/16/release/VC_redist.x86.exe

That worked! Good Job! Thanks for quick reply as well.
