### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by StevenFredette** [pvpgn/pvpgn-server#419]
So not sure if i'm going crazy or pvpgn is using a lot more cpu over time. 

I edited the LUA script. handle_game.lua

function handle_game_create(game)
	channel_send_message("War2BNE", tostring(game.mapname) .. " hosted by " .. tostring(game.owner), message_type_info)
end

Works great to notify channel of game hosted but after 12 hours or so the cpu sadly went from 3% to 95% had to terminate the process and reopen to make server stable again.

I cannot use the latest development build with email because it has my cpu at 90% default.

**Comment by RElesgoe** [comment]
Try the latest commit (c2167e18a6fc26c40220f921b51698dc7d104db8)

**Comment by StevenFredette** [comment]
I'm still learning github. So I would need to recompile you do you have a compiled plain link?

**Comment by RElesgoe** [comment]
You can either compile or download from https://pvpgn.pro/download.html

**Comment by StevenFredette** [comment]
I am now on the latest dev version. 

The memory leak might have been fixed (Prior Updates). I need about 12-24 hours to tell. 

This definitely runs a lot better on the CPU. Thank YOU! 

If the memory leak on the LUA script is gone. I will close tomorrow. Thanks again!

**Comment by StevenFredette** [comment]
Sadly,

The leaks are still happening with the most current updated development. 

![image](https://user-images.githubusercontent.com/31942238/91645816-cdbb3680-ea16-11ea-8956-76b6c15f2876.png)

About 8 hours idle with 12 bots, the CPU went from 3% to 90%. If there is something I can do please let me know. The only difference from default should be the Lua script I mentioned above.

**Comment by StevenFredette** [comment]
The CPU stayed at 0 near most of the night. The RAM only increased by .5 MB. (The leak did not occur while the bots were offline.)

The name & version of the bot.
![image](https://user-images.githubusercontent.com/31942238/91654168-bdd23f80-ea74-11ea-9f43-346cf50257b3.png)

Bot configuration:

1. 14 accounts running (pvpgn handles multiple connections per IP.)
2. Spoof ping to 1ms
3. Same Channel
4. W2BN Client

I'm not sure if it's the packets going back and forth between the server or server code for concurrent connections is leaking. Hopefully, this update will help track down whatever is causing that CPU to rocket overtime when those bots connect.

I had about 15 players for 5-6 hours play many games with no issues last night as well. These players are from all over the world.

**Comment by HarpyWar** [comment]
Try run bots on different machine than pvpgn. Probably undefined udp packets cause this behavior because of the same udp port.
Set full logging `loglevels = fatal,error,warn,info,debug,trace` and look which actions from there may cause cpu load.

**Comment by StevenFredette** [comment]
> Try run bots on different machine than pvpgn. Probably undefined udp packets cause this behavior because of the same udp port.
> Set full logging `loglevels = fatal,error,warn,info,debug,trace` and look which actions from there may cause cpu load.

Yes, the bot's (my desktop), pvpgn (my VPS). I enabled more verbose debugging and the CPU is already at 5 CPU% for pvpgn. There is not much coming in the debug console.

There is a bad echo timing when they connect.

Aug 30 09:29:30 [info ] pvpgn::bnetd::conn_destroy: [628] closed bnet connection
Aug 30 09:29:30 [debug] pvpgn::bnetd::ipbanlist_check: lastcheck: 1598779563, now: 1598779770, now-lc: 207.
Aug 30 09:29:30 [debug] pvpgn::bnetd::ipbanlist_check: checking 50.90.128.16
Aug 30 09:29:31 [debug] pvpgn::bnetd::ipbanlist_check: address 50.90.128.16 does not match exact 76.119.98.17
Aug 30 09:29:31 [debug] pvpgn::bnetd::ipbanlist_check: address 50.90.128.16 does not match exact 76.119.98.17
Aug 30 09:29:31 [info ] pvpgn::bnetd::sd_accept: [628] accepted connection from 50.90.128.16:61078 on 0.0.0.0:6112
Aug 30 09:29:31 [debug] pvpgn::bnetd::conn_create: [628][616] sessionkey=0x1598800988 sessionnum=0x00000014
Aug 30 09:29:31 [debug] pvpgn::bnetd::sd_accept: [628] client connected to a bnet listening address
Aug 30 09:29:31 [info ] pvpgn::bnetd::handle_init_packet: [628] client initiated bnet connection
Aug 30 09:29:31 [trace] pvpgn::bnetd::conn_shutdown: [628] connection already closed
Aug 30 09:29:31 [debug] pvpgn::bnetd::conn_set_class: added latency check timer
Aug 30 09:29:31 [debug] pvpgn::bnetd::_client_auth_info: [628] AUTH_INFO packet { protocol=0x0, platform=IX86, product=W2BN, versionid=0x4f, language=SUne, localip=0x1dca8c0, tzbias=012c, locale=1033, language=1033, country=USA.United States }
Aug 30 09:29:31 [warn ] pvpgn::bnetd::conn_set_gamelang: got UNKNOWN gamelang
Aug 30 09:29:31 [debug] pvpgn::bnetd::_client_auth_info: [628] selected "ver-IX86-1.mpq" "A=3845581634 B=880823580 C=1363937103 4 A=A-S B=B-C C=C-A A=A-B"
Aug 30 09:29:31 [warn ] pvpgn::bnetd::_client_echoreply: [628] bad timing in echo reply: now=480442 then=0
Aug 30 09:29:31 [info ] pvpgn::bnetd::_client_authreq109: [628] CLIENT_AUTHREQ_109 ticks=0x5dc056da, verstr=2.0.2.0 exeinfo="WarCraft II BNE.exe 08/27/20 03:22:17 712704" versionid=0x0000004f gameversion=0x02000200 checksum=0xb52bad87
Aug 30 09:29:31 [info ] pvpgn::bnetd::_client_authreq109: [628] client matches versiontag "W2BN_202A"
Aug 30 09:29:31 [info ] pvpgn::bnetd::_client_authreq109: [628] no upgrade is available
Aug 30 09:29:31 [info ] pvpgn::bnetd::_client_loginreq2: [628] "Admin" logged in (correct password)
Aug 30 09:29:32 [error] pvpgn::bnetd::handle_bnet_packet: [628] unknown (logged in) bnet packet type 0x14ff, len 8
Aug 30 09:29:32 [error] pvpgn::bnetd::handle_bnet_packet: [628] unknown (logged in) bnet packet type 0x2dff, len 4
Aug 30 09:29:32 [info ] pvpgn::bnetd::conn_set_channel: [628] joined channel "The Void"
Aug 30 09:29:32 [debug] pvpgn::bnetd::class_topic::class_topiclist::get: returning nullptr
Aug 30 09:29:34 [info ] pvpgn::bnetd::conn_set_channel: [628] joined channel "War2USA"

I do have these which seem common with or without leak. 
Aug 30 09:22:32 [debug] pvpgn::bnetd::handle_udp_packet: [616] got udpping unknown1=350854750
Aug 30 09:23:00 [debug] pvpgn::bnetd::handle_udp_packet: [616] got udpping unknown1=1572973296
Aug 30 09:24:02 [debug] pvpgn::bnetd::handle_udp_packet: [616] got udpping unknown1=350944747
Aug 30 09:24:30 [debug] pvpgn::bnetd::handle_udp_packet: [616] got udpping unknown1=1573063296
Aug 30 09:25:32 [debug] pvpgn::bnetd::handle_udp_packet: [616] got udpping unknown1=351034744
Aug 30 09:26:00 [debug] pvpgn::bnetd::handle_udp_packet: [616] got udpping unknown1=1573153296

**Comment by HarpyWar** [comment]
Did you try master branch to make sure it was not caused by last changes? Or even this one https://github.com/pvpgn/pvpgn-server/releases/tag/1.99.7.2.1
First thoughts there is a "leak" somewhere in the code which increases a queue or like that, and every new iteration of that array takes more time.

Immediately after you stop bots cpu load on pvpgn server becomes normal, Is that correct?

**Comment by StevenFredette** [comment]
> Did you try master branch to make sure it was not caused by last changes? Or even this one https://github.com/pvpgn/pvpgn-server/releases/tag/1.99.7.2.1
> First thoughts there is a "leak" somewhere in the code which increases a queue or like that, and every new iteration of that array takes more time.
> 
> Immediately after you stop bots cpu load on pvpgn server becomes normal, Is that correct?

Its definitely wasn't caused by the latest build. I actualy havent updated since Finalize 1.99.7.2.1 release #362 is the version were I found the original leak. Now I'm on your latest dev build. Still here also.

Yes, once the bot got closed. The server CPU instantly went to 0%.

**Comment by HarpyWar** [comment]
The robust way (but may be not so fast in your case) is to try different commits to find where the issue was started.
Firstly try with disabled Lua to exclude it from suspicion (dont every commit, just once to check it works fine or not).

Brief tutor how to do it:
1) Install Visual C++ as it described in readme of the [Magic Builder](https://github.com/pvpgn/pvpgn-magic-builder) repo in "Requirements" and download Magic Builder itself.
2) Open commits history https://github.com/pvpgn/pvpgn-server/commits/master
3) Select any commit and click on `<>` to browse it's code.
4) Download ZIP of this point and unpack into `source` directory which is in Magic Builder root path. 
5) Run `build_pvpgn.bat` as usual and follow instructions. After build copy `release\`pvpgn.exe` (or `pvpgnconsole.exe`) and replace on your server to check it.
6) Repeat from step 2 if required. 
(*Hint: after first build you can run `rebuild_pvpgn.bat` to start build immediately with the parameters from the lastest build*)

Don't try every commit, first find which works fine. It can be far away from the current commit, so pass several pages and start from there. When you find it - follow backward to find the commit which contain the issue.

**Comment by RElesgoe** [comment]
If you only run 1 bot, how long would it take for CPU usage to go up?

**Comment by cen1** [comment]
Our SVN branch we use in production is using 100% CPU since we moved from freebsd to debian for unknown reasons. So it might be that there is some kind of resource leak even since 1.99. Luckily it does not seem to affect bnetd working normally in any way.

**Comment by StevenFredette** [comment]
> The robust way (but may be not so fast in your case) is to try different commits to find where the issue was started.
> Firstly try with disabled Lua to exclude it from suspicion (dont every commit, just once to check it works fine or not).
> 
> Brief tutor how to do it:
> 
> 1. Install Visual C++ as it described in readme of the [Magic Builder](https://github.com/pvpgn/pvpgn-magic-builder) repo in "Requirements" and download Magic Builder itself.
> 2. Open pvpgn commits history https://github.com/pvpgn/pvpgn-server/commits/master
> 3. Select any commit and click on `<>` to browse it's code.
> 4. Download the repo ZIP of this point and unpack into `source` directory which is in Magic Builder root path.
> 5. Run `build_pvpgn.bat` and follow instructions. After build copy `release\pvpgnconsole.exe` and replace on your server to check it.
> 6. Repeat from step 2 if required.
>    (_Hint: after first build you can run `rebuild_pvpgn.bat` to start build immediately with the parameters from the lastest build_)
> 
> Don't try every commit, first find which works fine. It can be far away from the current commit, so pass several pages and start from there. When you find it - follow backward to find the commit which contain the issue.

I would have to prepare for this bounty. I think that would take a great amount of time. It would have to occur next weekend.


> If you only run 1 bot, how long would it take for CPU usage to go up?

One bot connected and instantly seen CPU activity. Sits at 0% for 30 seconds then hops to .1% back to 0% hops to .2% back to 0% hops backs to .3%. Just in a matter of minutes.

**Comment by RElesgoe** [comment]
I believe the high CPU usage is related to https://stackoverflow.com/a/6296203
