### ISSUE TITLE
about Max Savefile size Help~~

### ISSUE THREAD

**Issue by MxCen** [pvpgn/pvpgn-server#424]
Diablo2 about what restrictions pvpgn has on Max Savefile size? Help~~

**Comment by MxCen** [comment]
`D2dbs-setup:
constexpr long kBufferSize = 1024L * 20L;
#define kMaxPacketLength	(1024 * 5)

D2cs-setup:
#define MAX_SAVEFILE_SIZE	32 * 1024`


Are there any other restrictions excluding the above?

**Comment by RElesgoe** [comment]
`d2dbs` may write up to _2^16_ bytes in a save file. `d2cs` will only handle save files up to _32 * 1024_ bytes long.
