### ISSUE TITLE
FreeBSD port has no maintainer :(

### ISSUE THREAD

**Issue by feraldruid22** [pvpgn/pvpgn-server#425]
I was just about to set this up to celebrate the new FreeBSD 12.2 release but sadly noticed the message from the ports.

```
SHA256 (pvpgn/pvpgn-1.8.5.tar.bz2) = 229607bb52a0c8bdc01e310ff7e0ca23c91d63d2a2ed2f7decaa3ddac40e57d5
SIZE (pvpgn/pvpgn-1.8.5.tar.bz2) = 982931
SHA256 (pvpgn/pvpgn-support-1.2.tar.gz) = 5ab2cf15d9957dabbf60ea46c12bf6d4704aaead4ac358e85f5ef8494330d51f
SIZE (pvpgn/pvpgn-support-1.2.tar.gz) = 125345
```
Quite old version as well.
Also did some of you guys ever managed to run the Diablo 2 world instance server with Wine on FreeBSD?

**Comment by cen1** [comment]
I am surprised FreeBSD even allows obsolete packages with no mainteners in the ports tree.

Realistically there is no point in having pvpgn in any sort of repo since there is nobody to keep them up to date. Code is mostly in maintenance mode with occasional massive rewrites so package updates would be insufferable.

As for d2, no idea.

**Comment by RElesgoe** [comment]
Technically, this is a fork of the official PvPGN project, so that port is kind of unrelated to this repository.

For running D2GS with WINE, I would ask the guys at [DIABLO2.ORG](https://discord.com/invite/FkFJNBu).

**Comment by feraldruid22** [comment]
According to your github commits this project still seems to be developed but now you say that the one in FreeBSD is something else not related to this. I need the latest up to date version, then I should just take it from here from your git and build it?

**Comment by cen1** [comment]
Version 1.8.5 is the original source code when it was hosten on berlios. That repo and original developers are now long gone, this repo is technically "pvpgn.pro" and is a continuation/fork of the original codebase. Right now this repo is the only one which gets any kind of work being done.

Pre-fork version is 1.99-SVN which can be found here https://github.com/d1zzy/pvpgn

I suggest you clone the develop branch of this repo and build it youself.
