### ISSUE TITLE
With Diablo II, bnetd quits with "FATAL ERROR: argument index out of range"

### ISSUE THREAD

**Issue by johannes87** [pvpgn/pvpgn-server#426]
OS: Ubuntu 18.04.5, I followed the instructions in the README.

To reproduce:
I start bnetd, then d2cs, then d2dbs as root (sometimes with -D command line switch so it runs in the foreground)
In Diablo II, I go to Battle.net, and can register a user, and create a character.
When creating a game, "bnetd" quits with the message:

    FATAL ERROR: argument index out of range

In Diablo II, it shows the "You are in line to create a game" message, and that my position in line is 1.

In the config files I changed: `gameservlist` and `bnetaddr` in `d2cs.conf`, as well as `gameservlist` in `d2dbs.conf` and I also removed the comment in `realms.conf` and put my IP address in there. IP address is like "192.168.122.23", I didn't use 127.0.0.1.

Expected: 
After I click to create a game, I can play

**Comment by RElesgoe** [comment]
Did you compile from the `develop` branch?

**Comment by johannes87** [comment]
Thank you for the quick answer! I tried it with the develop branch, the error doesn't occur anymore. But I'm still stuck in the queue, with position=1. Should I create another issue for this?

**Comment by RElesgoe** [comment]
You probably didn't set up D2GS correctly. Make sure that `D2CSIP` and `D2DBSIP` are correct in `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\D2Server\D2GS`.
