### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by StevenFredette** [pvpgn/pvpgn-server#428]
Hey,

I was testing out the latest development build as of 12/15/2020. The command "/mail s username" and the same user with a full mailbox outputs.

![image](https://user-images.githubusercontent.com/31942238/102207792-93c65100-3e9c-11eb-9f97-d818cfda689b.png)

The person I was sending a message to is female. Change the word "his" to "the".

**Comment by RElesgoe** [comment]
I think "their" is a better word to use.

**Comment by StevenFredette** [comment]
> I think "their" is a better word to use.

Excellent thanks!
