### ISSUE TITLE
Crash on /rehash all

### ISSUE THREAD

**Issue by StevenFredette** [pvpgn/pvpgn-server#429]
The "rehash all" command has always made PVPGN PRO crash no matter the version I used.

I would normally get a crash dump to post... but it no longer seems to create those dumps.

If you use the /rehash all command a few times the pvpgn will become unstable and randomly crash anytime.... a few hours later I'm notified the server went down. Over the years I've trained myself to just reboot the whole server just to refresh files. Another way I found to repeat this is to spam the /rehash all command really fast...

**Comment by HarpyWar** [comment]
That's known bug coming from 1.99. Need to debug this issue carefully.

**Comment by StevenFredette** [comment]
Yeah, I saw another person with this issue in another thread. They were told to post a new topic and never did. So I guess I will do that as well. I checked into my recycle bin and I actually do have two older dump files from crashes they seem to hold critical data so can I share those in private somehow?

**Comment by HarpyWar** [comment]
The issue can be easily reproduced so no need dumps here.

BTW, to debug dump files you must have an appropriate symbol file (.pdb) + source code from the same code base (better commit id on github). Dump files are useless without this data.

**Comment by StevenFredette** [comment]
> The issue can be easily reproduced so no need dumps here.
> 
> BTW, to debug dump files you must have an appropriate symbol file (.pdb) + source code from the same code base (better commit id on github). Dump files are useless without this data.

@HarpyWar I appreciate all the great information. I was very curious about how those dumps actually worked. If there is something I can do or try let me know.
