### ISSUE TITLE
address_translate with ddns

### ISSUE THREAD

**Issue by qqqwqk** [pvpgn/pvpgn-server#432]
domain name to Dynamic IP check is always Run or just once？
example：
i don‘t have Static public IP but has Dynamic public IP
if enter a domain name at address_translate.conf  
as 
"192.168.1.117:6112 mydomain.xyz 192.168.1.0/24 any"
and setted my router
now,i‘m very sure that my friends can join me.
but,when Dynamic IP has changed,all user can't found servers untill D2CS restarted

**Comment by RElesgoe** [comment]
Just once.

Duplicate: #348
