### ISSUE TITLE
(WOL) Renegade Server Detection

### ISSUE THREAD

**Issue by Sora012** [pvpgn/pvpgn-server#433]
The issue is that `src/common/tag.cpp` is setup to match Renegade, and the Renegade "Dedicated" server to seperate tags resulting in "lobby not listing" when a Renegade client requests servers from the WOL list.

A simple fix is:

https://github.com/pvpgn/pvpgn-server/blob/master/src/common/tag.cpp#L489
Change `return CLIENTTAG_RENGDFDS_UINT;` to `return CLIENTTAG_RENEGADE_UINT;`

**Comment by behod** [comment]
Hello the PVPGN westwood server cant start game
![Uploading QQ截图20230810205732.png…]()
