### ISSUE TITLE
error: 'my_true' was not declared in this scope

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#434]
For mysql 8 need use int

![image](https://user-images.githubusercontent.com/6318282/104416011-c14b0b00-55be-11eb-8a6e-c8d474f9eb08.png)

**Comment by HarpyWar** [comment]
It's done in `develop`  branch https://github.com/pvpgn/pvpgn-server/commit/60f07511327e481751a9e69ee96e12865781fa26
