### ISSUE TITLE
Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by TemKaSD** [pvpgn/pvpgn-server#435]
Ubuntu 20.04 develop version compile error: Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)

Need install:
sudo apt-get install libcurl4-openssl-dev

**Comment by RElesgoe** [comment]
What's the problem? Just run that command to install libcurl and then rerun cmake

**Comment by TemKaSD** [comment]
> What's the problem? Just run that command to install libcurl and then rerun cmake

No problem. Add to manual install command apt-get install libcurl4-openssl-dev
