### ISSUE TITLE
trans_net: no match found for ... Cannot create character after account creation.

### ISSUE THREAD

**Issue by hashborgir** [pvpgn/pvpgn-server#441]
Server setup and configured. I can connect with my D2SE mod, however, after account creation when I try to create a character, I get the error: a character with this name already exists on this realm.

Mar 03 11:02:36 [debug] trans_net: checking ip:6113 for client ip ...
Mar 03 11:02:36 [debug] trans_net: no match found for ip:6113 (not translated)
Mar 03 11:02:36 [debug] on_d2cs_accountloginreq: user Hash loggedin on d2cs

I've searched google and looked through the issues here and I'm unsure what could be happening.

**Comment by hashborgir** [comment]
I edited the user/group to run pvpgn as 'root' in the config file, and I also turned off localization (I assume that what transset was about? I've not looked through the source yet).

I can now create characters. 

I assumed it might have been either due to permission or locatlization. Could someone shed more light on this?

**Comment by RElesgoe** [comment]
It might have something to do with permissions. Try resetting everything back to the way it was and then try running each executable with sudo/as root user and again without sudo/as root user.
