### ISSUE TITLE
Unable to create/join game: Always first/1 in line to join game after creation.

### ISSUE THREAD

**Issue by hashborgir** [pvpgn/pvpgn-server#443]
I have went through all the configuration files very carefully multiple times. I think everything is setup correctly. However, when I try to create game:

"Your position in line is: 1" And it stays there. Please advise. Let me know if you want me to share my configs, or which parts of them.

**Comment by hashborgir** [comment]
I see this has to do with d2gs now and it's not supported here, so no problem. At least we know what this issue relates to. Unless I'm incorrect.

**Comment by RElesgoe** [comment]
It ultimately means that d2gs isn't connected to d2cs. A possible scenario is that d2gs didn't attempt to connect to d2cs because it failed to first connect to d2dbs.

The logs should have enough information for you to determine what went wrong.
