### ISSUE TITLE
Question: Default MOTD Location?

### ISSUE THREAD

**Issue by SoraBytes** [pvpgn/pvpgn-server#448]
Where is the default MOTD location? My server spits out "Failed to load MOTD, Sending default MOTD" I've tried modifying the i18n MOTD, and creating one in /etc/pvpgn but that doesn't seem to work. The /motd command works just fine though?

I did install the service with a prefix install location, unsure if that affects the MOTD though.

> cmake -DCMAKE_INSTALL_PREFIX=/home/gameservers/services/pvpgn -DWITH_MYSQL=true ../

**Comment by RElesgoe** [comment]
Can you post bnetd.log

**Comment by SoraBytes** [comment]
[removed bnetd.log forgot APGAR]

**Comment by RElesgoe** [comment]
Can you check if the latest commit fixes it

**Comment by SoraBytes** [comment]
Just pulled develop branch and compiled, and it still is failing to send the actual motd on first login.

**Comment by RElesgoe** [comment]
This latest commit should fix it.

**Comment by SoraBytes** [comment]
That fixed it thanks!
