### ISSUE TITLE
PVPGN Version Checking

### ISSUE THREAD

**Issue by hunelDev** [pvpgn/pvpgn-server#455]
When I use version 1.14d client everyting is okey.
Whenever I changed client version to 1.13c in this time I set d2cs_version to 0.
I expect not checking version by pvpgn but it's still checking.I also checked source code to fix this issue.But I couldn't do that.
How can I set my version checking to false ?

**Comment by RElesgoe** [comment]
In `bnetd.conf`, set `allow_bad_version = true` and `allow_unknown_version = true`.

**Comment by hunelDev** [comment]
everything true but. It cannot be about version checking 

Apr 14 13:45:34 [debug] pvpgn::bnetd::ipbanlist_check: lastcheck: 1618397080, now: 1618397134, now-lc: 54.
Apr 14 13:45:34 [debug] pvpgn::bnetd::ipbanlist_check: checking 192.168.0.18
Apr 14 13:45:35 [info ] pvpgn::bnetd::sd_accept: [1064] accepted connection from 192.168.0.18:49283 on 0.0.0.0:6112
Apr 14 13:45:35 [debug] pvpgn::bnetd::conn_create: [1064][1056] sessionkey=0x1618384207 sessionnum=0x00000002
Apr 14 13:45:35 [debug] pvpgn::bnetd::sd_accept: [1064] client connected to a bnet listening address
Apr 14 13:45:35 [info ] pvpgn::bnetd::handle_init_packet: [1064] client initiated bnet connection
Apr 14 13:45:35 [trace] pvpgn::bnetd::conn_shutdown: [1064] connection already closed
Apr 14 13:45:35 [debug] pvpgn::bnetd::conn_set_class: added latency check timer
Apr 14 13:45:35 [debug] pvpgn::bnetd::handle_udp_packet: [1056] got UDPTEST packet from 192.168.0.18:6112 (myself?)
Apr 14 13:45:35 [debug] pvpgn::bnetd::handle_udp_packet: [1056] got UDPTEST packet from 192.168.0.18:6112 (myself?)
Apr 14 13:45:35 [debug] pvpgn::bnetd::_client_auth_info: [1064] AUTH_INFO packet { protocol=0x0, platform=IX86, product=D2XP, versionid=0xd, language=enUS, localip=0x1200a8c0, tzbias=ffffff4c, locale=1055, language=1055, country=TUR.Turkey }
Apr 14 13:45:35 [info ] pvpgn::bnetd::conn_set_gamelang: [1064] setting client gamelang to "enUS"
Apr 14 13:45:35 [debug] pvpgn::bnetd::_client_auth_info: [1064] selected "IX86ver1.mpq" "A=3845581634 B=880823580 C=1363937103 4 A=A-S B=B-C C=C-A A=A-B"
Apr 14 13:45:36 [debug] pvpgn::bnetd::sd_tcpinput: [1064] read returned -1 (closing connection)
Apr 14 13:45:36 [info ] pvpgn::bnetd::conn_destroy: [1064] closed bnet connection
Apr 14 13:45:38 [debug] pvpgn::bnetd::guiOnClose: GUI wants server dead...

my bnet.log

Apr 14 13:45:35 [trace] pvpgn::bnetd::conn_shutdown: [1064] connection already closed.Why my connection already closed ?

**Comment by hunelDev** [comment]
my problem is my client is not working with win xp sp3 mod :)
