### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by ChrisCatCP** [pvpgn/pvpgn-server#457]
i create the account But no matter what password I use, the acct_passhash1 fields inserted in the database are consistent
This is part of my log file

May 10 06:03:38 [trace] sql_write_attrs: multi-update query: UPDATE pvpgn_BNET SET acct_ctime = '1620626618', acct_userid = '2', acct_passhash1 = '67452301efcdab8998badcfe10325476c3d2e1f0', acct_username = 'chriscp' WHERE uid = '2'

May 10 06:07:43 [trace] sql_write_attrs: multi-update query: UPDATE pvpgn_BNET SET acct_ctime = '1620626863', acct_userid = '3', acct_passhash1 = '67452301efcdab8998badcfe10325476c3d2e1f0', acct_username = 'test' WHERE uid = '3'

Different passwords get the same acct_passhash1
67452301efcdab8998badcfe10325476c3d2e1f0

i cant login the account

**Comment by RElesgoe** [comment]
What client are you using?

**Comment by ChrisCatCP** [comment]
war3 1.27a  english

**Comment by RElesgoe** [comment]
Which branch is your pvpgn compiled from?

**Comment by ChrisCatCP** [comment]
master   branch

**Comment by RElesgoe** [comment]
Try compiling from the `develop` branch.

**Comment by ChrisCatCP** [comment]
thanks!  
I will try

**Comment by ChrisCatCP** [comment]
> Try compiling from the `develop` branch.

i compiling from the develop branch  then i can login in now
