### ISSUE TITLE
May 30 development version error

### ISSUE THREAD

**Issue by MxCen** [pvpgn/pvpgn-server#458]
May 30 development version

bnetd.log
Jun 16 14:26:40 [info ] pvpgn::bnetd::_client_authreq109: [660] client matches versiontag "Diablo II - 20210612"
Jun 16 14:26:40 [info ] pvpgn::bnetd::_client_authreq109: [660] no upgrade is available
Jun 16 14:26:40 [info ] pvpgn::bnetd::_client_fileinforeq: [660] file requested: "bnserver-D2DV.ini" - type = 0x80000004
Jun 16 14:26:40 [info ] pvpgn::bnetd::sd_accept: [668] accepted connection from 60.171.114.162:16587 on 0.0.0.0:6112
Jun 16 14:26:40 [info ] pvpgn::bnetd::handle_init_packet: [668] client initiated file download connection
Jun 16 14:26:40 [info ] pvpgn::bnetd::_client_authreq109: [656] CLIENT_AUTHREQ_109 ticks=0xc1e777c3, verstr=1.0.13.4 exeinfo="Game.exe 06/05/21 15:53:32 44032" versionid=0x0000000d gameversion=0x01000d04 checksum=0x7b173520
Jun 16 14:26:40 [info ] pvpgn::bnetd::_client_authreq109: [656] client matches versiontag "Diablo II - 20210612"
Jun 16 14:26:40 [info ] pvpgn::bnetd::_client_authreq109: [656] no upgrade is available
Jun 16 14:26:41 [info ] pvpgn::bnetd::file_send: [668] sending file "bnserver-D2DV.ini" ("files/bnserver-D2DV.ini") of length 336
Jun 16 14:26:41 [error] pvpgn::bnetd::handle_bnet_packet: [628] unknown (connected) bnet packet type 0x3eff, len 39
Jun 16 14:26:41 [info ] pvpgn::bnetd::_client_fileinforeq: [656] file requested: "bnserver-D2DV.ini" - type = 0x80000004
Jun 16 14:26:41 [info ] pvpgn::bnetd::conn_destroy: [668] closed file connection
Jun 16 14:26:41 [info ] pvpgn::bnetd::sd_accept: [668] accepted connection from 113.57.182.226:53147 on 0.0.0.0:6112
Jun 16 14:26:41 [info ] pvpgn::bnetd::sd_accept: [616] accepted connection from 59.33.250.69:64336 on 0.0.0.0:6112
Jun 16 14:26:41 [info ] pvpgn::bnetd::handle_init_packet: [668] client initiated file download connection

d2dbs.log
Jun 16 14:25:56 [info ] pvpgn::d2dbs::dbs_packet_getdata_charinfo: loaded charinfo iceasn(*yyqboy99) for gs 10.0.4.6(1)
Jun 16 14:25:56 [info ] pvpgn::d2dbs::dbs_packet_fix_charinfo: updating charinfo for ICEasn -> level = 105 , status = 0x0F68 , pstatus = 0x9EE8
Jun 16 14:25:56 [info ] pvpgn::d2dbs::dbs_packet_savedata_charinfo: saved charinfo iceasn(*yyqboy99) for gs 10.0.4.6(1)
Jun 16 14:25:56 [info ] pvpgn::d2dbs::dbs_packet_updateladder: update ladder for ICEasn@Resurgence for gs 10.0.4.6(1)
Jun 16 14:26:08 [info ] pvpgn::d2dbs::dbs_packet_getdata: lock char RUAAAAAAAAA(*wyg332)@Resurgence for gs 10.0.4.6(1)
Jun 16 14:26:08 [info ] pvpgn::d2dbs::dbs_packet_getdata_charsave: loaded charsave ruaaaaaaaaa(*wyg332) for gs 10.0.4.6(1)
Jun 16 14:26:08 [info ] pvpgn::d2dbs::dbs_packet_getdata_charinfo: loaded charinfo ruaaaaaaaaa(*wyg332) for gs 10.0.4.6(1)
Jun 16 14:26:28 [error] pvpgn::packet_get_size: packet has bad size 3335
Jun 16 14:26:28 [error] pvpgn::packet_get_size: packet has bad size 3335
Jun 16 14:26:28 [warn ] pvpgn::net_recv_packet: [304] corrupted packet received (total_size=0 currsize=8) (closing connection)
Jun 16 14:26:28 [info ] pvpgn::d2dbs::conn_destroy: [304] unlock all characters on gs 10.0.4.6(1)
Jun 16 14:26:28 [info ] pvpgn::d2dbs::conn_destroy: [304] closed d2gs connection

**Comment by RElesgoe** [comment]
Can you try setting `MAX_PACKET_SIZE` to `65535` in https://github.com/pvpgn/pvpgn-server/blob/develop/src/common/field_sizes.h#L21 and try testing that change.

**Comment by MxCen** [comment]
[D2DBSConsole_20210902_040130.zip](https://github.com/pvpgn/pvpgn-server/files/7096059/D2DBSConsole_20210902_040130.zip)

Close D2DBSConsole will generate this file

Windows service mode starts, resulting in

**Comment by MxCen** [comment]
[log.zip](https://github.com/pvpgn/pvpgn-server/files/7096076/log.zip)
