### ISSUE TITLE
D2GS logs spam

### ISSUE THREAD

**Issue by qyh214** [pvpgn/pvpgn-server#462]
branch:master
I set log to off. logs now show empty in d2gs/: but in d2gs/log/ will spam a lot of logs,like:
- 08-30 10:30
- 08-30 10:31
- 08-30 10:32

seems like Automatic archiving of logs.

how to close it?in HKEY_LOCAL_MACHINE\Software\D2Server I don't see this setting

**Comment by MxCen** [comment]
"EnableGSLog"=dword:00000001
"EnableGELog"=dword:00000001

to：

"EnableGSLog"=dword:00000000
"EnableGELog"=dword:00000000

**Comment by qyh214** [comment]
> "EnableGSLog"=dword:00000001
> "EnableGELog"=dword:00000001
> 
> to：
> 
> "EnableGSLog"=dword:00000000
> "EnableGELog"=dword:00000000

I have set it.logs now is empty. 

BUT the archive folder is created every minute and the empty log file is placed in it.

how to close the archieve feature?(now I may need to manually delete archived log folders every few days)

**Comment by RElesgoe** [comment]
@qyh214 Please try asking for help at **#pvpgn-d2gs-support** at [Discord - DIABLO2.ORG](https://discord.com/invite/FkFJNBu)
