### ISSUE TITLE
[question] Is there any support for `Mental Omega 3.3.6` (Yuri's mod)?

### ISSUE THREAD

**Issue by ryuujo1573** [pvpgn/pvpgn-server#473]
thank you for your work.

**Comment by SoraBytes** [comment]
It really depends on how far the mod has altered the game. Provided the mod doesn't alter the westwood online internet components of Red Alert 2 internet play. It -might- work.

WOL is basically a modified IRC protocol, and plain text at that, so it should be simple to test and debug. You can build the latest develop branch and test against it. You will also need to uncomment the westwood online section in the configuration file.

If I recall correctly, Red Alert 2 uses the v2 protocol, which is port 4005. You will also need to modify the hosts file, on linux or windows (which ever is playing Red Alert 2) to point to the PvPGN server.

The following should be enough to get a loopback connection to PvPGN.
`127.0.0.1 irc.westwood.com gameres.westwood.com servserv.westwood.com apireg.westwood.com`

**Comment by ryuujo1573** [comment]
Thanks for your considerate reply! I'll have a try asap. 😊
