### ISSUE TITLE
How do I add a Warcraft II: BNE server using the Universal Battle.NET Gateway Editor?

### ISSUE THREAD

**Issue by eband** [pvpgn/pvpgn-server#474]
For games that are other than Starcraft, Warcraft III, and Diablo II, how would I configure the BAT file so that the server is added?

For instance, I am trying to play on a Warcraft II: Battle.NET Edition Server.

**Comment by HarpyWar** [comment]
Warcraft 2 reads Battle.net server settings in the same way as Starcraft.
