### ISSUE TITLE
魔兽争霸3冰封王座创建游戏后别人无法进入房间？

### ISSUE THREAD

**Issue by hackzy** [pvpgn/pvpgn-server#493]
如题，服务器没有提示错误，游戏提示不能发现你所试图进入的游戏。

**Comment by zd0029** [comment]
请问你的pvpgn部署在本地还是云服务器上

**Comment by hackzy** [comment]
在云服务器上的 我抓了下包 客户端这边没收到任何服务器发来的包> 请问你的pvpgn部署在本地还是云服务器上

**Comment by hackzy** [comment]
服务端版本:pvpgn-master-1.99.7.2.1-PRO_sqlite
游戏版本:1.24e

**Comment by zd0029** [comment]
我也是云服务，进入游戏5秒，客户端提示你已断开连接

**Comment by hackzy** [comment]
我怀疑有端口没放开 我只放开了6112和6200

**Comment by zd0029** [comment]
我也只放开了这两个

**Comment by zd0029** [comment]
Aug 24 16:31:54 [debug] trans_net: checking 115.60.178.164:6112 for client 115.60.178.164 ...
Aug 24 16:31:54 [debug] trans_net: against entry -> 0.0.0.0:6200 output IP:6200 network 0.0.0.0/0x00000000
Aug 24 16:31:54 [debug] trans_net: entry does match input address
Aug 24 16:31:54 [debug] trans_net: no match found for 115.60.178.164:6112 (not translated)
Aug 24 16:31:54 [trace] handle_anongame_join: i = 0
Aug 24 16:31:54 [debug] trans_net: checking 115.60.178.164:6112 for client 115.60.178.164 ...
Aug 24 16:31:54 [debug] trans_net: against entry -> 0.0.0.0:6200 output IP:6200 network 0.0.0.0/0x00000000
Aug 24 16:31:54 [debug] trans_net: entry does match input address
Aug 24 16:31:54 [debug] trans_net: no match found for 115.60.178.164:6112 (not translated)
Aug 24 16:31:58 [trace] handle_w3route_packet: [11] got LOADINGDONE, playernum: 1
Aug 24 16:31:58 [trace] handle_w3route_packet: [12] got LOADINGDONE, playernum: 2

**Comment by hackzy** [comment]
跟你一样的提示 没法连上 看起来是服务端只是提供登录功能 没有内网穿透或者代理

**Comment by zd0029** [comment]
局域网内两台电脑是可以开局的，跨域的话可能需要组网才能联机

**Comment by hackzy** [comment]
那这服务器有啥用 有局域网了 我还上这个干啥 直接局域网联机不就行了

**Comment by XuQianJin-Stars** [comment]
> 局域网内两台电脑是可以开局的，跨域的话可能需要组网才能联机

我想用云主机搭建一台war3服务器用于远程组网可以实现么？

**Comment by hackzy** [comment]
不行 这个是局域网用的

**Comment by zd0029** [comment]
> > 局域网内两台电脑是可以开局的，跨域的话可能需要组网才能联机
> 
> 我想用云主机搭建一台war3服务器，用于远程组网可以实现么？

可以
