### ISSUE TITLE
0x4B SID_EXTRAWORK

### ISSUE THREAD

**Issue by HarpyWar** [pvpgn/pvpgn-server#72]
After sending *server &rarr; client* [SID_REQUIREDWORD](https://bnetdocs.org/?op=packet&pid=182) packet, client should download mpq file and then call `ExtraWork` function from dll inside of mpq, with sending output from the function back from *client &rarr; server* [SID_EXTRAWORK](https://bnetdocs.org/?op=packet&pid=240). 

I found two different versions of `IX86ExtraWork.dll` from official Battle.net and add one of them into `IX86ExtraWork.mpq` using MpqEditor. This file correctly received by a game client (I tried DIablo 2, Warcraft3 and Starcraft), but then nothing happened (no response from the client).

I even create own dll that shows messagebox, but it doesn't work too. You can try it by yourself [ExtraWorkTest.zip](https://mega.co.nz/#!adFxWZjY!c4G8EjXJFNkUvV3sEDB9w6vJ5Uqz4UOKWnUmRizCHT4)
Code for ExtraWork.exe was taken from [here]
(http://forum.valhallalegends.com/index.php/topic,7248.msg65278.html#msg65278):
```c++
#include <windows.h>
#include <iostream>

using namespace std;

typedef bool (__fastcall *ExtraWorkProc)(void *);

enum GameType {
  Diablo2 = 1,
  Warcraft3 = 2,
  Starcraft = 3,
  WorldOfWarcraft = 4
};

struct EXTRAWORK {
  WORD GameType;
  WORD Length;
  char OutBuffer[1024];
};

int main() {
   HINSTANCE      hLib;
   ExtraWorkProc   lpfnExtraWork;
   BOOL         bReturn;
   EXTRAWORK      ew;

   hLib = LoadLibrary("IX86ExtraWork.dll");

   bool success = false;
   if (hLib) {
      lpfnExtraWork = (ExtraWorkProc)GetProcAddress(hLib, "ExtraWork");

      if (lpfnExtraWork) {
         bReturn = (*lpfnExtraWork)(&ew);

         cout << "ExtraWork returned " << (bReturn?"TRUE":"FALSE") << endl;
         cout << "GameType: " << ew.GameType << "\t\t" << "Length: " << ew.Length << endl << endl;
         cout << "Message: " << ew.OutBuffer << endl;
         
         success = true;
      }
      FreeLibrary(hLib);
   }
   if (!success)
      cout << "Could not load " << "IX86ExtraWork.dll" << endl;

   return 0;
}
```

**Comment by HarpyWar** [comment]
@tesseract2048 the same error occured in Starcraft and Diablo 2 with official DLL from Battle.net, that I found in the internet (link in the first message of the topic). But I can't find original MPQ - only DLL, then it was signed with your library using [MPQSigner](https://github.com/xboi209/MPQSigner).

**Comment by tesseract2048** [comment]
`ExtraWork.cpp`

```
#include <Windows.h>

 __declspec(dllexport) BOOL __fastcall ExtraWork(void *) {
	 MessageBoxA(NULL, "it worked", NULL, MB_OK);
	 return FALSE;
}
```

`ExtraWork.def`

```
LIBRARY
	ExtraWork

EXPORTS
	ExtraWork
```

Code above worked for me, to be more specific:
* `dllexport` should be specified, and should be forced to have that name by defining in `ExtraWork.def`
* `__fastcall` should be used.

**Comment by xboi209** [comment]
So ````__declspec(dllexport)```` was missing from my code, everything is good now.

**Comment by cen1** [comment]
Here is a wild idea: can this packet be pushed in the connecting to server stage and make W3 patch itself instead of using w3lh loader?

**Comment by xboi209** [comment]
That might actually be possible. Client will start the logon sequence using SID_AUTHINFO and instead of immediately replying back to that packet, we could try sending ExtraWork to disable server signature verification before replying.

**Comment by cen1** [comment]
If someone has time, try to push AlertBox before the logon sequence and see what happens.

**Comment by xboi209** [comment]
For what purpose?

**Comment by cen1** [comment]
I guess to see if the game accepts packets out of the blue like this.

**Comment by cen1** [comment]
I have added ```conn_client_requiredwork(c, "IX86ExtraWork.mpq");``` in handle_init.cpp line 74 which should be asap after successful connection, placed the above provided IX86ExtraWork.mpq to ./var/files but nothing happened. Am I doing something wrong?

**Comment by xboi209** [comment]
I don't think that's an acceptable place to put it(for clean code). I would suggest placing it in ````handle_bnet.cpp```` at line 568. This is still bad code because ideally we should confirm that the client completely downloaded the file before the server moves on with the connection process.

**Comment by cen1** [comment]
This is just for testing purpose so position is far from final. I'll check it out.

**Comment by cen1** [comment]
Ok, I tried to put it where you recommended but EXTRAWORK is never sent from the client. Then I tried to put it on channel join just for a sanity check and it worked:
```Apr 19 10:20:22 [info ] pvpgn::bnetd::_client_fileinforeq: [600] file requested: "IX86ExtraWork.mpq" - type = 0xa0000006
Apr 19 10:20:22 [debug] pvpgn::bnetd::_client_extrawork: [600] Received EXTRAWORK packet with GameType: 2 and Length: 29 (IX86ExtraWork v1.0 by xboi209)
```
still no alertbox tho (I believe the above attached mpq was supposed to work for w3?).

**Comment by RElesgoe** [comment]
[ExtraWork has matured and has been placed under the PvPGN organization](https://github.com/pvpgn/ExtraWork).
