### ISSUE TITLE
Error when making code on Mac

### ISSUE THREAD

**Issue by ferologics** [pvpgn/pvpgn-server#8]
mp41:build H$ make
[  8%] Built target compat
[  8%] Building CXX object src/common/CMakeFiles/common.dir/fdwatch.o
In file included from /Users/H/Documents/gitprojects/pvpgn/src/common/fdwatch.cpp:29:
In file included from /Users/H/Documents/gitprojects/pvpgn/src/common/fdwatch_select.h:31:
/Users/H/Documents/gitprojects/pvpgn/src/common/fdwbackend.h:36:42: error: reference to type
      'const std::string'
      (aka 'const basic_string<char, char_traits<char>, allocator<char> >') could not bind to
      an lvalue of type 'const char [1]'
                        explicit InitError(const std::string& str = "")
                                                              ^     ~~
/Users/H/Documents/gitprojects/pvpgn/src/common/fdwbackend.h:36:42: note: passing argument to
      parameter 'str' here
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/fdwatch.o] Error 1
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2

this spits my terminal, any idea what caused this?

**Comment by xboi209** [comment]
@ferologics what's the version of your OS and compiler?

**Comment by ferologics** [comment]
damn, this was a long time ago, I believe it was Mavericks, compiler, no idea, cmake something, sry :/
