### ISSUE TITLE
Lost Connection (crash) When use some command in ghost

### ISSUE THREAD

**Issue by anonbyte** [pvpgn/pvpgn-server#93]
![wc3scrnshot_082814_180315_03](https://cloud.githubusercontent.com/assets/7726432/4074620/7ad90152-2ea3-11e4-8d2f-f7a803df9569.jpg)

bnetd crash when i use command like :
!comp !open

**Comment by xboi209** [comment]
Does this problem still persist?

**Comment by anonprophet** [comment]
its fixed, u can close this
